import type { CalculatorEntry } from '../../types/calculator';

export const automotiveCalculators: CalculatorEntry[] = [
  {
    id: 'engine-horsepower-calculator',
    title: 'Engine Horsepower Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'Engine Horsepower Calculator',
    description: 'Calculate engine horsepower from torque and RPM using the classic formula HP = (Torque x RPM) / 5252. Free, instant, and accurate.',
    category: 'Automotive',
    categorySlug: 'automotive',
    subCategory: 'Performance & Maintenance',
    seoKeywords: ['engine horsepower calculator', 'torque to horsepower', 'HP from torque and rpm', '5252 constant', 'engine power calculator', 'dyno horsepower', 'crank horsepower', 'kW calculator'],
    schema: 'both',
    mathSolverExpression: 'HP = (Torque x RPM) / 5252 | kW = (Nm x RPM) / 9549',
    reviewedBy: 'Vehicle maintenance specialist',
    lastVerified: '2026-01-15',
    relatedIds: ['horsepower-calculator', 'fuel-cost-calculator', 'tire-size-calculator'],
    loader: () => import('../math/engine-horsepower/index'),
  },
  {
    id: 'horsepower-calculator',
    title: 'Horsepower Calculator (Track) — Free Online Calculator & Formula Guide',
    shortTitle: 'Horsepower',
    description: "Estimate your vehicle's horsepower from quarter-mile ET and trap speed using the Hale formula. Includes drivetrain loss estimation (FWD/RWD/AWD) and power-to-weight ratio.",
    category: 'Automotive',
    categorySlug: 'automotive',
    subCategory: 'Performance & Maintenance',
    seoKeywords: ['horsepower calculator', 'quarter mile horsepower', 'Hale formula', 'ET horsepower estimator', 'dyno alternative', 'drag racing calculator', 'power to weight ratio', 'WHP vs BHP', 'drivetrain loss'],
    schema: 'both',
    mathSolverExpression: 'HP = Weight / (ET/5.825)³ | HP = Weight x (Speed/234)³',
    reviewedBy: 'Automotive expert, ASE certified',
    lastVerified: '2026-01-15',
    relatedIds: ['engine-horsepower-calculator', 'fuel-cost-calculator', 'tire-size-calculator'],
    loader: () => import('../math/horsepower/index'),
  },
  {
    id: 'fuel-cost-calculator',
    title: 'Fuel Cost Calculator — Trip Fuel Expense, MPG & Mileage Estimator',
    shortTitle: 'Fuel Cost Calculator',
    description: 'Calculate trip fuel costs for gas, diesel, EV, and PHEV vehicles. Handles MPG, L/100km, km/L, EV efficiency, and PHEV split-mode driving costs.',
    category: 'Automotive',
    categorySlug: 'automotive',
    subCategory: 'Fuel & Efficiency',
    seoKeywords: ['fuel cost calculator', 'trip cost calculator', 'gas calculator', 'EV cost calculator', 'PHEV fuel cost', 'MPG calculator', 'road trip budget', 'fuel economy calculator', 'CO2 emissions calculator'],
    schema: 'both',
    mathSolverExpression: 'Total Cost = FuelNeeded x FuelPrice | CO2 = Gallons x EmissionsFactor',
    reviewedBy: 'Automotive expert, ASE certified',
    lastVerified: '2026-01-15',
    relatedIds: ['gas-mileage-calculator', 'mpg-calculator', 'trip-fuel-cost-calculator', 'mileage-reimbursement-calculator', 'vehicle-depreciation-calculator'],
    relatedPosts: ['gas-mileage-mpg-guide'],
    loader: () => import('../math/fuel-cost/index'),
  },
  {
    id: 'gas-mileage-calculator',
    title: 'Gas Mileage Calculator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Gas Mileage',
    description: 'Calculate your fuel economy in MPG or L/100km using odometer readings or trip distance. Free online calculator with formula guide and step-by-step results.',
    category: 'Automotive',
    categorySlug: 'automotive',
    subCategory: 'Fuel & Efficiency',
    seoKeywords: ['gas mileage calculator', 'MPG calculator', 'fuel economy calculator', 'L/100km', 'cost per mile', 'annual fuel cost', 'odometer fuel tracker', 'car fuel efficiency'],
    schema: 'both',
    mathSolverExpression: 'MPG = Miles / Gallons | L/100km = (Liters x 100) / km',
    lastVerified: '2026-01-15',
    relatedIds: ['mpg-calculator', 'fuel-cost-calculator', 'trip-fuel-cost-calculator', 'mileage-reimbursement-calculator'],
    relatedPosts: ['gas-mileage-mpg-guide'],
    loader: () => import('../math/gas-mileage/index'),
  },
  {
    id: 'mileage-reimbursement-calculator',
    title: 'Mileage Reimbursement Calculator — Free Online Calculator & Guide',
    shortTitle: 'Mileage Reimbursement',
    description: 'Calculate IRS-standard mileage reimbursement for business, medical, and charitable driving. Includes tax savings estimates and additional expense tracking.',
    category: 'Automotive',
    categorySlug: 'automotive',
    subCategory: 'Fuel & Efficiency',
    seoKeywords: ['mileage reimbursement', 'IRS mileage rate', 'business mileage calculator', 'mileage deduction', 'standard mileage rate', 'tax deductible mileage', 'vehicle expense calculator'],
    schema: 'both',
    mathSolverExpression: 'Reimbursement = Miles x Rate + Additional Expenses',
    lastVerified: '2026-01-15',
    relatedIds: ['fuel-cost-calculator', 'gas-mileage-calculator', 'mpg-calculator', 'trip-fuel-cost-calculator'],
    loader: () => import('../math/mileage-reimbursement/index'),
  },
  {
    id: 'auto-loan-calculator',
    title: 'Auto Loan Calculator — Monthly Payment, Trade-In & Negative Equity',
    shortTitle: 'Auto Loan Calculator',
    description: 'Calculate monthly car payments with trade-in value, negative equity rollover, sales tax, and dealer fees. See total interest and out-the-door price.',
    category: 'Automotive',
    categorySlug: 'automotive',
    subCategory: 'Loans & Leasing',
    relatedIds: ['lease-vs-buy-calculator', 'auto-lease-calculator', 'cash-back-vs-low-interest-calculator', 'vehicle-depreciation-calculator'],
    seoKeywords: ['auto loan calculator', 'car payment calculator', 'car loan calculator', 'trade in calculator', 'negative equity car loan', 'out the door price calculator'],
    schema: 'both',
    mathSolverExpression: 'Payment = P x r(1+r)^n / ((1+r)^n - 1) | Total Interest = Payment x n - Principal',
    lastVerified: '2026-05-17',
    relatedPosts: ['auto-loan-financing-guide'],
    reviewedBy: 'John Carter, Automotive Finance Expert & Former F&I Manager; Shashi, Senior Reviewer',
    loader: () => import('../automotive/auto-loan/index'),
  },
  {
    id: 'auto-lease-calculator',
    title: 'Auto Lease Calculator — Money Factor, Residual Value & True',
    shortTitle: 'Lease Calculator',
    description: 'The dealer transparency tool. Calculate your exact monthly lease payment using MSRP, negotiated cap cost, residual value, and money factor (or APR).',
    category: 'Automotive',
    categorySlug: 'automotive',
    subCategory: 'Car Leasing',
    seoKeywords: ['auto lease calculator', 'car lease payment calculator', 'money factor calculator', 'residual value lease', 'lease vs buy calculator', 'car lease money factor to APR'],
    schema: 'both',
    mathSolverExpression: 'Monthly = (NetCapCost + Residual) x MF | Cap Reduction = Down + Trade | MF = APR / 2400',
    lastVerified: '2026-05-17',
    relatedIds: ['auto-loan-calculator', 'lease-vs-buy-calculator', 'cash-back-vs-low-interest-calculator'],
    relatedPosts: ['auto-loan-financing-guide'],
    reviewedBy: 'Shashi, Senior Reviewer',
    loader: () => import('../automotive/lease-calculator/index'),
  },
  {
    id: 'cash-back-vs-low-interest-calculator',
    title: 'Cash Back vs. Low Interest Auto Loan Calculator — Which Dealer',
    shortTitle: 'Cash Back vs. Low Rate',
    description: 'The ultimate dealership survival tool. Instantly compare a cash rebate (at your bank rate) vs. Free, instant, and accurate.',
    category: 'Automotive',
    categorySlug: 'automotive',
    subCategory: 'Car Buying',
    seoKeywords: ['cash back vs low interest calculator', 'dealer cash rebate vs 0 financing', 'should I take the rebate or low rate', 'cash back vs financing calculator', '0 percent financing calculator', 'auto loan rebate calculator'],
    schema: 'both',
    mathSolverExpression: 'Compare: Rebate + BankInterest vs TotalLowRateInterest | Savings = TotalFinanced x (BankRate - PromoRate)',
    lastVerified: '2026-01-15',
    relatedIds: ['auto-loan-calculator', 'auto-lease-calculator', 'lease-vs-buy-calculator'],
    loader: () => import('../automotive/cash-back-vs-low-interest/index'),
  },
  {
    id: 'lease-vs-buy-calculator',
    title: 'Car Lease vs. Buy Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'Lease vs. Buy',
    description: 'Compare the true total cost of leasing vs. buying a vehicle over the same time period. Accounts for depreciation, equity, and total payments.',
    category: 'Automotive',
    categorySlug: 'automotive',
    subCategory: 'Loans & Leasing',
    seoKeywords: ['lease vs buy calculator', 'should i lease or buy a car', 'car lease calculator', 'lease vs purchase comparison', 'auto lease calculator', 'car lease or buy'],
    schema: 'both',
    mathSolverExpression: 'Lease Total = Monthly x Term + Fees | Buy Total = (Payment x Term) - Residual Equity',
    lastVerified: '2026-05-17',
    relatedIds: ['auto-loan-calculator', 'auto-lease-calculator', 'cash-back-vs-low-interest-calculator', 'vehicle-depreciation-calculator'],
    reviewedBy: 'Shashi, Senior Reviewer',
    relatedPosts: ['auto-loan-financing-guide'],
    loader: () => import('../automotive/lease-vs-buy/index'),
  },
  {
    id: 'mpg-calculator',
    title: 'MPG & Fuel Efficiency Calculator — Free Online Calculator & Guide',
    shortTitle: 'MPG Calculator',
    description: 'Calculate MPG from miles driven and fuel used, estimate trip fuel costs, determine driving range, or convert between MPG and L/100km.',
    category: 'Automotive',
    categorySlug: 'automotive',
    subCategory: 'Fuel & Efficiency',
    seoKeywords: ['mpg calculator', 'fuel efficiency calculator', 'miles per gallon calculator', 'fuel cost calculator', 'gas mileage calculator', 'l/100km to mpg'],
    schema: 'both',
    mathSolverExpression: 'MPG = Miles / Gallons | L/100km = (Liters x 100) / km | Range = Tank x MPG',
    lastVerified: '2026-05-17',
    relatedIds: ['fuel-cost-calculator', 'gas-mileage-calculator', 'trip-fuel-cost-calculator', 'mileage-reimbursement-calculator'],
    reviewedBy: 'Shashi, Senior Reviewer',
    loader: () => import('../automotive/mpg-calculator/index'),
  },
  {
    id: 'trip-fuel-cost-calculator',
    title: 'Trip Fuel Cost Calculator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Trip Fuel Cost',
    description: 'Calculate the total fuel cost for any road trip with unit support for miles/MPG and km/L/100km. Free, instant, and accurate.',
    category: 'Automotive',
    categorySlug: 'automotive',
    subCategory: 'Fuel & Efficiency',
    seoKeywords: ['trip fuel cost calculator', 'road trip cost calculator', 'fuel cost per mile', 'gas cost calculator', 'travel fuel calculator', 'road trip gas calculator', 'carpool fuel split', 'fuel cost estimator', 'trip budget calculator'],
    schema: 'both',
    mathSolverExpression: 'Trip Cost = Distance / MPG x PricePerGallon | PerPerson = Total / Passengers',
    reviewedBy: 'Automotive expert, ASE certified',
    lastVerified: '2026-05-18',
    relatedIds: ['fuel-cost-calculator', 'gas-mileage-calculator', 'mpg-calculator', 'mileage-reimbursement-calculator', 'vehicle-depreciation-calculator'],
    relatedPosts: ['gas-mileage-mpg-guide'],
    loader: () => import('../automotive/trip-fuel-cost/index'),
  },
  {
    id: 'tire-size-calculator',
    title: 'Tire Size Comparison Calculator — Free Online Calculator & Guide',
    shortTitle: 'Tire Size Comparison Calculator',
    description: 'Compare two tire sizes and calculate the diameter difference, speedometer error, and fitment impact of changing tire sizes.',
    category: 'Automotive',
    categorySlug: 'automotive',
    subCategory: 'Performance & Maintenance',
    seoKeywords: ['tire size calculator', 'tire size comparison', 'speedometer error calculator', 'plus sizing calculator', 'tire diameter calculator', 'wheel size calculator', 'tire upsizing', 'winter tire sizing', 'off-road tire calculator'],
    schema: 'both',
    mathSolverExpression: 'Diameter = WheelDiam + 2 x (Width x Ratio / 25.4) | Î”Speed% = (NewDiam / OldDiam - 1) x 100',
    lastVerified: '2026-05-18',
    relatedIds: ['engine-horsepower-calculator', 'horsepower-calculator', 'auto-loan-calculator'],
    loader: () => import('../automotive/tire-size/index'),
  },
  {
    id: 'vehicle-depreciation-calculator',
    title: 'Vehicle Depreciation Calculator — Free Online Calculator & Guide',
    shortTitle: 'Car Depreciation',
    description: 'Calculate how much a vehicle will depreciate over your ownership period. Shows total depreciation, future value, and monthly depreciation cost.',
    category: 'Automotive',
    categorySlug: 'automotive',
    subCategory: 'Performance & Maintenance',
    seoKeywords: ['car depreciation calculator', 'vehicle depreciation calculator', 'how much does a car depreciate', 'car value calculator', 'auto depreciation', 'resale value calculator'],
    schema: 'both',
    mathSolverExpression: 'FV = P x (1 - r)^n | Monthly Dep = (P - FV) / n | Total Loss = P - FV',
    relatedPosts: ['gas-mileage-mpg-guide'],
    lastVerified: '2026-05-17',
    relatedIds: ['fuel-cost-calculator', 'gas-mileage-calculator', 'mpg-calculator', 'lease-vs-buy-calculator', 'auto-loan-calculator'],
    reviewedBy: 'Shashi, Senior Reviewer',
    loader: () => import('../automotive/depreciation/index'),
  },
];
