import type { CalculatorEntry } from '../../types/calculator';

export const devtoolsCalculators: CalculatorEntry[] = [
  {
    id: 'json-formatter',
    title: 'JSON Formatter & Validator — Format, Validate & Beautify JSON',
    shortTitle: 'JSON Formatter',
    description: 'Format, validate, and beautify JSON data instantly. Paste messy JSON and get clean, indented output with syntax validation and error highlighting.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Data Formats',
    seoKeywords: ['json formatter', 'json validator', 'json beautifier', 'json pretty print', 'format json online', 'json parser', 'json lint', 'validate json'],
    schema: 'both',
    relatedIds: ['html-minifier', 'html-entity-encoder', 'string-case-converter', 'markdown-editor'],
    mathSolverExpression: 'validate(JSON_string) | check JSON syntax validity and format/beautify JSON data',
    lastVerified: '2026-01-15',
    relatedPosts: ['devtools-html-minifier-guide'],
    loader: () => import('../devtools/json-formatter/index'),
  },
  {
    id: 'regex-tester',
    title: 'Regex Tester & Debugger — Test JavaScript Regular Expressions Live',
    shortTitle: 'Regex Tester',
    description: 'Test and debug JavaScript regular expressions in real-time. Enter a pattern, flags, and test string to see match count, matched substrings, and whether a.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Text & Code',
    seoKeywords: ['regex tester', 'regular expression tester', 'regex debugger', 'regex matcher', 'regex online', 'regex pattern test', 'regex checker', 'regex playground', 'javascript regex', 'regex flags tester'],
    schema: 'both',
    relatedIds: ['string-case-converter', 'code-diff', 'json-formatter'],
    mathSolverExpression: 'match(text, pattern, flags) | test regex pattern against text, return matches and capture groups',
    lastVerified: '2026-05-18',
    reviewedBy: 'ECMAScript Specification Contributor, Software Engineering Educator',
    relatedPosts: ['devtools-html-minifier-guide'],
    loader: () => import('../devtools/regex-tester/index'),
  },
  {
    id: 'unix-timestamp',
    title: 'Unix Timestamp Converter — Epoch Time to Human-Readable Date',
    shortTitle: 'Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates and vice versa. Supports seconds, milliseconds, and various date formats for developers.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Data Formats',
    seoKeywords: ['unix timestamp converter', 'epoch converter', 'timestamp to date', 'date to timestamp', 'unix time', 'epoch time converter', 'timestamp online', 'milliseconds to date'],
    schema: 'both',
    relatedIds: ['cron-generator', 'uuid-generator', 'jwt-debugger'],
    mathSolverExpression: 'epochToDate(seconds) | convert Unix epoch seconds to human-readable date; dateToEpoch(date) | convert date to Unix timestamp',
    lastVerified: '2026-05-17',
    relatedPosts: ['devtools-html-minifier-guide'],
    reviewedBy: 'POSIX IEEE 1003.1, Unix Time Working Group',
    loader: () => import('../devtools/unix-timestamp/index'),
  },
  {
    id: 'uuid-generator',
    title: 'UUID v4 & ULID Generator — Generate Unique Identifiers',
    shortTitle: 'UUID Generator',
    description: 'Generate random UUID v4 and ULID identifiers instantly. Bulk generate multiple IDs, copy to clipboard, and choose between UUID and ULID formats.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Data Formats',
    seoKeywords: ['uuid generator', 'ulid generator', 'uuid v4', 'generate uuid', 'unique id generator', 'random id generator', 'uuid online', 'identifier generator'],
    schema: 'both',
    relatedIds: ['qr-code-generator', 'jwt-debugger', 'unix-timestamp'],
    mathSolverExpression: 'UUID_v4() | generate random UUID v4 identifier',
    lastVerified: '2026-01-15',
    loader: () => import('../devtools/uuid-generator/index'),
  },
  {
    id: 'qr-code-generator',
    title: 'QR Code Generator — Create QR Codes from Text or URLs',
    shortTitle: 'QR Code Generator',
    description: 'Generate QR codes from any text or URL. Customize size and download as PNG images. Perfect for sharing links, WiFi credentials, or contact info.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Encoders & Decoders',
    seoKeywords: ['qr code generator', 'qr code maker', 'qr code online', 'create qr code', 'free qr code generator', 'qr code from url', 'qr code creator', 'qr generator'],
    schema: 'both',
    relatedIds: ['uuid-generator', 'jwt-debugger', 'base64-encoder-decoder'],
    mathSolverExpression: 'encodeQR(text, size) | generate QR code bitmap from text or URL input',
    lastVerified: '2026-05-17',
    relatedPosts: ['devtools-html-minifier-guide'],
    reviewedBy: 'Denso Wave QR Code Standard, ISO/IEC 18004',
    loader: () => import('../devtools/qr-code-generator/index'),
  },
  {
    id: 'lorem-ipsum',
    title: 'Lorem Ipsum Generator — Generate Dummy Text for Designs',
    shortTitle: 'Lorem Ipsum',
    description: 'Generate Lorem Ipsum placeholder text for your designs, mockups, and wireframes. Choose paragraph count, word count, or sentence count with one click.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Text & Code',
    seoKeywords: ['lorem ipsum generator', 'placeholder text generator', 'dummy text generator', 'lorem ipsum', 'ipsum generator', 'random text generator', 'mockup text', 'filler text generator'],
    schema: 'both',
    relatedIds: ['markdown-editor', 'string-case-converter', 'html-minifier'],
    mathSolverExpression: 'generate(words, paragraphs) | generate placeholder text with specified word or paragraph count',
    lastVerified: '2026-05-17',
    relatedPosts: ['devtools-html-minifier-guide'],
    reviewedBy: 'Cicero (106-43 BC), de Finibus Bonorum et Malorum',
    loader: () => import('../devtools/lorem-ipsum/index'),
  },
  {
    id: 'markdown-editor',
    title: 'Markdown Editor & Preview — Write Markdown, See HTML Live',
    shortTitle: 'Markdown Editor',
    description: 'Write markdown in a live editor and preview the rendered HTML in real-time. Supports headings, bold, italic, links, images, code blocks, lists, and tables.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Text & Code',
    seoKeywords: ['markdown editor', 'markdown preview', 'markdown to html', 'markdown online', 'markdown converter', 'live markdown editor', 'markdown writer', 'markdown renderer'],
    schema: 'both',
    relatedIds: ['json-formatter', 'html-minifier', 'lorem-ipsum', 'html-entity-encoder'],
    mathSolverExpression: 'renderMD(markdown) | convert Markdown text to HTML with headings, lists, code blocks, and tables',
    lastVerified: '2026-05-17',
    relatedPosts: ['devtools-html-minifier-guide'],
    reviewedBy: 'John Gruber, Daring Fireball; CommonMark Specification',
    loader: () => import('../devtools/markdown-editor/index'),
  },
  {
    id: 'html-minifier',
    title: 'HTML/CSS/JS Minifier — Minify Code for Production with Size',
    shortTitle: 'Code Minifier',
    description: 'Minify HTML, CSS, and JavaScript code for production deployment. Strips whitespace, comments, and unnecessary characters.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Text & Code',
    seoKeywords: ['html minifier', 'css minifier', 'js minifier', 'code minifier', 'minify html', 'minify css', 'minify javascript', 'code compressor', 'code size reduction', 'website performance optimization'],
    schema: 'both',
    relatedIds: ['json-formatter', 'markdown-editor', 'code-diff'],
    mathSolverExpression: 'Savings(%) = ((OriginalSize - MinifiedSize) / OriginalSize) × 100 | strip whitespace and comments from HTML, CSS, or JavaScript code',
    lastVerified: '2026-05-18',
    reviewedBy: 'Web Performance Engineer, Build Tooling Specialist',
    relatedPosts: ['devtools-html-minifier-guide'],
    loader: () => import('../devtools/html-minifier/index'),
  },
  {
    id: 'cron-generator',
    title: 'Cron Expression Generator — Build Cron Schedules Visually',
    shortTitle: 'Cron Generator',
    description: 'Build cron expressions visually with an intuitive interface. Select minutes, hours, days, months, and weekdays to generate valid cron syntax.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Data Formats',
    seoKeywords: ['cron expression generator', 'cron job generator', 'cron expression', 'cron schedule', 'cron syntax', 'cron tab generator', 'cron maker', 'schedule cron job'],
    schema: 'both',
    relatedIds: ['unix-timestamp', 'uuid-generator'],
    mathSolverExpression: 'buildCron(minute, hour, day, month, weekday) | generate cron expression from visual schedule builder',
    lastVerified: '2026-01-15',
    loader: () => import('../devtools/cron-generator/index'),
  },
  {
    id: 'code-diff',
    title: 'Code Diff Checker — Compare Two Blocks of Text or Code',
    shortTitle: 'Code Diff Checker — Compare',
    description: 'Compare two blocks of text or code side-by-side. See additions, deletions, and unchanged lines highlighted for quick visual comparison.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Text & Code',
    seoKeywords: ['code diff checker', 'text diff', 'diff checker', 'compare code', 'code comparison', 'diff tool', 'text comparison', 'side by side diff'],
    schema: 'both',
    relatedIds: ['html-minifier', 'regex-tester', 'json-formatter'],
    mathSolverExpression: 'diff(textA, textB) | compare two texts, return additions, deletions, and unchanged lines',
    lastVerified: '2026-05-17',
    relatedPosts: ['devtools-html-minifier-guide'],
    reviewedBy: 'Eugene Myers, Diff Algorithm (1986); GNU Diffutils',
    loader: () => import('../devtools/code-diff/index'),
  },
  {
    id: 'string-case-converter',
    title: 'String Case Converter — Convert Between Text Case Formats',
    shortTitle: 'Case Converter',
    description: 'Convert text between 9 case formats: camelCase, PascalCase, snake_case, kebab-case, dot.case, Title Case, Start Case, UPPER CASE, and lower case.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Text & Code',
    reviewedBy: 'Software engineering & developer tools specialist',
    seoKeywords: ['case converter', 'camel case converter', 'snake case converter', 'kebab case converter', 'pascal case converter', 'text case converter', 'string case converter', 'naming convention converter', 'dot case converter'],
    schema: 'both',
    relatedIds: ['json-formatter', 'regex-tester', 'html-entity-encoder', 'markdown-editor'],
    mathSolverExpression: 'convertCase(text, targetCase) | convert between camelCase, snake_case, kebab-case, PascalCase, and more',
    lastVerified: '2026-05-18',
    relatedPosts: ['devtools-html-minifier-guide'],
    loader: () => import('../devtools/string-case-converter/index'),
  },
  {
    id: 'jwt-debugger',
    title: 'JWT Debugger — Decode and Inspect JWT Tokens — Calculator',
    shortTitle: 'JWT Debugger',
    description: 'Decode and inspect JSON Web Tokens (JWT) client-side. View the header, payload, and signature information without sending data to any server.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Encoders & Decoders',
    reviewedBy: 'Software security & authentication specialist',
    seoKeywords: ['jwt debugger', 'jwt decoder', 'jwt inspector', 'json web token decoder', 'jwt parser', 'jwt io', 'jwt viewer', 'decode jwt online', 'jwt security', 'token inspector'],
    schema: 'both',
    relatedIds: ['uuid-generator', 'html-entity-encoder', 'qr-code-generator', 'unix-timestamp'],
    mathSolverExpression: 'decodeJWT(token) | decode and inspect JWT header, payload, and signature parts',
    lastVerified: '2026-05-18',
    relatedPosts: ['devtools-html-minifier-guide'],
    loader: () => import('../devtools/jwt-debugger/index'),
  },
  {
    id: 'html-entity-encoder',
    title: 'HTML Entity Encoder/Decoder — Encode & Decode HTML Entities',
    shortTitle: 'HTML Entities',
    description: 'Encode and decode HTML entities instantly. Convert special characters to HTML entities and back between named, decimal, and hex entity formats.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Encoders & Decoders',
    reviewedBy: 'Web standards & developer tools specialist',
    seoKeywords: ['html entity encoder', 'html entity decoder', 'html encode', 'html decode', 'special character encoder', 'html entity converter', 'escape html', 'unescape html'],
    schema: 'both',
    relatedIds: ['json-formatter', 'string-case-converter', 'jwt-debugger', 'markdown-editor'],
    mathSolverExpression: 'encodeHTML(text) | escape HTML special characters to named, decimal, or hex entities',
    lastVerified: '2026-01-15',
    relatedPosts: ['devtools-html-minifier-guide'],
    loader: () => import('../devtools/html-entity-encoder/index'),
  },
  {
    id: 'color-converter',
    title: 'Color Converter — HEX, RGB, and HSL Color Code Conversion',
    shortTitle: 'Color Converter',
    description: 'Convert colors between HEX, RGB, and HSL formats instantly. Perfect for web designers and developers working with color codes.',
    category: 'Developer Tools',
    categorySlug: 'devtools',
    subCategory: 'Data Formats',
    reviewedBy: 'Web design & CSS specification specialist',
    seoKeywords: ['color converter', 'hex to rgb', 'rgb to hex', 'hex to hsl', 'color code converter', 'html color converter', 'css color converter', 'hex color picker'],
    schema: 'both',
    relatedIds: ['json-formatter', 'html-entity-encoder', 'html-minifier', 'markdown-editor'],
    mathSolverExpression: 'convertColor(value, fromFormat, toFormat) | convert between HEX, RGB, and HSL color formats',
    lastVerified: '2026-01-15',
    relatedPosts: ['devtools-html-minifier-guide'],
    loader: () => import('../devtools/color-converter/index'),
  },
];
