import type { CalculatorEntry } from '../../types/calculator';

export const diyCalculators: CalculatorEntry[] = [
  {
    id: 'concrete-calculator',
    title: 'Concrete Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Concrete Calculator',
    description: 'Calculate the exact volume of concrete needed for slabs, holes, columns, and stairs. Outputs cubic yards plus the number of 60-lb and 80-lb bags required.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'Concrete & Masonry',
    seoKeywords: ['concrete calculator', 'concrete volume', 'cubic yards concrete', 'concrete bag calculator', 'slab concrete', 'concrete footing', '80lb bags concrete', '60lb bags concrete', 'DIY concrete'],
    schema: 'both',
    mathSolverExpression: 'Volume = Area x Depth | Cubic Yards = Cubic Feet / 27',
    lastVerified: '2026-01-15',
    relatedIds: ['concrete-slab-calculator', 'gravel-calculator', 'lumber-board-foot-calculator'],
    relatedPosts: ['concrete-calculator-guide', 'square-footage-calculator-guide', 'tile-flooring-calculator-guide'],
    loader: () => import('../diy/concrete/index'),
  },
  {
    id: 'btu-calculator',
    title: 'BTU Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'BTU Calculator',
    description: 'Calculate the required BTUs for heating or cooling any room. Factors in climate zone, sun exposure, insulation, ceiling height, room type, and occupancy.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'General',
    seoKeywords: ['BTU calculator', 'AC size calculator', 'BTU per square foot', 'room cooling calculator', 'furnace sizing', 'HVAC calculator', 'air conditioner size', 'heating BTU calculator'],
    schema: 'both',
    mathSolverExpression: 'BTU = Area x ClimateFactor x CeilingFactor x SunFactor x Insulation x RoomFactor + People x 600',
    lastVerified: '2026-01-15',
    relatedIds: ['roofing-calculator', 'square-footage-calculator'],
    relatedPosts: ['btu-calculator-guide', 'electricity-cost-calculator-guide'],
    loader: () => import('../diy/btu/index'),
  },
  {
    id: 'square-footage-calculator',
    title: 'Square Footage Calculator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Sq Footage',
    description: 'Calculate square footage for rectangles, circles, and L-shaped rooms. Supports feet and meters, includes wastage for materials, and estimates total cost.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'General',
    seoKeywords: ['square footage calculator', 'sq ft calculator', 'area calculator', 'room size calculator', 'flooring calculator', 'square meter calculator', 'L-shaped room area', 'material wastage'],
    schema: 'both',
    mathSolverExpression: 'Rectangle: A = L x W | Circle: A = πr² | L-Shape: A = A1 + A2',
    lastVerified: '2026-01-15',
    relatedIds: ['tile-calculator', 'tile-flooring-calculator', 'paint-coverage-calculator', 'concrete-calculator'],
    relatedPosts: ['btu-calculator-guide', 'concrete-calculator-guide', 'paint-coverage-calculator-guide', 'square-footage-calculator-guide', 'tile-flooring-calculator-guide'],
    loader: () => import('../diy/square-footage/index'),
  },
  {
    id: 'tile-calculator',
    title: 'Tile Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Tile Calculator',
    description: 'Calculate tiles needed for any room with different layout patterns. Supports grid, brick, diagonal, and herringbone layouts with automatic waste factors.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'Materials',
    seoKeywords: ['tile calculator', 'floor tile calculator', 'tile layout', 'herringbone pattern', 'tile waste factor', 'bathroom tile', 'kitchen backsplash', 'square foot tile'],
    schema: 'both',
    mathSolverExpression: 'TotalTiles = ceil(RoomArea / TileArea x (1+Waste%))',
    lastVerified: '2026-01-15',
    relatedIds: ['tile-flooring-calculator', 'square-footage-calculator', 'concrete-calculator'],
    relatedPosts: ['paint-coverage-calculator-guide', 'square-footage-calculator-guide', 'tile-flooring-calculator-guide'],
    loader: () => import('../math/tile/index'),
  },
  {
    id: 'roofing-calculator',
    title: 'Roofing Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Roofing Calculator',
    description: 'Estimate roofing materials for gable and hip roofs. Calculates squares, shingle bundles, felt rolls, and nails. Includes pitch multipliers and waste factors.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'Materials',
    seoKeywords: ['roofing calculator', 'roof squares', 'shingle calculator', 'roof pitch multiplier', 'hip roof calculator', 'gable roof calculator', 'roofing materials', 'DIY roofing'],
    schema: 'both',
    mathSolverExpression: 'RoofArea = Footprint x PitchMultiplier x (1+Waste) | 1 square = 100 sq ft',
    lastVerified: '2026-01-15',
    relatedIds: ['btu-calculator', 'stair-calculator', 'square-footage-calculator'],
    loader: () => import('../math/roofing/index'),
  },
  {
    id: 'stair-calculator',
    title: 'Stair Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Stair Calculator',
    description: 'Design safe stairs with IBC-compliant rise/run calculations. Computes number of steps, riser height, tread depth, stringer length and angle.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'Materials',
    seoKeywords: ['stair calculator', 'stair stringer calculator', 'IBC stair code', 'rise and run calculator', 'stair building', 'deck stairs', 'stringer length', 'riser height code', 'tread depth code'],
    schema: 'both',
    mathSolverExpression: 'Risers = âŒˆTotalRise / RiserHeightâŒ‰ | Stringer = âˆš(Rise² + Run²)',
    relatedPosts: ['btu-calculator-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['roofing-calculator', 'concrete-calculator', 'lumber-board-foot-calculator'],
    loader: () => import('../math/stair/index'),
  },
  {
    id: 'mulch-calculator',
    title: 'Mulch Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Mulch Calculator',
    description: 'Calculate mulch volume for rectangular and circular garden beds. Compare costs between bagged (2 cu ft) and bulk delivery to find the most economical option.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'Materials',
    seoKeywords: ['mulch calculator', 'garden mulch', 'cubic yards mulch', 'bagged vs bulk mulch', 'landscaping calculator', 'mulch depth', 'garden bed calculator'],
    schema: 'both',
    mathSolverExpression: 'CubicYards = (L x W x DepthIn) / 324 | Circle: A = π(D/2)²',
    lastVerified: '2026-01-15',
    relatedIds: ['mulch-topsoil-calculator', 'gravel-calculator'],
    loader: () => import('../math/mulch/index'),
  },
  {
    id: 'gravel-calculator',
    title: 'Gravel Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Gravel Calculator',
    description: 'Calculate gravel volume in cubic yards and tons for landscaping projects. Choose from pea gravel, crushed limestone, river rock, and decomposed granite.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'Materials',
    seoKeywords: ['gravel calculator', 'cubic yards gravel', 'gravel tons', 'landscaping gravel', 'pea gravel calculator', 'crushed stone', 'gravel coverage', 'pathway materials'],
    schema: 'both',
    mathSolverExpression: 'CubicYards = (L x W x DepthIn) / 324 | Tons = CubicYards x Density / 2000',
    lastVerified: '2026-01-15',
    relatedIds: ['mulch-calculator', 'concrete-calculator', 'concrete-slab-calculator', 'mulch-topsoil-calculator'],
    loader: () => import('../math/gravel/index'),
  },
  {
    id: 'paint-coverage-calculator',
    title: 'Paint Coverage Calculator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Paint Calculator',
    description: 'Calculate how many gallons of paint you need for any room. Enter dimensions, number of doors and windows, and coats to get an accurate paint quantity.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'Paint & Coatings',
    seoKeywords: ['paint calculator', 'how much paint do i need', 'paint coverage calculator', 'gallons of paint calculator', 'room paint calculator', 'interior paint estimator'],
    schema: 'both',
    relatedIds: ['drywall-calculator', 'square-footage-calculator', 'tile-flooring-calculator'],
    mathSolverExpression: 'gallons = total_area / coverage_per_gallon | paint needed in gallons for given wall area',
    lastVerified: '2026-05-17',
    relatedPosts: ['paint-coverage-calculator-guide', 'square-footage-calculator-guide', 'home-renovation-budgeting-estimate-costs'],
    loader: () => import('../diy/paint-coverage/index'),
  },
  {
    id: 'tile-flooring-calculator',
    title: 'Tile & Flooring Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'Tile Calculator',
    description: 'Calculate how many tiles you need for any floor or wall. Includes waste percentage for cuts, multiple tile sizes, and optional material cost estimate.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'Materials',
    seoKeywords: ['tile calculator', 'flooring calculator', 'how many tiles do i need', 'square footage calculator', 'tile square footage', 'floor tile calculator'],
    schema: 'both',
    relatedIds: ['tile-calculator', 'square-footage-calculator', 'paint-coverage-calculator'],
    mathSolverExpression: 'tiles_needed = room_area / tile_area x (1 + waste%) | flooring material quantity in tiles',
    lastVerified: '2026-05-17',
    relatedPosts: ['tile-flooring-calculator-guide', 'square-footage-calculator-guide', 'home-renovation-budgeting-estimate-costs'],
    loader: () => import('../diy/tile-flooring/index'),
  },
  {
    id: 'concrete-slab-calculator',
    title: 'Concrete Slab Calculator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Concrete Calculator',
    description: 'Calculate cubic yards of concrete needed for any slab, driveway, or foundation. Shows cubic yards for ready-mix ordering and equivalent bag counts.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'Concrete & Masonry',
    seoKeywords: ['concrete calculator', 'concrete slab calculator', 'cubic yards calculator', 'how much concrete do i need', 'concrete bags calculator', 'driveway concrete calculator'],
    schema: 'both',
    relatedIds: ['concrete-calculator', 'gravel-calculator', 'lumber-board-foot-calculator'],
    mathSolverExpression: 'cubic_yards = (length_ft x width_ft x depth_in) / 324 | concrete volume in cubic yards',
    lastVerified: '2026-05-17',
    relatedPosts: ['concrete-calculator-guide', 'square-footage-calculator-guide', 'construction-cost-estimator-budget'],
    loader: () => import('../diy/concrete-slab/index'),
  },
  {
    id: 'mulch-topsoil-calculator',
    title: 'Mulch & Topsoil Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'Mulch Calculator',
    description: 'Calculate cubic yards of mulch, topsoil, compost, gravel, or sand needed for any landscaping project. Shows bulk yards and equivalent bagged quantities.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'Materials',
    seoKeywords: ['mulch calculator', 'topsoil calculator', 'cubic yards of mulch', 'how much mulch do i need', 'landscaping material calculator', 'gravel calculator'],
    schema: 'both',
    relatedIds: ['mulch-calculator', 'gravel-calculator'],
    mathSolverExpression: 'cubic_yards = (length_ft x width_ft x depth_in) / 324 | material volume in cubic yards',
    lastVerified: '2026-05-17',
    relatedPosts: ['square-footage-calculator-guide'],
    loader: () => import('../diy/mulch-topsoil/index'),
  },
  {
    id: 'drywall-calculator',
    title: 'Drywall Sheet Estimator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Drywall Calculator',
    description: 'Calculate how many sheets of drywall you need for walls and ceiling. Includes screw count, joint compound, tape estimates, and accounts for doors.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'Materials',
    seoKeywords: ['drywall calculator', 'sheetrock calculator', 'how many sheets of drywall', 'drywall estimator', 'drywall square footage calculator', 'gypsum board calculator', 'drywall screw calculator', 'joint compound calculator', 'drywall finishing materials', 'drywall tape estimator'],
    schema: 'both',
    relatedIds: ['paint-coverage-calculator', 'square-footage-calculator', 'lumber-board-foot-calculator'],
    relatedPosts: ['paint-coverage-calculator-guide', 'square-footage-calculator-guide'],
    mathSolverExpression: 'sheets = ceil((wall_area + ceiling_area - openings) * 1.10 / sheet_area) | number of drywall sheets with 10% waste',
    lastVerified: '2026-05-17',
    loader: () => import('../diy/drywall/index'),
  },
  {
    id: 'lumber-board-foot-calculator',
    title: 'Lumber Board Foot Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'Board Foot Calculator',
    description: 'Calculate board feet of lumber for any project. Shows nominal and actual board foot volumes with dimensional conversions.',
    category: 'Home DIY',
    categorySlug: 'diy',
    subCategory: 'Materials',
    seoKeywords: ['board foot calculator', 'lumber calculator', 'board feet calculator', 'how many board feet', 'lumber cost calculator', 'wood calculator', 'dimensional lumber calculator', 'nominal vs actual lumber', 'framing lumber calculator', 'hardwood board foot calculator'],
    schema: 'both',
    relatedIds: ['concrete-calculator', 'concrete-slab-calculator', 'stair-calculator', 'drywall-calculator'],
    relatedPosts: ['concrete-calculator-guide'],
    mathSolverExpression: 'bf = (thickness_in × width_in × length_ft) / 12 | board feet of lumber (nominal and actual)',
    lastVerified: '2026-05-17',
    loader: () => import('../diy/lumber/index'),
  },
];
