import type { CalculatorEntry } from '../../types/calculator';

export const ecommerceCalculators: CalculatorEntry[] = [
  {
    id: 'profit-margin-calculator',
    title: 'Profit Margin & Markup Calculator — Free Online Calculator & Guide',
    shortTitle: 'Profit Margin',
    description: 'Calculate gross profit margin, markup percentage, and selling price. Converts between margin and markup with full profit breakdown.',
    category: 'E-Commerce',
    categorySlug: 'ecommerce',
    subCategory: 'Pricing & Margin',
    seoKeywords: ['profit margin calculator', 'markup calculator', 'gross margin calculator', 'profit calculator', 'selling price calculator', 'margin vs markup', 'gross profit calculator', 'margin vs markup calculator'],
    schema: 'both',
    relatedIds: ['margin-calculator', 'break-even-calculator', 'cogs-calculator', 'roas-calculator'],
    mathSolverExpression: 'margin_% = (revenue - cost) / revenue × 100 | markup_% = (price - cost) / cost × 100 | gross profit margin and markup percentage',
    lastVerified: '2026-05-17',
    relatedPosts: ['profit-margin-business-guide'],
    loader: () => import('../ecommerce/profit-margin/index'),
  },
  {
    id: 'cogs-calculator',
    title: 'Cost of Goods Sold (COGS) Calculator — Free Online Calculator & Guide',
    shortTitle: 'COGS Calculator',
    description: 'Calculate your Cost of Goods Sold using the inventory accounting formula. Includes gross profit margin and COGS as a percentage of revenue.',
    category: 'E-Commerce',
    categorySlug: 'ecommerce',
    subCategory: 'Pricing & Margin',
    seoKeywords: ['cogs calculator', 'cost of goods sold calculator', 'inventory cost calculator', 'gross profit calculator', 'cogs formula', 'cost of sales calculator'],
    schema: 'both',
    relatedIds: ['profit-margin-calculator', 'margin-calculator', 'break-even-calculator'],
    mathSolverExpression: 'COGS = beginning_inventory + purchases - ending_inventory | cost of goods sold from inventory accounting',
    lastVerified: '2026-01-15',
    loader: () => import('../ecommerce/cogs/index'),
  },
  {
    id: 'break-even-calculator',
    title: 'Break-Even Point Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'Break-Even Point',
    description: 'Calculate your break-even point in units and revenue. Enter fixed costs, selling price, and variable cost per unit to find when your business becomes.',
    category: 'E-Commerce',
    categorySlug: 'ecommerce',
    subCategory: 'Operations',
    seoKeywords: ['break even calculator', 'break even point calculator', 'break even analysis', 'contribution margin calculator', 'break even formula', 'break even units', 'break even revenue'],
    schema: 'both',
    relatedIds: ['profit-margin-calculator', 'margin-calculator', 'cogs-calculator', 'roas-calculator', 'cac-calculator'],
    mathSolverExpression: 'BEP_units = fixed_costs / (price - variable_cost_per_unit) | break-even point in units and revenue',
    lastVerified: '2026-05-17',
    relatedPosts: ['profit-margin-business-guide'],
    loader: () => import('../ecommerce/break-even/index'),
  },
  {
    id: 'amazon-fba-calculator',
    title: 'Amazon FBA Fee & Margin Calculator — Free Online Calculator & Guide',
    shortTitle: 'Amazon FBA',
    description: 'Calculate Amazon FBA fees, net profit, ROI, and margin for any product. Includes referral fees (8-20%), weight-based fulfillment fees, monthly storage.',
    category: 'E-Commerce',
    categorySlug: 'ecommerce',
    subCategory: 'Operations',
    seoKeywords: ['amazon fba calculator', 'amazon seller fees calculator', 'fba fee calculator', 'amazon profit calculator', 'amazon margin calculator', 'amazon referral fee', 'fba fulfillment cost', 'amazon product profitability'],
    schema: 'both',
    relatedIds: ['etsy-fees-calculator', 'payment-fees-calculator', 'saas-ltv-cac-calculator'],
    mathSolverExpression: 'profit = price - referral_fee - fulfillment_fee - storage_fee | Amazon FBA net profit and ROI',
    lastVerified: '2026-05-18',
    relatedPosts: ['profit-margin-business-guide'],
    loader: () => import('../ecommerce/amazon-fba/index'),
  },
  {
    id: 'roas-calculator',
    title: 'Return on Ad Spend (ROAS) Calculator — Free Online Calculator & Guide',
    shortTitle: 'ROAS Calculator',
    description: 'Calculate your ROAS and break-even ROAS based on gross margin. Determine if your advertising campaigns are truly profitable.',
    category: 'E-Commerce',
    categorySlug: 'ecommerce',
    subCategory: 'Marketing & Ads',
    seoKeywords: ['roas calculator', 'return on ad spend', 'advertising roas', 'google ads roas', 'facebook ads roas', 'break even roas', 'roi vs roas', 'ad profitability'],
    schema: 'both',
    relatedIds: ['cac-calculator', 'cpm-cpc-calculator', 'profit-margin-calculator', 'break-even-calculator'],
    mathSolverExpression: 'ROAS = revenue / ad_spend | break_even_ROAS = 1 / gross_margin_pct | return on ad spend',
    lastVerified: '2026-05-17',
    relatedPosts: ['profit-margin-business-guide'],
    loader: () => import('../ecommerce/roas/index'),
  },
  {
    id: 'cac-calculator',
    title: 'Customer Acquisition Cost (CAC) Calculator — Free Online Calculator',
    shortTitle: 'CAC Calculator',
    description: 'Calculate customer acquisition cost and LTV:CAC ratio. Evaluate the efficiency of your marketing spend and payback period.',
    category: 'E-Commerce',
    categorySlug: 'ecommerce',
    subCategory: 'Marketing & Ads',
    seoKeywords: ['cac calculator', 'customer acquisition cost', 'ltv cac ratio', 'marketing cost per customer', 'cost per acquisition calculator', 'cac payback period', 'ltv calculator', 'unit economics'],
    schema: 'both',
    relatedIds: ['roas-calculator', 'saas-ltv-cac-calculator', 'cpm-cpc-calculator', 'break-even-calculator'],
    mathSolverExpression: 'CAC = total_marketing_cost / new_customers | LTV:CAC = LTV / CAC | customer acquisition cost and unit economics',
    lastVerified: '2026-05-17',
    relatedPosts: ['profit-margin-business-guide'],
    loader: () => import('../ecommerce/cac/index'),
  },
  {
    id: 'margin-calculator',
    title: 'Margin Calculator — Gross Margin, Markup, Cost & Price (Solve Any',
    shortTitle: 'Margin Calculator',
    description: 'Solve for Gross Margin %, Markup %, Cost, or Revenue — choose what you know and calculate what you need. Free, instant, and accurate.',
    category: 'E-Commerce',
    categorySlug: 'ecommerce',
    subCategory: 'Pricing & Profitability',
    seoKeywords: ['margin calculator', 'gross margin calculator', 'markup calculator', 'margin vs markup', 'profit margin calculator', 'selling price calculator', 'cost price calculator', 'solve for margin'],
    schema: 'both',
    relatedIds: ['profit-margin-calculator', 'break-even-calculator', 'cogs-calculator', 'roas-calculator'],
    mathSolverExpression: 'margin_% = (selling_price - cost) / selling_price × 100 | gross margin percentage and markup',
    lastVerified: '2026-05-17',
    relatedPosts: ['profit-margin-business-guide'],
    loader: () => import('../ecommerce/margin-calculator/index'),
  },
  {
    id: 'saas-ltv-cac-calculator',
    title: 'SaaS LTV:CAC Ratio Calculator — Unit Economics & Payback Period',
    shortTitle: 'SaaS LTV:CAC',
    description: 'Calculate customer lifetime value (LTV), customer acquisition cost (CAC), LTV:CAC ratio, payback period, and the SaaS Magic Number.',
    category: 'E-Commerce',
    categorySlug: 'ecommerce',
    subCategory: 'Operations',
    seoKeywords: ['ltv cac calculator', 'saas metrics calculator', 'customer lifetime value calculator', 'customer acquisition cost calculator', 'ltv cac ratio', 'saas payback period', 'saas magic number', 'unit economics calculator', 'churn rate calculator', 'saas golden ratio 3 to 1'],
    schema: 'both',
    relatedIds: ['cac-calculator', 'break-even-calculator', 'amazon-fba-calculator'],
    mathSolverExpression: 'LTV = ARPU / churn_rate | LTV:CAC = LTV / CAC | customer lifetime value and LTV:CAC ratio',
    lastVerified: '2026-01-15',
    relatedPosts: ['profit-margin-business-guide'],
    loader: () => import('../ecommerce/saas-ltv-cac/index'),
  },
  {
    id: 'payment-fees-calculator',
    title: 'Stripe & PayPal Fee Calculator — Payment Processor Fee Comparison',
    shortTitle: 'Payment Fees',
    description: 'Compare Stripe and PayPal transaction fees side by side. Enter your transaction amount to see the exact fee, net amount, effective rate, and monthly.',
    category: 'E-Commerce',
    categorySlug: 'ecommerce',
    subCategory: 'Operations',
    seoKeywords: ['stripe fee calculator', 'paypal fee calculator', 'payment processor fees', 'stripe vs paypal', 'transaction fee calculator', 'online payment fees', 'merchant fee calculator'],
    schema: 'both',
    relatedIds: ['etsy-fees-calculator', 'amazon-fba-calculator', 'youtube-revenue-calculator'],
    mathSolverExpression: 'Fee = Amount x Rate + FixedFee | Net = Amount - Fee | EffectiveRate = Fee / Amount',
    lastVerified: '2026-05-17',
    relatedPosts: ['profit-margin-business-guide', 'amazon-fba-fees-explained-profit'],
    loader: () => import('../ecommerce/payment-fees/index'),
  },
  {
    id: 'youtube-revenue-calculator',
    title: 'YouTube / AdSense Revenue Calculator -- CPM, Views & RPM Estimator',
    shortTitle: 'YouTube Revenue',
    description: 'Estimate YouTube AdSense revenue from views, CPM, and RPM. Supports 7 niche CPM presets (gaming to finance), mid-roll ad modeling, engagement tracking.',
    category: 'E-Commerce',
    categorySlug: 'ecommerce',
    subCategory: 'Creator Economy',
    seoKeywords: ['youtube revenue calculator', 'adsense calculator', 'youtube money calculator', 'cpm calculator', 'rpm calculator', 'youtube earnings estimator', 'how much does youtube pay', 'views to money calculator', 'youtube niche cpm', 'creator revenue calculator'],
    schema: 'both',
    relatedIds: ['engagement-rate-calculator', 'cpm-cpc-calculator', 'etsy-fees-calculator', 'payment-fees-calculator'],
    mathSolverExpression: 'Revenue = (Views / 1000) x CPM | NetPayout = Revenue x (1 - 0.45) | RPM = Revenue / Views x 1000',
    lastVerified: '2026-05-18',
    loader: () => import('../ecommerce/youtube-revenue/index'),
  },
  {
    id: 'etsy-fees-calculator',
    title: 'Etsy Fee Calculator — Listing, Transaction, Payment & Offsite Ads',
    shortTitle: 'Etsy Fee Calculator — Listing,',
    description: 'Calculate all Etsy seller fees for any item: listing fee ($0.20), transaction fee (6.5%), payment processing (3% + $0.25), and optional offsite ads fee.',
    category: 'E-Commerce',
    categorySlug: 'ecommerce',
    subCategory: 'Creator Economy',
    seoKeywords: ['etsy fee calculator', 'etsy seller fees', 'etsy transaction fee', 'etsy listing fee', 'etsy payment processing', 'etsy offsite ads fee', 'etsy profit calculator', 'how much does etsy take'],
    schema: 'both',
    relatedIds: ['amazon-fba-calculator', 'payment-fees-calculator', 'youtube-revenue-calculator', 'engagement-rate-calculator'],
    mathSolverExpression: 'TotalFees = Listing + (Price x TransactionRate) + (Price x PaymentRate + Fixed) + OffsiteAdsFee | Net = Price - TotalFees',
    relatedPosts: ['profit-margin-business-guide'],
    lastVerified: '2026-01-15',
    loader: () => import('../ecommerce/etsy-fees/index'),
  },
  {
    id: 'cpm-cpc-calculator',
    title: 'CPM & CPC Calculator — Reverse Budget Mode with Industry Benchmarks',
    shortTitle: 'CPM & CPC Calculator —',
    description: 'Calculate CPM (cost per mille) and CPC (cost per click) from ad spend, impressions, and clicks. Free, instant, and accurate.',
    category: 'E-Commerce',
    categorySlug: 'ecommerce',
    subCategory: 'Creator Economy',
    seoKeywords: ['cpm calculator', 'cpc calculator', 'cost per mille calculator', 'cost per click calculator', 'advertising cpm benchmark', 'google ads cost calculator', 'social media ad calculator', 'ctr calculator', 'ad budget calculator', 'facebook ads cpm'],
    schema: 'both',
    relatedIds: ['roas-calculator', 'cac-calculator', 'engagement-rate-calculator', 'youtube-revenue-calculator'],
    mathSolverExpression: 'CPM = AdSpend / Impressions x 1000 | CPC = AdSpend / Clicks | CTR = Clicks / Impressions x 100',
    lastVerified: '2026-01-15',
    loader: () => import('../ecommerce/cpm-cpc/index'),
  },
  {
    id: 'engagement-rate-calculator',
    title: 'TikTok & Instagram Engagement Rate Calculator + Influencer Tier',
    shortTitle: 'Engagement Rate',
    description: 'Calculate engagement rate for Instagram, TikTok, and X with platform-specific formulas. Includes influencer tier classification and benchmarks.',
    category: 'E-Commerce',
    categorySlug: 'ecommerce',
    subCategory: 'Creator Economy',
    seoKeywords: ['engagement rate calculator', 'instagram engagement calculator', 'tiktok engagement rate', 'influencer engagement calculator', 'social media engagement benchmark', 'er calculator instagram', 'tiktok analytics tool', 'influencer marketing calculator'],
    schema: 'both',
    relatedIds: ['cpm-cpc-calculator', 'youtube-revenue-calculator', 'etsy-fees-calculator', 'cac-calculator'],
    mathSolverExpression: 'ER = TotalEngagements / Followers x 100 | Instagram ER = (Likes + Comments) / Followers x 100',
    lastVerified: '2026-01-15',
    relatedPosts: ['profit-margin-business-guide', 'amazon-fba-fees-explained-profit'],
    loader: () => import('../ecommerce/engagement-rate/index'),
  },
];
