import type { CalculatorEntry } from '../../types/calculator';

export const engineeringCalculators: CalculatorEntry[] = [
  {
    id: 'resistor-calculator',
    title: 'Resistor Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Resistor Calculator',
    description: 'Decode 4/5/6-band resistor color codes to ohms or reverse-calculate the color bands from any resistance value. Free, instant, and accurate.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'Electrical',
    relatedIds: ['ohms-law-calculator', 'electricity-cost-calculator', 'voltage-drop-calculator'],
    seoKeywords: ['resistor calculator', 'resistor color code', 'ohm calculator', '4 band resistor', '5 band resistor', '6 band resistor', 'color code decoder', 'E12 series', 'E24 series', 'electronics calculator'],
    schema: 'both',
    mathSolverExpression: 'R = (Digit1 x 10 + Digit2) x Multiplier | ±Tolerance%',
    lastVerified: '2026-05-02',
    relatedPosts: ['resistor-color-code-calculator-guide'],
    loader: () => import('../math/resistor/index'),
  },
  {
    id: 'electricity-cost-calculator',
    title: 'Electricity Cost Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'Electricity Cost',
    description: 'Calculate the energy cost of any electrical appliance. Pick from 20 common appliance presets or enter custom wattage, usage hours, and electricity rate.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'Electrical',
    relatedIds: ['ohms-law-calculator', 'resistor-calculator', 'voltage-drop-calculator'],
    seoKeywords: ['electricity cost calculator', 'appliance energy calculator', 'kWh calculator', 'power cost calculator', 'energy bill calculator', 'appliance wattage', 'electricity rate calculator'],
    schema: 'both',
    mathSolverExpression: 'Cost = (InTokens × InPrice + OutTokens × OutPrice) × Requests × DAU | LLM API cost estimation with cached pricing',
    lastVerified: '2026-01-15',
    relatedPosts: ['btu-calculator-guide', 'electricity-cost-calculator-guide'],
    loader: () => import('../math/electricity-cost/index'),
  },
  {
    id: 'ip-subnet-calculator',
    title: 'IP Subnet Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'IP Subnet Calculator',
    description: 'Calculate network address, broadcast address, usable host range, and total hosts for any IPv4 subnet. Includes binary representation and IP class detection.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['bandwidth-calculator', 'rate-limit-calculator', 'electricity-cost-calculator', 'password-generator'],
    relatedPosts: ['electricity-cost-calculator-guide'],
    seoKeywords: ['IP subnet calculator', 'CIDR calculator', 'subnet mask', 'network address', 'broadcast address', 'usable host range', 'IPv4 subnetting', 'CCNA calculator', 'binary subnet'],
    schema: 'both',
    mathSolverExpression: 'Network = IP & Mask | Broadcast = IP | ~Mask | Hosts = 2^(32-CIDR) - 2',
    lastVerified: '2026-01-15',
    loader: () => import('../math/ip-subnet/index'),
  },
  {
    id: 'bandwidth-calculator',
    title: 'Bandwidth Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Bandwidth Calculator',
    description: 'Calculate file transfer times based on connection speed. Includes TCP overhead simulation and clear bit vs byte distinction (Mbps vs MB/s).',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['ip-subnet-calculator', 'rate-limit-calculator', 'electricity-cost-calculator'],
    seoKeywords: ['bandwidth calculator', 'download time calculator', 'file transfer time', 'Mbps to MB/s', 'internet speed calculator', 'network throughput', 'TCP overhead'],
    schema: 'both',
    mathSolverExpression: 'TransferTime = FileSizeBytes / (Speed x (1 - Overhead))',
    lastVerified: '2026-01-15',
    relatedPosts: ['electricity-cost-calculator-guide'],
    loader: () => import('../math/bandwidth/index'),
  },
  {
    id: 'password-generator',
    title: 'Password Generator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Password Gen',
    description: 'Generate cryptographically secure passwords with customizable length and character types. Free online calculator with formula guide and step-by-step results.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['crypto-hash-generator', 'base64-encoder-decoder', 'character-token-converter'],
    seoKeywords: ['password generator', 'secure password', 'random password', 'passphrase generator', 'strong password creator', 'crypto random', 'password entropy', 'crack time estimate', 'CSPRNG'],
    schema: 'both',
    mathSolverExpression: 'E = L x log2(S) | password entropy in bits',
    lastVerified: '2026-01-15',
    loader: () => import('../math/password-generator/index'),
  },
  {
    id: 'base64-encoder-decoder',
    title: 'Base64 Encoder / Decoder — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Base64 Encoder / Decoder',
    description: 'Encode text to Base64 or decode Base64 back to text instantly. Supports text and file input with live encoding and one-click copy.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['url-encoder-decoder', 'password-generator', 'crypto-hash-generator', 'character-token-converter'],
    relatedPosts: ['electricity-cost-calculator-guide'],
    seoKeywords: ['base64 encoder', 'base64 decoder', 'base64 encode', 'base64 decode', 'base64 converter', 'base64 tool', 'data encoding', 'base64 text'],
    schema: 'both',
    mathSolverExpression: 'Base64 = binary-to-text encoding using 64-character alphabet',
    lastVerified: '2026-01-15',
    loader: () => import('../math/base64/index'),
  },
  {
    id: 'url-encoder-decoder',
    title: 'URL Encoder / Decoder — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'URL Encode',
    description: 'Encode text for safe URL transmission or decode URL-encoded strings. Shows character mappings for special characters. Free, instant, and accurate.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['base64-encoder-decoder', 'character-token-converter'],
    seoKeywords: ['url encoder', 'url decoder', 'url encode', 'url decode', 'percent encoding', 'url escape', 'special characters encoding'],
    schema: 'both',
    mathSolverExpression: 'URL Encode = percent-encode special characters for safe URL transmission',
    lastVerified: '2026-01-15',
    loader: () => import('../math/url-encode/index'),
  },
  {
    id: 'character-token-converter',
    title: 'Character-to-Token Converter — Estimate LLM Token Counts',
    shortTitle: 'Token Converter',
    description: 'Estimate token counts for any text across OpenAI (cl100k_base), Claude, Llama 3, and General tokenizers. Free, instant, and accurate.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['url-encoder-decoder', 'password-generator', 'ai-token-pricing'],
    seoKeywords: ['token converter', 'character to token converter', 'token counter', 'openai token estimator', 'claude token counter', 'llama 3 tokenizer', 'cl100k_base token counter', 'llm token calculator', 'token cost estimator'],
    schema: 'both',
    mathSolverExpression: 'Tokens ≈ Characters x TokenRatio | Token/Char ratio varies by tokenizer and language',
    lastVerified: '2026-01-15',
    loader: () => import('../math/character-token/index'),
  },
  {
    id: 'ohms-law-calculator',
    title: "Ohm's Law Calculator",
    shortTitle: "Ohm's Law",
    description: "Calculate voltage, current, resistance, or power using Ohm's Law. Enter any two known electrical values to solve for the unknown.",
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'Electrical',
    relatedIds: ['resistor-calculator', 'voltage-drop-calculator', 'wire-gauge-calculator', 'electricity-cost-calculator'],
    seoKeywords: ["ohm's law calculator", 'voltage current resistance calculator', 'electrical calculator', 'ohms law formula', 'power calculator electronics', 'v=ir calculator'],
    schema: 'both',
    mathSolverExpression: 'V = I x R | P = V x I | Ohms law: voltage, current, resistance, power relationships',
    lastVerified: '2026-01-15',
    relatedPosts: ['resistor-color-code-calculator-guide'],
    loader: () => import('../engineering/ohms-law/index'),
  },
  {
    id: 'voltage-drop-calculator',
    title: 'Voltage Drop Calculator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Voltage Drop',
    description: 'Calculate voltage drop over a wire run based on AWG gauge, wire length, and current. Checks compliance with the NEC 3% recommended maximum.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'Electrical',
    relatedIds: ['ohms-law-calculator', 'wire-gauge-calculator', 'resistor-calculator'],
    seoKeywords: ['voltage drop calculator', 'wire voltage drop', 'nec voltage drop', 'electrical wire calculator', 'conductor voltage drop', 'voltage loss calculator', 'power loss in wires', 'awg voltage drop'],
    schema: 'both',
    mathSolverExpression: 'Vd = 2 x L x I x R / 1000 (single phase) | voltage drop over conductor length',
    lastVerified: '2026-05-18',
    relatedPosts: ['resistor-color-code-calculator-guide'],
    loader: () => import('../engineering/voltage-drop/index'),
  },
  {
    id: 'wire-gauge-calculator',
    title: 'Wire Gauge Ampacity Calculator — Free Online Calculator & Guide',
    shortTitle: 'Wire Gauge',
    description: 'Find the correct AWG wire gauge for any electrical circuit based on current, conductor material, insulation rating, and conduit fill.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'Electrical',
    relatedIds: ['ohms-law-calculator', 'voltage-drop-calculator', 'resistor-calculator'],
    seoKeywords: ['wire gauge calculator', 'awg calculator', 'wire ampacity calculator', 'what wire gauge do i need', 'wire size calculator', 'nec wire sizing'],
    schema: 'both',
    mathSolverExpression: 'AWG = 36 - 39 x log92(N) | CM = 92^((36-AWG)/39) x 127 | American wire gauge standard sizing',
    lastVerified: '2026-01-15',
    loader: () => import('../engineering/wire-gauge/index'),
  },
  {
    id: 'gear-ratio-calculator',
    title: 'Gear Ratio & RPM Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'Gear Ratio',
    description: 'Calculate output RPM, output torque, or gear ratio for any gear system. Supports speed reduction, overdrive, and compound gear train analysis.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'Mechanical',
    relatedIds: ['flow-rate-calculator', 'mtbf-calculator', 'ohms-law-calculator'],
    seoKeywords: ['gear ratio calculator', 'rpm calculator', 'gear ratio formula', 'output rpm calculator', 'transmission gear ratio', 'gear reduction calculator'],
    schema: 'both',
    mathSolverExpression: 'GR = N2/N1 = ω1/ω2 | OutputRPM = InputRPM / GR | gear train ratio calculation',
    lastVerified: '2026-01-15',
    loader: () => import('../engineering/gear-ratio/index'),
  },
  {
    id: 'mtbf-calculator',
    title: 'MTBF Reliability Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'MTBF Calculator',
    description: 'Calculate Mean Time Between Failures (MTBF), system reliability at a specific mission time, and expected number of failures for reliability engineering.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'Reliability',
    relatedIds: ['gear-ratio-calculator', 'flow-rate-calculator', 'rate-limit-calculator'],
    seoKeywords: ['mtbf calculator', 'mean time between failures', 'reliability calculator', 'failure rate calculator', 'system reliability', 'mtbf formula'],
    schema: 'both',
    mathSolverExpression: 'MTBF = TotalTime / Failures | R(t) = e^(-t/MTBF) | reliability engineering and failure rate',
    relatedPosts: ['electricity-cost-calculator-guide'],
    lastVerified: '2026-01-15',
    loader: () => import('../engineering/mtbf/index'),
  },
  {
    id: 'flow-rate-calculator',
    title: 'Fluid Flow Rate & Pipe Velocity Calculator — Free Online Calculator',
    shortTitle: 'Fluid Flow Rate & Pipe',
    description: 'Calculate pipe flow velocity, volumetric flow rate, or required pipe diameter using the continuity equation. Supports GPM and metric units.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'Mechanical',
    relatedIds: ['gear-ratio-calculator', 'mtbf-calculator'],
    seoKeywords: ['flow rate calculator', 'pipe velocity calculator', 'gpm calculator', 'pipe flow calculator', 'fluid flow calculator', 'volumetric flow rate calculator'],
    schema: 'both',
    mathSolverExpression: 'Q = A x v | volumetric flow rate from cross-sectional area and flow velocity',
    lastVerified: '2026-01-15',
    loader: () => import('../engineering/flow-rate/index'),
  },
  {
    id: 'ai-token-pricing',
    title: 'AI Token Pricing Calculator — Compare GPT-4o, Claude, Gemini Costs',
    shortTitle: 'AI Token Pricing',
    description: 'Compare token pricing across 12 models from 6 providers: GPT-5, Claude 4.7, Gemini 3.1, DeepSeek V3, Grok 3, Llama 4. Free, instant, and accurate.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['character-token-converter', 'rate-limit-calculator', 'password-generator'],
    seoKeywords: ['ai token calculator', 'llm cost calculator', 'gpt-5 pricing', 'claude 4.7 pricing', 'gemini 3.1 cost', 'deepseek v3 pricing', 'grok 3 api cost', 'ai api pricing comparison', 'prompt caching calculator', 'token cost estimator 2026', 'llama 4 api cost'],
    schema: 'both',
    mathSolverExpression: 'Cost = (InTokensxInPrice + OutTokensxOutPrice) x Requests x DAU | LLM API cost estimation',
    lastVerified: '2026-05-18',
    loader: () => import('../engineering/ai-token-pricing/index'),
  },
  {
    id: 'crypto-hash-generator',
    title: 'Crypto Hash Generator — SHA-256, MD5, SHA-1, SHA-512, Keccak-256',
    shortTitle: 'Crypto Hash',
    description: 'Generate cryptographic hashes locally in your browser using SHA-256, MD5, SHA-1, SHA-384, SHA-512, and Keccak-256 (SHA-3).',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['password-generator', 'base64-encoder-decoder', 'character-token-converter', 'url-encoder-decoder'],
    relatedPosts: ['electricity-cost-calculator-guide'],
    seoKeywords: ['crypto hash generator', 'sha-256 hash', 'md5 hash generator', 'keccak-256', 'sha-512 hash', 'hash calculator online', 'cryptographic hash tool', 'zero knowledge hashing', 'sha3-256', 'avalanche effect demo'],
    schema: 'both',
    mathSolverExpression: 'SHA-256, MD5, SHA-1, SHA-512, Keccak-256 | deterministic cryptographic hash algorithms',
    lastVerified: '2026-05-18',
    loader: () => import('../engineering/crypto-hash/index'),
  },
  {
    id: 'cookie-consent-banner-generator',
    title: 'Cookie Consent / Banner Generator — GDPR Cookie Notice Maker',
    shortTitle: 'Cookie Consent',
    description: 'Generate GDPR-compliant cookie consent banners with customizable position, layout, and color theme. Get ready-to-use HTML/CSS code for your website.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['url-encoder-decoder', 'base64-encoder-decoder', 'password-generator'],
    seoKeywords: ['cookie consent generator', 'gdpr cookie banner', 'cookie notice maker', 'cookie banner html css', 'gdpr consent banner generator', 'cookie policy banner tool', 'gdpr cookie compliance tool'],
    schema: 'both',
    mathSolverExpression: 'GDPR cookie consent banner | Art. 5(1)(a) data minimization | configurable position, layout, and theme',
    lastVerified: '2026-01-15',
    loader: () => import('../engineering/cookie-consent/index'),
  },
  {
    id: 'rate-limit-calculator',
    title: 'API Rate Limit & Throughput Calculator — RPS, Bandwidth & Burst',
    shortTitle: 'Rate Limit Calculator',
    description: 'Calculate API throughput including requests per second, bandwidth requirements, daily capacity, and burst limits. Free, instant, and accurate.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'Reliability',
    relatedIds: ['bandwidth-calculator', 'ip-subnet-calculator', 'mtbf-calculator', 'ai-token-pricing'],
    seoKeywords: ['api rate limit calculator', 'throughput calculator', 'rps calculator', 'api bandwidth calculator', 'rate limiting calculator', '429 too many requests', 'aws api gateway limits', 'burst capacity calculator', 'api concurrent users calculator', 'nginx rate limit'],
    schema: 'both',
    mathSolverExpression: 'RPS = Requests / Period | Burst = b + r x t | token bucket rate limiting algorithm',
    lastVerified: '2026-01-15',
    loader: () => import('../engineering/rate-limit/index'),
  },
  {
    id: 'ph-calculator',
    title: 'pH Calculator — H+ and OH- Concentration, pOH and Acid-Base Scale',
    shortTitle: 'pH Calculator',
    description: 'Calculate pH, pOH, H+ and OH- ion concentrations in aqueous solutions. Enter any known value to get the complete acid-base profile with step-by-step results.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['resistor-calculator', 'flow-rate-calculator', 'mtbf-calculator', 'electricity-cost-calculator'],
    relatedPosts: ['electricity-cost-calculator-guide'],
    seoKeywords: ['ph calculator', 'acid base calculator', 'ph to h+ concentration', 'poh calculator', 'h+ concentration calculator', 'oh- concentration calculator', 'chemistry calculator', 'ph scale', 'acid base chemistry', 'ph to concentration'],
    schema: 'both',
    mathSolverExpression: 'pH = -log10([H+]) | pOH = -log10([OH-]) | pH + pOH = 14 | [H+] = 10^(-pH) | At 25°C',
    lastVerified: '2026-01-15',
    loader: () => import('../engineering/ph-calculator/index'),
  },
  {
    id: 'nusselt-number-calculator',
    title: 'Nusselt Number Calculator — Convection Heat Transfer Analysis',
    shortTitle: 'Nusselt Number',
    description: 'Calculate the Nusselt number from convective heat transfer coefficient, characteristic length, and fluid thermal conductivity. Includes flow regime interpretation.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['prandtl-number-calculator', 'froude-number-calculator', 'flow-rate-calculator'],
    seoKeywords: ['nusselt number calculator', 'heat transfer calculator', 'convection coefficient', 'thermal conductivity', 'nusselt number formula', 'convective heat transfer', 'dimensionless number heat transfer', 'nusselt correlation', 'heat exchanger design'],
    schema: 'both',
    mathSolverExpression: 'Nu = h × L / k | Nusselt number = convective heat transfer coefficient × characteristic length / thermal conductivity',
    lastVerified: '2026-05-19',
    loader: () => import('../engineering/nusselt-number/index'),
  },
  {
    id: 'buffer-capacity-calculator',
    title: 'Buffer Capacity Calculator — Van Slyke Equation & Buffer Design',
    shortTitle: 'Buffer Capacity',
    description: 'Calculate buffer capacity (β) using the Van Slyke equation. Find how much acid or base your buffer can neutralize before pH changes. Includes selection guide.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['ph-calculator', 'freezing-point-depression-calculator', 'molarity-calculator'],
    seoKeywords: ['buffer capacity calculator', 'van slyke equation', 'buffer solution', 'acid base buffer', 'pH buffer capacity', 'buffer preparation', 'chemistry buffer', 'tris buffer', 'phosphate buffer', 'acetate buffer'],
    schema: 'both',
    mathSolverExpression: 'β = 2.303 × C × (Ka × [H+]) / (Ka + [H+])² | Van Slyke buffer capacity equation',
    lastVerified: '2026-05-19',
    loader: () => import('../engineering/buffer-capacity/index'),
  },
  {
    id: 'prandtl-number-calculator',
    title: 'Prandtl Number Calculator — Momentum vs Thermal Diffusivity',
    shortTitle: 'Prandtl Number',
    description: 'Calculate the Prandtl number from viscosity, specific heat, and thermal conductivity. Fluid classification for gases, water, oils, and liquid metals included.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['nusselt-number-calculator', 'froude-number-calculator', 'flow-rate-calculator', 'viscosity-converter'],
    seoKeywords: ['prandtl number calculator', 'prandtl number formula', 'momentum diffusivity', 'thermal diffusivity', 'prandtl number of water', 'prandtl number of air', 'fluid dynamics', 'dimensionless number', 'heat transfer prandtl'],
    schema: 'both',
    mathSolverExpression: 'Pr = μ × cp / k = ν / α | Prandtl number = dynamic viscosity × specific heat / thermal conductivity',
    lastVerified: '2026-05-19',
    loader: () => import('../engineering/prandtl-number/index'),
  },
  {
    id: 'froude-number-calculator',
    title: 'Froude Number Calculator — Open Channel Flow & Ship Hull Analysis',
    shortTitle: 'Froude Number',
    description: 'Calculate the Froude number for open channel flow, spillways, and ship hulls. Determine if flow is subcritical, critical, or supercritical with wave celerity.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['nusselt-number-calculator', 'prandtl-number-calculator', 'flow-rate-calculator', 'gear-ratio-calculator'],
    seoKeywords: ['froude number calculator', 'open channel flow', 'hydraulic jump', 'ship hull speed', 'subcritical flow', 'supercritical flow', 'critical flow', 'spillway design', 'froude number formula', 'naval architecture'],
    schema: 'both',
    mathSolverExpression: 'Fr = v / √(g × L) | Froude number = velocity / square root of (gravity × characteristic length)',
    lastVerified: '2026-05-19',
    loader: () => import('../engineering/froude-number/index'),
  },
  {
    id: 'lead-screw-calculator',
    title: 'Lead Screw Calculator — Torque, Efficiency & Mechanical Advantage',
    shortTitle: 'Lead Screw',
    description: 'Calculate required torque, mechanical advantage, and power for Acme and ball screw drives. Essential for 3D printer, CNC, and linear actuator design.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'Mechanical',
    relatedIds: ['gear-ratio-calculator', 'froude-number-calculator', 'torque-converter'],
    seoKeywords: ['lead screw calculator', 'ball screw torque', 'acme screw calculator', 'lead screw efficiency', 'linear actuator torque', 'cnc lead screw', '3d printer z axis torque', 'mechanical advantage screw', 'lead screw pitch'],
    schema: 'both',
    mathSolverExpression: 'T = F × p / (2π × η) | lead screw torque = axial force × lead / (2π × efficiency)',
    lastVerified: '2026-05-19',
    loader: () => import('../engineering/lead-screw/index'),
  },
  {
    id: 'freezing-point-depression-calculator',
    title: 'Freezing Point Depression Calculator — Colligative Properties',
    shortTitle: 'Freezing Point Depression',
    description: 'Calculate freezing point depression using the van\'t Hoff equation. Find how salt, antifreeze, or any solute lowers the freezing point. Includes molality auto-calculation.',
    category: 'Engineering',
    categorySlug: 'engineering',
    subCategory: 'General',
    relatedIds: ['buffer-capacity-calculator', 'ph-calculator', 'molarity-calculator'],
    seoKeywords: ['freezing point depression calculator', 'colligative properties', 'vant hoff factor', 'antifreeze calculator', 'road salt calculator', 'freezing point formula', 'cryoscopic constant', 'molality calculator', 'ice cream freezing point'],
    schema: 'both',
    mathSolverExpression: 'ΔTf = Kf × m × i | freezing point depression = cryoscopic constant × molality × van\'t Hoff factor',
    lastVerified: '2026-05-19',
    loader: () => import('../engineering/freezing-point-depression/index'),
  },
];
