import type { CalculatorEntry } from '../../types/calculator';

export const everydayCalculators: CalculatorEntry[] = [
  {
    id: 'wind-chill-calculator',
    title: 'Wind Chill Calculator — Frostbite Risk & Feels-Like Temperature (NWS)',
    shortTitle: 'Wind Chill',
    description: 'Calculate the wind chill feels-like temperature using the official NWS formula. Includes frostbite risk timeline, OSHA cold-stress safety guidelines, and.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['wind chill calculator', 'wind chill factor', 'NWS wind chill', 'frostbite risk', 'wind chill temperature', 'feels like temperature', 'cold weather safety'],
    relatedIds: ['heat-index-calculator', 'dew-point-calculator'],
    schema: 'both',
    mathSolverExpression: "WindChill = 35.74 + 0.6215T - 35.75(V^0.16) + 0.4275T(V^0.16) | NWS wind chill formula",
    lastVerified: '2026-05-17',
    reviewedBy: 'NOAA Meteorologist, OSHA Cold-Stress Safety Trainer',
    relatedPosts: ['sleep-cycle-calculator-guide'],
    loader: () => import('../math/wind-chill/index'),
  },
  {
    id: 'heat-index-calculator',
    title: 'Heat Index Calculator — OSHA Danger Tiers & Heatstroke Prevention',
    shortTitle: 'Heat Index',
    description: 'Calculate the heat index feels-like temperature using the official NOAA formula. Includes OSHA danger tiers, heatstroke warning signs, and sport/worksite.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['heat index calculator', 'feels like temperature', 'NOAA heat index', 'heat safety', 'OSHA heat guidelines', 'heat stroke prevention', 'humidity index'],
    relatedIds: ['wind-chill-calculator', 'dew-point-calculator'],
    schema: 'both',
    mathSolverExpression: 'Heat Index = f(T, RH) | NOAA heat index formula using temperature and relative humidity',
    lastVerified: '2026-05-17',
    reviewedBy: 'NOAA Heat Safety Researcher, OSHA Workplace Safety Specialist',
    relatedPosts: ['sleep-cycle-calculator-guide'],
    loader: () => import('../math/heat-index/index'),
  },
  {
    id: 'dew-point-calculator',
    title: 'Dew Point Calculator — Comfort Scale, HVAC Mold Prevention & Fog',
    shortTitle: 'Dew Point Calculator',
    description: 'Calculate the dew point from temperature and relative humidity using the Magnus formula. Free online calculator with formula guide and step-by-step results.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['dew point calculator', 'dew point temperature', 'humidity calculator', 'human comfort scale', 'sticky index', 'HVAC dew point', 'air moisture calculator'],
    relatedIds: ['wind-chill-calculator', 'heat-index-calculator'],
    schema: 'both',
    mathSolverExpression: 'Td = (b × γ(T,RH)) / (a - γ(T,RH)) | Magnus formula dew point calculation',
    lastVerified: '2026-05-17',
    reviewedBy: 'ASHRAE HVAC Design Engineer, NWS Meteorologist',
    relatedPosts: ['sleep-cycle-calculator-guide'],
    loader: () => import('../math/dew-point/index'),
  },
  {
    id: 'dice-roller',
    title: 'Dice Roller — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Dice Roller',
    description: 'Roll virtual dice from D4 to D20 with modifiers. Uses cryptographically secure random values. Free, instant, and accurate.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Gaming',
    seoKeywords: ['dice roller', 'dnd dice', 'D&D dice roller', 'virtual dice', 'D20', 'D6', 'random dice roll', 'tabletop dice', 'RPG dice', 'multiple dice'],
    relatedIds: ['edpi-calculator', 'robux-converter-calculator'],
    schema: 'both',
    mathSolverExpression: 'Roll N dice with S sides each, sum with modifier M',
    reviewedBy: 'Travel & lifestyle expert',
    lastVerified: '2026-01-15',
    loader: () => import('../math/dice-roller/index'),
  },
  {
    id: 'edpi-calculator',
    title: 'EDPI Calculator — Mouse Sensitivity Converter (eDPI & cm/360)',
    shortTitle: 'eDPI Calculator',
    description: 'Calculate your effective dots per inch (eDPI) from DPI and in-game sensitivity for popular FPS games. Free, instant, and accurate.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Gaming',
    seoKeywords: ['edpi calculator', 'mouse sensitivity converter', 'cm/360 calculator', 'valorant sensitivity', 'cs2 sensitivity', 'overwatch sensitivity', 'apex legends sensitivity', 'effective dpi calculator', 'gaming mouse calculator'],
    relatedIds: ['dice-roller', 'robux-converter-calculator'],
    schema: 'both',
    mathSolverExpression: 'eDPI = DPI x InGameSensitivity | cm/360 = (360 x 2.54) / (eDPI x Yaw)',
    relatedPosts: ['sleep-cycle-calculator-guide'],
    lastVerified: '2026-01-15',
    loader: () => import('../math/edpi/index'),
  },
  {
    id: 'love-calculator',
    title: 'Love Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Love Calculator',
    description: 'Discover your compatibility score with a fun, deterministic love algorithm. Includes zodiac compatibility insights, shareable results card, and flavor.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['love calculator', 'love match', 'compatibility test', 'name love test', 'crush calculator', 'relationship quiz', 'zodiac compatibility', 'flame test'],
    relatedIds: ['numerology-calculator', 'moon-phase-calculator'],
    schema: 'both',
    mathSolverExpression: 'Love Score = L.O.V.E letter values + shared letter chemistry bonus (0-100%)',
    lastVerified: '2026-01-15',
    loader: () => import('../math/love-calculator/index'),
  },
  {
    id: 'shoe-size-calculator',
    title: 'Shoe Size Converter — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Shoe Size Converter',
    description: 'Convert shoe sizes across US, UK, EU, and Japan/CM systems with mens and womens sizing and smart interpolation for half sizes. Free, instant, and accurate.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['shoe size converter', 'US to UK shoe size', 'EU shoe size', 'CM shoe size', 'shoe size chart', 'international shoe conversion', 'foot length cm', 'mens to womens shoe size'],
    relatedIds: ['clothing-size-converter', 'bra-size-calculator', 'pixels-to-inches-calculator'],
    schema: 'both',
    mathSolverExpression: 'Convert between US, UK, EU, and JP shoe sizing systems with interpolation',
    lastVerified: '2026-01-15',
    reviewedBy: 'Footwear industry sizing specialist',
    loader: () => import('../math/shoe-size/index'),
  },
  {
    id: 'clothing-size-converter',
    title: 'Clothing Size Converter — International Size Charts for Men',
    shortTitle: 'Clothing Sizes',
    description: 'Convert clothing sizes between US, UK, EU, and Japanese sizing for dresses, shirts, shoes, and more. Includes men, women, and children sizes.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Shopping & Discounts',
    seoKeywords: ['clothing size converter', 'international size chart', 'us to eu size', 'shoe size converter', 'dress size converter', 'clothing size chart', 'mens suit size', 'womens dress size'],
    relatedIds: ['shoe-size-calculator', 'bra-size-calculator', 'oven-temperature-converter-everyday', 'percent-off-calculator'],
    schema: 'both',
    mathSolverExpression: 'US â†” EU â†” UK | clothing size conversion chart',
    lastVerified: '2026-01-15',
    reviewedBy: 'Fashion industry sizing specialist',
    relatedPosts: ['percent-off-discount-guide', 'tipping-calculator-guide'],
    loader: () => import('../everyday/clothing-size-converter/index'),
  },
  {
    id: 'countdown-calculator',
    title: 'Countdown Calculator — Days Until Any Event or Date',
    shortTitle: 'Countdown Calculator — Days Until',
    description: 'Calculate the exact time remaining until any date. See days, weeks, months, and hours until your next event, birthday, or deadline.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Time & Date',
    seoKeywords: ['countdown calculator', 'days until calculator', 'time until date', 'event countdown', 'date difference calculator', 'days hours minutes countdown', 'countdown timer'],
    relatedIds: ['age-calculator', 'working-days-calculator', 'moon-phase-calculator', 'time-duration-calculator'],
    schema: 'both',
    mathSolverExpression: 'Time Remaining = Target_Date - Current_Date',
    lastVerified: '2026-01-15',
    loader: () => import('../everyday/countdown-calculator/index'),
  },
  {
    id: 'bra-size-calculator',
    title: 'Bra Size Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Bra Size Calculator',
    description: 'Find your correct bra size using the modern 6-measurement method (underbust loose/snug/tight, bust standing/leaning/lying).',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['bra size calculator', 'bra fitting', 'ABraThatFits', 'sister sizes', 'band size', 'cup size', 'bra measurement guide', 'accurate bra sizing', '6 measurement bra'],
    relatedIds: ['clothing-size-converter', 'shoe-size-calculator'],
    schema: 'both',
    mathSolverExpression: 'Band = Round(Snug Underbust) to even | Cup = Bust Average âˆ’ Band',
    lastVerified: '2026-01-15',
    loader: () => import('../math/bra-size/index'),
  },
  {
    id: 'sleep-calculator',
    title: 'Sleep Cycle Calculator — 90-Minute REM Cycles, Optimal Bedtime &',
    shortTitle: 'Sleep Cycle Calculator',
    description: 'Calculate your optimal bedtime or wake-up time using 90-minute sleep cycles and sleep onset latency. Free, instant, and accurate.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['sleep calculator', 'sleep cycle calculator', 'best bedtime', 'wake up calculator', 'REM cycles', '90 minute cycles', 'sleep optimization', 'circadian rhythm'],
    relatedIds: ['age-calculator', 'moon-phase-calculator'],
    schema: 'both',
    mathSolverExpression: 'Sleep Time = N × 90 min cycles + 14 min fall-asleep',
    lastVerified: '2026-05-17',
    reviewedBy: 'Sleep Medicine Physician, CDC Sleep Health Researcher',
    relatedPosts: ['sleep-cycle-calculator-guide'],
    loader: () => import('../math/sleep/index'),
  },
  {
    id: 'golf-handicap-calculator',
    title: 'Golf Handicap Calculator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Golf Handicap',
    description: 'Calculate your World Handicap System (WHS) index from recent rounds. Supports 5 to 20 rounds with proper differential selection.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['golf handicap calculator', 'WHS handicap', 'golf handicap index', 'score differential', 'course handicap', 'golf scoring', 'handicap system'],
    relatedIds: ['betting-odds-calculator', 'percentage-calculator'],
    schema: 'both',
    mathSolverExpression: 'Index = Avg(Lowest 8 of 20) x 0.96 | Diff = (Score - Rating) x 113 / Slope',
    lastVerified: '2026-01-15',
    loader: () => import('../math/golf-handicap/index'),
  },
  {
    id: 'percent-off-calculator',
    title: 'Percent Off Calculator — Stacked Discounts & Sales Tax',
    shortTitle: 'Percent Off Calculator',
    description: 'Calculate the true final price after stacked discounts and local sales tax. See why "20% off plus an extra 10%" is NOT 30% off, and get the real effective.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Shopping & Discounts',
    seoKeywords: ['percent off calculator', 'discount calculator', 'stacked discount calculator', 'sale price calculator', 'percentage off calculator', 'final price calculator'],
    relatedIds: ['tip-calculator', 'percentage-calculator'],
    schema: 'both',
    mathSolverExpression: 'FinalPrice = Base x (1-d1) x (1-d2) | EffectiveDiscount = 1 - âˆ(1-di)',
    lastVerified: '2026-01-15',
    loader: () => import('../finance/percent-off/index'),
  },
  {
    id: 'age-calculator',
    title: 'Age Calculator — Find Your Exact Age in Years, Months, Days & Hours',
    shortTitle: 'Age Calculator',
    description: 'Find exact age in years, months, and days between dates. Shows total days, weeks, months, and hours lived plus a next birthday countdown timer.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Time & Date',
    seoKeywords: ['age calculator', 'how old am i', 'exact age calculator', 'birthday calculator', 'days lived calculator', 'age in days', 'age in years months days', 'next birthday countdown', 'chronological age calculator'],
    relatedIds: ['working-days-calculator', 'moon-phase-calculator', 'sleep-calculator', 'countdown-calculator'],
    schema: 'both',
    mathSolverExpression: 'Age = CurrentDate - BirthDate | exact years, months, days elapsed',
    lastVerified: '2026-05-17',
    reviewedBy: 'Date & Time Calculation Expert, Health & Wellness Advisor',
    relatedPosts: ['age-calculator-guide'],
    loader: () => import('../everyday/age-calculator/index'),
  },
  {
    id: 'percentage-calculator',
    title: 'Percentage Calculator — Tips, Discounts, Tax and % Change',
    shortTitle: 'Percentage',
    description: 'Calculate percentages for tips, discounts, sales tax, and percent change. Five modes: find percent of number, percent change, add or subtract percentage.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Shopping & Discounts',
    seoKeywords: ['percentage calculator', 'percent calculator', 'percentage change calculator', 'what percent of', 'how to calculate percentage', 'percent increase calculator', 'percent off calculator', 'discount percentage calculator', 'tip percentage calculator'],
    relatedIds: ['percent-off-calculator', 'tip-calculator', 'discount-calculator'],
    schema: 'both',
    mathSolverExpression: 'P% of X = X x P/100 | % Change = (New-Old)/Old x 100',
    lastVerified: '2026-05-17',
    reviewedBy: 'Mathematics Educator, Financial Literacy Advisor',
    relatedPosts: ['betting-odds-explained-guide', 'fractions-math-guide', 'gpa-calculator-guide', 'percent-off-discount-guide', 'tipping-calculator-guide'],
    loader: () => import('../everyday/percentage-calculator/index'),
  },
  {
    id: 'study-time-calculator',
    title: 'Study Time Calculator — Plan Your Exam Prep Schedule',
    shortTitle: 'Study Time',
    description: 'Calculate how many study hours you need based on material volume and deadline. Plan your weekly schedule and avoid last-minute cramming.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Time & Date',
    seoKeywords: ['study time calculator', 'exam prep planner', 'study schedule calculator', 'reading speed estimator', 'study hours calculator', 'exam preparation tool', 'study planner'],
    relatedIds: ['countdown-calculator', 'time-duration', 'age-calculator'],
    schema: 'both',
    mathSolverExpression: 'Total Hours = (Pages / Pages_per_Hour) x Difficulty x Sessions',
    lastVerified: '2026-01-15',
    loader: () => import('../everyday/study-time-calculator/index'),
  },
  {
    id: 'tip-calculator',
    title: 'Tip and Bill Splitter — Calculate Restaurant Tips Per Person',
    shortTitle: 'Tip Splitter',
    description: 'Calculate and split a restaurant tip among multiple people. Choose 10-30% tip, see per-person breakdown with pre-tax calculation and itemized totals.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Shopping & Discounts',
    seoKeywords: ['tip calculator', 'bill splitter', 'tip splitter', 'restaurant tip calculator', 'how much to tip', 'split the bill calculator', 'gratuity calculator', 'dinner bill calculator', 'group tip calculator'],
    relatedIds: ['percent-off-calculator', 'percentage-calculator', 'wedding-alcohol-calculator'],
    schema: 'both',
    mathSolverExpression: 'Tip = Bill x Tip% | Each = (Bill + Tip) / People',
    lastVerified: '2026-05-17',
    reviewedBy: 'Hospitality Industry Expert, Personal Finance Advisor',
    relatedPosts: ['percent-off-discount-guide', 'tipping-calculator-guide'],
    loader: () => import('../everyday/tip-splitter/index'),
  },
  {
    id: 'working-days-calculator',
    title: 'Working Days Between Two Dates — Free Online Calculator & Guide',
    shortTitle: 'Working Days',
    description: 'Count the exact number of working days (business days) between two dates, excluding weekends and US federal holidays. Free, instant, and accurate.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Time & Date',
    seoKeywords: ['working days calculator', 'business days calculator', 'days between dates', 'weekdays between dates', 'work days counter', 'business day calculator'],
    relatedIds: ['age-calculator', 'moon-phase-calculator', 'schengen-visa-calculator'],
    schema: 'both',
    mathSolverExpression: 'WorkingDays = Total - Weekends - Holidays | business days count',
    lastVerified: '2026-01-15',
    loader: () => import('../everyday/working-days/index'),
  },
  {
    id: 'word-count-calculator',
    title: 'Word & Character Count Tool — Flesch-Kincaid Readability, Keyword',
    shortTitle: 'Word Count',
    description: 'Count words, characters, sentences, and paragraphs in any text. Estimates reading and speaking time with Flesch-Kincaid grade level, keyword density.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['word count tool', 'character counter', 'word counter online', 'reading time calculator', 'count words', 'text analyzer', 'flesch-kincaid readability', 'keyword density checker', 'speaking time estimator'],
    relatedIds: ['wpm-typing-test-calculator', 'reading-time-calculator'],
    schema: 'both',
    mathSolverExpression: 'Words = split(text, /\s+/) | Characters = len(text) | ReadingTime = Words / WPM | FKGL = 0.39×(W/S) + 11.8×(Syl/W) - 15.59',
    lastVerified: '2026-05-18',
    reviewedBy: 'SEO Content Strategist, Academic Writing Instructor',
    relatedPosts: ['age-calculator-guide'],
    loader: () => import('../everyday/word-count/index'),
  },
  {
    id: 'robux-converter-calculator',
    title: 'Robux / V-Bucks Converter — Virtual Currency to USD',
    shortTitle: 'Robux Converter',
    description: 'Convert Robux, V-Bucks, and Roblox Premium to USD using official package pricing. Find the best-value package with the lowest cost per virtual currency unit.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Gaming',
    seoKeywords: ['robux to usd', 'robux converter', 'v bucks to usd', 'v-bucks calculator', 'roblox currency converter', 'fortnite v-bucks calculator', 'robux price calculator', 'virtual currency converter'],
    relatedIds: ['edpi-calculator', 'dice-roller', 'random-number-generator'],
    relatedPosts: ['percent-off-discount-guide'],
    schema: 'both',
    mathSolverExpression: 'USD = ceil(Amount / PackageSize) x PackagePrice | EffectiveRate = USD / Amount',
    lastVerified: '2026-05-17',
    reviewedBy: 'Gaming Industry Analyst, Personal Finance Advisor',
    loader: () => import('../everyday/robux-converter/index'),
  },
  {
    id: 'moon-phase-calculator',
    title: 'Moon Phase Calculator — Lunar Calendar & Zodiac Sign Finder',
    shortTitle: 'Moon Phase',
    description: 'Find the moon phase, illumination percentage, and zodiac sign for any date. See the phase emoji, next full moon date, and days until the next full moon.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Astronomy',
    seoKeywords: ['moon phase calculator', 'moon phase date', 'lunar calendar', 'moon illumination', 'zodiac sign finder', 'full moon date', 'new moon calculator', 'astronomy tool'],
    relatedIds: ['age-calculator', 'working-days-calculator', 'numerology-calculator'],
    schema: 'both',
    mathSolverExpression: 'Phase = ((JD - 2451550.1) / 29.530588853) mod 1 | Illumination based on lunar age',
    lastVerified: '2026-01-15',
    loader: () => import('../everyday/moon-phase/index'),
  },
  {
    id: 'pixels-to-inches-calculator',
    title: 'Pixels to Inches Converter — DPI/PPI with Print Size Presets',
    shortTitle: 'Pixels to Inches',
    description: 'Convert pixels to inches at any DPI/PPI with presets for web, screen, draft, and print. Shows print size in inches, cm, and mm for A4, letter, and photo sizes.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Conversions',
    relatedIds: ['aspect-ratio-calculator', 'oven-temperature-converter-everyday', 'clothing-size-converter'],
    seoKeywords: ['pixels to inches calculator', 'px to inches', 'dpi calculator', 'ppi calculator', 'image print size calculator', 'pixel to print size', '300 dpi to pixels', 'resolution calculator', 'photo print size calculator'],
    schema: 'both',
    mathSolverExpression: 'Inches = Pixels / DPI | cm = Inches x 2.54 | mm = Inches x 25.4',
    lastVerified: '2026-05-17',
    reviewedBy: 'Professional Photographer, Graphic Designer',
    relatedPosts: ['square-footage-calculator-guide'],
    loader: () => import('../everyday/pixels-to-inches/index'),
  },
  {
    id: 'aspect-ratio-calculator',
    title: 'Aspect Ratio Calculator — Social Media Presets & Missing Dimension',
    shortTitle: 'Aspect Ratio',
    description: 'Calculate the aspect ratio from any width and height. Identify common presets (16:9, 4:3, 1:1, 3:2, 21:9, 9:16) or find the missing dimension when you.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Conversions',
    relatedIds: ['pixels-to-inches-calculator', 'oven-temperature-converter-everyday', 'clothing-size-converter'],
    seoKeywords: ['aspect ratio calculator', '16:9 calculator', '4:3 calculator', 'image aspect ratio', 'video aspect ratio', 'social media image size', 'youtube thumbnail size', 'instagram post size', 'tiktok video size', 'resolution aspect ratio'],
    schema: 'both',
    mathSolverExpression: 'GCD(W, H) â†’ simplified W:H | Missing dimension = known dimension x target ratio',
    reviewedBy: 'Travel & lifestyle expert',
    lastVerified: '2026-01-15',
    loader: () => import('../everyday/aspect-ratio/index'),
  },
  {
    id: 'oven-temperature-converter-everyday',
    title: 'Oven Temperature Converter — °F, °C & Gas Mark — Calculator',
    shortTitle: 'Oven Temperature Converter — °F,',
    description: 'Convert oven temperatures between Fahrenheit, Celsius, and Gas Mark. Includes a cooking temperature reference table with descriptions (Slow, Moderate.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Conversions',
    seoKeywords: ['oven temperature converter', 'fahrenheit to celsius oven', 'gas mark converter', 'oven temp conversion', 'cooking temperature converter', 'f to c oven', 'gas mark to celsius', 'baking temperature conversion', 'recipe temperature converter', 'uk gas mark to fahrenheit'],
    schema: 'both',
    mathSolverExpression: '°C = (°F - 32) x 5/9 | °F = °C x 9/5 + 32 | Gas Mark = nearest match in standard oven scale',
    relatedPosts: ['pregnancy-due-date-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['recipe-scaler-calculator', 'pixels-to-inches-calculator', 'aspect-ratio-calculator', 'clothing-size-converter'],
    loader: () => import('../everyday/oven-temperature-converter/index'),
  },
  {
    id: 'bpm-tapper-calculator',
    title: 'BPM Tapper & Delay Time Calculator — For Music Producers',
    shortTitle: 'BPM Tapper',
    description: 'Convert BPM to delay times in milliseconds for any note value (whole, half, quarter, eighth, sixteenth, dotted, triplet).',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['bpm tapper', 'tap tempo tool', 'delay time calculator', 'bpm to milliseconds', 'music producer calculator', 'reverb delay calculator', 'bpm counter', 'tempo tap', 'lfo sync calculator', 'audio delay calculator'],
    relatedIds: ['depth-of-field-calculator', 'wpm-typing-test-calculator'],
    schema: 'both',
    mathSolverExpression: 'Delay(ms) = 60000 / BPM x Divisor | Hz = 1000 / Delay(ms)',
    lastVerified: '2026-01-15',
    loader: () => import('../everyday/bpm-tapper/index'),
  },
  {
    id: 'recipe-scaler-calculator',
    title: 'Recipe Scaler & Ingredient Converter — Adjust Any Recipe',
    shortTitle: 'Recipe Scaler',
    description: 'Scale any recipe up or down by changing the serving size. Enter ingredients with fractions like "1 1/2 cups" and get exact scaled quantities.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Conversions',
    seoKeywords: ['recipe scaler', 'recipe converter', 'ingredient calculator', 'scale recipe up', 'recipe multiplier', 'fraction to decimal cooking', 'baking ingredient calculator', 'kitchen calculator', 'serving size converter'],
    relatedIds: ['oven-temperature-converter-everyday', 'wedding-alcohol-calculator', 'tip-calculator', 'percent-off-calculator'],
    schema: 'both',
    mathSolverExpression: 'ScaleFactor = DesiredServings / OriginalServings | ScaledQty = Qty x ScaleFactor',
    lastVerified: '2026-01-15',
    reviewedBy: 'Professional chef & recipe developer',
    relatedPosts: ['fractions-math-guide', 'tipping-calculator-guide'],
    loader: () => import('../everyday/recipe-scaler/index'),
  },
  {
    id: 'reading-time-calculator',
    title: 'Reading Time Calculator — How Long to Read Any Text',
    shortTitle: 'Reading Time',
    description: 'Estimate how long it takes to read any text based on word count, reading speed, and content type. Includes breaks for long sessions.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Time & Date',
    seoKeywords: ['reading time calculator', 'how long to read', 'reading speed calculator', 'words per minute calculator', 'book reading time', 'article reading time estimator', 'study time calculator'],
    relatedIds: ['word-count', 'wpm-typing-test', 'time-duration'],
    schema: 'both',
    mathSolverExpression: 'Reading Time = Word_Count / Speed x Content_Multiplier',
    lastVerified: '2026-01-15',
    loader: () => import('../everyday/reading-time-calculator/index'),
  },
  {
    id: 'wedding-alcohol-calculator',
    title: 'Wedding & Party Alcohol Calculator — Beer, Wine & Cocktails by',
    shortTitle: 'Wedding Alcohol',
    description: 'Calculate exactly how much beer, wine, and liquor to buy for your wedding or party. Based on guest count, drinking percentage, event duration, and drink.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    reviewedBy: 'Hospitality industry expert, certified event planner',
    seoKeywords: ['wedding alcohol calculator', 'party drink calculator', 'how much alcohol for wedding', 'wedding bar calculator', 'event alcohol calculator', 'drink calculator', 'wedding beverage calculator', 'party planning calculator', 'how many drinks for 100 guests'],
    relatedIds: ['recipe-scaler-calculator', 'tip-calculator', 'countdown-calculator', 'percent-off-calculator'],
    schema: 'both',
    mathSolverExpression: 'Beers = Guests x Beer% x Hours x 1.5 | Wine = Guests x Wine% x Hours x 1.0 | Liquor = Guests x Liquor% x Hours x 0.75',
    lastVerified: '2026-01-15',
    relatedPosts: ['tipping-calculator-guide', 'percent-off-discount-guide'],
    loader: () => import('../everyday/wedding-alcohol/index'),
  },
  {
    id: 'wpm-typing-test-calculator',
    title: 'WPM Typing Test — Net WPM, Accuracy & Error Breakdown',
    shortTitle: 'Typing Test',
    description: 'Calculate your net and gross typing speed in WPM. Paste your source text and what you typed to get accuracy percentage, error count, and net WPM.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['typing test', 'wpm test', 'words per minute test', 'typing speed test', 'net wpm calculator', 'typing accuracy test', 'free typing test', 'online typing speed test', 'keyboard speed test', 'typing test timer'],
    relatedIds: ['word-count-calculator', 'bpm-tapper-calculator'],
    schema: 'both',
    mathSolverExpression: 'GrossWPM = (TotalChars / 5) / Minutes | NetWPM = GrossWPM x Accuracy | Accuracy = CorrectChars / TotalChars x 100',
    reviewedBy: 'Lifestyle & productivity expert',
    lastVerified: '2026-01-15',
    loader: () => import('../everyday/wpm-typing-test/index'),
  },
  {
    id: 'schengen-visa-calculator',
    title: 'Schengen Visa 90/180 Day Calculator — Rolling Window Tracker',
    shortTitle: 'Schengen Calculator',
    description: 'Track your days in the Schengen Area with the 90/180 day rule. Enter your trips to see total days used, remaining days, and whether future dates will.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Travel',
    seoKeywords: ['schengen visa calculator', '90 180 day rule', 'schengen days calculator', 'schengen stay calculator', '90 day schengen rule', 'schengen visa days remaining', 'europe travel calculator', 'schengen area calculator', 'visa overstay calculator'],
    relatedIds: ['working-days-calculator', 'age-calculator'],
    schema: 'both',
    mathSolverExpression: 'DaysInWindow = Î£(tripDays overlapping [checkDate-180, checkDate]) | Remaining = 90 - DaysInWindow',
    reviewedBy: 'Consumer tools specialist',
    lastVerified: '2026-01-15',
    loader: () => import('../everyday/schengen-visa/index'),
  },
  {
    id: 'betting-odds-calculator',
    title: 'Betting Odds Converter + Implied Probability — American, Decimal',
    shortTitle: 'Odds Converter',
    description: 'Convert betting odds between American, Decimal, and Fractional formats. See the implied probability, payout, and profit for any stake.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['betting odds converter', 'odds calculator', 'implied probability calculator', 'american to decimal odds', 'betting payout calculator', 'sports betting odds', 'fractional odds to decimal', 'parlay calculator', 'vig calculator', 'overround calculator'],
    relatedIds: ['golf-handicap-calculator', 'percentage-calculator'],
    schema: 'both',
    mathSolverExpression: 'Decimal = (Positive/100) + 1 | Decimal = (100/|Negative|) + 1 | ImpliedProb = 1/Decimal x 100',
    lastVerified: '2026-01-15',
    relatedPosts: ['betting-odds-explained-guide'],
    loader: () => import('../everyday/betting-odds/index'),
  },
  {
    id: 'depth-of-field-calculator',
    title: 'Depth of Field Calculator — Sensor Size, Aperture & Hyperfocal',
    shortTitle: 'Depth of Field',
    description: 'Calculate depth of field for any camera setup with 7 sensor formats. Enter sensor size, focal length, aperture, and subject distance to find near/far.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['depth of field calculator', 'dof calculator', 'hyperfocal distance calculator', 'aperture calculator', 'camera depth of field', 'photography calculator', 'lens calculator', 'sensor size dof', 'circle of confusion', 'focus calculator', 'portrait photography', 'landscape photography hyperfocal'],
    relatedIds: ['pixels-to-inches-calculator', 'aspect-ratio-calculator', 'bpm-tapper-calculator'],
    schema: 'both',
    mathSolverExpression: 'H = f² / (A × CoC) | Near = (H × D) / (H + D) | Far = (H × D) / (H − D) when H > D | DOF = Far − Near',
    lastVerified: '2026-05-18',
    reviewedBy: 'Professional Photographer, Optics Engineer',
    relatedPosts: ['age-calculator-guide'],
    loader: () => import('../everyday/depth-of-field/index'),
  },
  {
    id: 'yarn-yardage-calculator',
    title: 'Yarn Yardage & Fabric Calculator — Knit, Crochet & Precut',
    shortTitle: 'Yarn Yardage',
    description: 'Estimate yarn yardage for scarves, blankets, sweaters, and hats. Adjusts for gauge, yarn weight, and includes a precut fabric converter with yard equivalents.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['yarn yardage calculator', 'yarn calculator', 'fabric calculator', 'crochet yarn calculator', 'knitting yarn calculator', 'jelly roll yardage', 'precut fabric calculator', 'quilt fabric calculator', 'yarn skein calculator', 'how much yarn do i need'],
    relatedIds: ['clothing-size-converter', 'recipe-scaler-calculator', 'oven-temperature-converter-everyday'],
    schema: 'both',
    mathSolverExpression: 'BaseYardage = ProjectYardage × (20/stGauge) × (24/rowGauge) | TotalYards = BaseYardage × 1.2 (waste) | Meters = Yards × 0.9144',
    lastVerified: '2026-05-17',
    reviewedBy: 'Craft & Textile Artisan, Knitting Pattern Designer',
    relatedPosts: ['square-footage-calculator-guide'],
    loader: () => import('../everyday/yarn-yardage/index'),
  },
  {
    id: 'numerology-calculator',
    title: 'Numerology & Life Path Number Calculator — Full Personality',
    shortTitle: 'Numerology',
    description: 'Calculate your Life Path number from your birth date with detailed personality profiles for numbers 1-9 and master numbers 11, 22, 33.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    seoKeywords: ['numerology calculator', 'life path number calculator', 'numerology number calculator', 'life path number meaning', 'destiny number calculator', 'soul urge number', 'pythagorean numerology', 'numerology compatibility', 'birthdate numerology', 'what is my life path number', 'master number calculator'],
    relatedIds: ['love-calculator', 'moon-phase-calculator'],
    schema: 'both',
    mathSolverExpression: 'LifePath = Reduce(MM + DD + YYYY) to single digit (master 11/22/33 preserved)',
    lastVerified: '2026-05-18',
    reviewedBy: 'Pythagorean Numerology Scholar, Astrology & Self-Discovery Practitioner',
    relatedPosts: ['age-calculator-guide'],
    loader: () => import('../everyday/numerology/index'),
  },
  {
    id: 'mars-time-calculator',
    title: 'Mars Time Calculator — Sols, LMST & NASA Rover Mission Clock',
    shortTitle: 'Mars Time',
    description: 'Convert Earth UTC to Mars Local Mean Solar Time. Sol-to-Earth-day conversions, rover mission elapsed time for Curiosity, Perseverance, and InSight included.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Astronomy',
    relatedIds: ['moon-phase-calculator', 'countdown-calculator', 'time-zone-calculator'],
    seoKeywords: ['mars time calculator', 'mars sol calculator', 'mars local mean solar time', 'mars24', 'mars rover mission time', 'curiosity sol', 'perseverance sol', 'mars solar day', 'mars clock', 'mars time vs earth time'],
    schema: 'both',
    mathSolverExpression: '1 sol = 24h 39m 35.244s = 88,775.244 seconds | MSD = (JD − 2451549.5 + 4.5) / 1.0274912517 + 44796.0',
    lastVerified: '2026-05-19',
    reviewedBy: 'NASA mission planning & planetary science specialist',
    loader: () => import('../everyday/mars-time/index'),
  },
  {
    id: 'gestation-period-calculator',
    title: 'Gestation Period Calculator — 34 Animals, Breeding to Due Date',
    shortTitle: 'Gestation Period',
    description: 'Look up gestation periods for 34 animals from elephant to opossum. Calculate due dates from breeding dates for pets, livestock, and wildlife. Free and instant.',
    category: 'Everyday',
    categorySlug: 'everyday',
    subCategory: 'Misc',
    relatedIds: ['pig-gestation-calculator', 'due-date-calculator', 'age-calculator'],
    seoKeywords: ['gestation period calculator', 'animal gestation calculator', 'animal pregnancy calculator', 'dog gestation period', 'cat gestation period', 'horse gestation', 'elephant gestation', 'livestock breeding calculator', 'due date calculator animals', 'incubation period calculator'],
    schema: 'both',
    mathSolverExpression: 'DueDate = BreedingDate + GestationPeriod(species) | gestation periods for 34+ animal species',
    lastVerified: '2026-05-19',
    reviewedBy: 'Veterinary medicine & zoology specialist',
    loader: () => import('../everyday/gestation-period/index'),
  },
];
