import type { CalculatorEntry } from '../../types/calculator';

export const financeCalculators: CalculatorEntry[] = [
  {
    id: 'commission-calculator',
    title: 'Commission Calculator — Flat, Tiered & Real Estate Splits',
    shortTitle: 'Commission Calculator',
    description: 'Calculate your take-home commission across flat, tiered, and real estate split structures. Free online calculator with formula guide and step-by-step results.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Business & Accounting',
    seoKeywords: ['commission calculator', 'real estate commission calculator', 'tiered commission calculator', 'graduated commission calculator', 'sales commission calculator', 'broker split calculator'],
    schema: 'both',
    mathSolverExpression: 'commission = sale_price × commission_rate | total_commission = flat_fee + Σ(tier_rate × tier_amount for each tier) | net_to_seller = sale_price − total_commission − fees',
    lastVerified: '2026-01-15',
    relatedIds: ['irr-calculator', 'vat-calculator', 'business-loan-calculator'],
    relatedPosts: ['commission-calculator-guide'],
    loader: () => import('../finance/commission/index'),
  },
  {
    id: 'canadian-mortgage-calculator',
    title: 'Canadian Mortgage Calculator — Semi-Annual Compounding & CMHC',
    shortTitle: 'Canadian Mortgage',
    description: 'Canadian mortgage calculator with legally-correct semi-annual compounding, CMHC insurance premiums, and accelerated bi-weekly payment comparison.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Real Estate',
    seoKeywords: ['canadian mortgage calculator', 'mortgage calculator canada', 'cmhc calculator', 'accelerated bi-weekly mortgage', 'semi annual compound mortgage', 'canadian mortgage payment calculator', 'california mortgage calculator', 'texas mortgage calculator', 'florida mortgage calculator'],
    schema: 'both',
    mathSolverExpression: 'M = P × r(1+r)^n / ((1+r)^n − 1) with semi-annual compounding: monthly_rate = (1 + annualRate/2)^(2/12) − 1 | total_payment = M + CMHC_insurance_amortized | accelerated_biweekly = M × 12 / 26',
    lastVerified: '2026-01-15',
    relatedIds: ['va-mortgage-calculator', 'fha-loan-calculator', 'mortgage-amortization-calculator', 'arv-flipping-calculator'],
    relatedPosts: ['canadian-mortgage-calculator-guide'],
    loader: () => import('../finance/canadian-mortgage/index'),
  },
  {
    id: 'marriage-tax-calculator',
    title: 'Marriage Tax Calculator 2026 — Penalty vs. Bonus Comparison',
    shortTitle: 'Marriage Tax Calculator',
    description: 'Compare your tax bill filing as singles vs. married filing jointly with 2026 IRS brackets. Free online calculator with formula guide and step-by-step results.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Taxes',
    seoKeywords: ['marriage tax calculator', 'marriage penalty calculator', 'marriage bonus calculator', 'married filing jointly calculator', 'married vs single tax calculator', 'tax marriage penalty 2026', 'side by side tax comparison', 'marriage tax savings calculator', 'california income tax calculator 2026', 'new york tax calculator 2026', 'texas sales tax calculator', '2026 tax calculator'],
    schema: 'both',
    mathSolverExpression: 'MarriageBonusOrPenalty = Tax_MFJ − (Tax_Single1 + Tax_Single2) | Tax = Σ(bracket_rate × bracket_income for each bracket) − credits | positive = penalty, negative = bonus',
    lastVerified: '2026-01-15',
    relatedIds: ['income-tax-calculator', 'estate-tax-calculator', 'capital-gains-tax-calculator'],
    loader: () => import('../finance/marriage-tax/index'),
  },
  {
    id: 'pension-calculator',
    title: 'Pension Calculator — Contribution Growth Projection & 4% Rule',
    shortTitle: 'Pension Calculator',
    description: 'Project your pension balance from now through retirement. See your projected balance, inflation-adjusted value, and 4% Rule monthly payout with a free PDF.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Retirement',
    seoKeywords: ['pension calculator', 'pension projection calculator', 'retirement savings calculator', 'pension balance calculator', '4 percent rule calculator', '4% rule pension calculator', 'pension growth calculator', 'monthly contribution pension calculator', 'download pension report'],
    schema: 'both',
    mathSolverExpression: 'FV = PV × (1+r)^n + PMT × ((1+r)^n − 1)/r | withdrawal_annual = FV × 0.04 | monthly_payout = withdrawal_annual / 12 | inflation_adjusted = FV / (1+inflation)^n',
    lastVerified: '2026-01-15',
    relatedIds: ['rmd-calculator', '401k-calculator', 'social-security-calculator', 'fire-calculator'],
    relatedPosts: ['pension-calculator-guide', 'when-to-take-social-security'],
    loader: () => import('../finance/pension/index'),
  },
  {
    id: 'rmd-calculator',
    title: 'RMD Calculator 2026 — Required Minimum Distribution (SECURE 2.0)',
    shortTitle: 'RMD Calculator',
    description: 'Calculate your RMD using the IRS Uniform Lifetime Table with SECURE 2.0 age rules (73 for born 1951-1959, 75 for born 1960+).',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Retirement',
    seoKeywords: ['RMD calculator', 'required minimum distribution calculator', 'SECURE 2.0 RMD age', 'IRA RMD calculator 2026', 'uniform lifetime table', 'required minimum distribution 2026'],
    schema: 'both',
    mathSolverExpression: 'RMD = AccountBalance / LifeExpectancyFactor(age from IRS Uniform Lifetime Table) | 10year_projection = Σ(RMD_t for t = 1 to 10, adjusting balance each year for withdrawal and growth)',
    lastVerified: '2026-05-18',
    relatedIds: ['pension-calculator', 'roth-ira-calculator', 'ira-calculator', '401k-calculator'],
    relatedPosts: ['rmd-calculator-guide', 'when-to-take-social-security'],
    loader: () => import('../finance/rmd/index'),
  },
  {
    id: 'asset-depreciation-calculator',
    title: 'Asset Depreciation Calculator — SL, DDB & SYD Schedules',
    shortTitle: 'Depreciation Calculator',
    description: 'Compare Straight-Line, Double Declining Balance, and SYD depreciation methods. See yearly expense, accumulated depreciation, and ending book value.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Business & Accounting',
    seoKeywords: ['depreciation calculator', 'straight line depreciation calculator', 'double declining balance calculator', 'SYD depreciation calculator', 'depreciation schedule', 'asset depreciation calculator'],
    schema: 'both',
    mathSolverExpression: 'SL = (Cost − Salvage) / Life | DDB = BookValue × (2/Life) | SYD = (Cost − Salvage) × (RemainingLife / Σ(years_digits)) | book_value = Cost − accumulated_depreciation',
    lastVerified: '2026-04-01',
    relatedIds: ['depreciation-calculator', 'business-loan-calculator', 'payback-period-calculator'],
    loader: () => import('../finance/asset-depreciation/index'),
  },
  {
    id: 'business-loan-calculator',
    title: 'Business Loan Calculator — DSCR, Payments & Full Amortization',
    shortTitle: 'Business Loan Calculator',
    description: 'Calculate monthly payments, DSCR ratio, origination fees, and cash disbursed. Enter NOI to see lender approval likelihood with a full amortization schedule.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Business & Accounting',
    seoKeywords: ['business loan calculator', 'DSCR calculator', 'debt service coverage ratio calculator', 'SBA loan calculator', 'business loan payment calculator', 'business loan amortization'],
    schema: 'both',
    mathSolverExpression: 'M = P × r(1+r)^n / ((1+r)^n − 1) | total_funded = loan_amount − origination_fees | DSCR = monthly_NOI / monthly_debt_service | higher DSCR means stronger approval likelihood',
    lastVerified: '2026-04-01',
    relatedIds: ['loan-calculator', 'personal-loan-calculator', 'irr-calculator', 'commission-calculator'],
    relatedPosts: ['business-loan-guide'],
    loader: () => import('../finance/business-loan/index'),
  },
  {
    id: 'debt-consolidation-calculator',
    title: 'Debt Consolidation Calculator — Is It Worth It? — Calculator',
    shortTitle: 'Debt Consolidation',
    description: 'Compare your current debt path vs. consolidating into a personal loan — including origination fees. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Debt Management',
    seoKeywords: ['debt consolidation calculator', 'should i consolidate my debt', 'personal loan vs credit card', 'debt consolidation savings', 'loan consolidation calculator', 'is debt consolidation worth it'],
    schema: 'both',
    mathSolverExpression: 'consolidated_payment = new_loan_P × r(1+r)^n / ((1+r)^n − 1) | current_total_payments = Σ(existing_minimum_payments) | monthly_savings = current_total − consolidated_payment | total_interest_saved = existing_interest − new_interest',
    lastVerified: '2026-01-15',
    relatedIds: ['debt-payoff-calculator', 'credit-card-payoff-calculator', 'student-loan-calculator', 'personal-loan-calculator'],
    relatedPosts: ['debt-consolidation-guide', 'credit-card-debt-payoff-guide'],
    loader: () => import('../finance/debt-consolidation/index'),
  },
  {
    id: 'student-loan-calculator',
    title: 'Student Loan Calculator — With In-School Interest & Capitalization',
    shortTitle: 'Student Loan Calculator',
    description: 'Calculate your post-graduation monthly payment and lifetime loan cost. Toggle between subsidized and unsubsidized loans to see the exact impact of.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Debt Management',
    seoKeywords: ['student loan calculator', 'student loan payment calculator', 'subsidized vs unsubsidized loan', 'student loan capitalized interest', 'federal student loan calculator', 'student loan payoff calculator'],
    schema: 'both',
    mathSolverExpression: 'P_graduation = P × (1 + r_monthly)^months_in_school (for unsubsidized) | M = P_graduation × r(1+r)^n / ((1+r)^n − 1) | total_cost = Σ(all_payments over loan_term)',
    relatedPosts: ['compound-interest-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['debt-consolidation-calculator', 'debt-payoff-calculator', 'college-cost-calculator'],
    loader: () => import('../finance/student-loan/index'),
  },
  {
    id: 'bond-calculator',
    title: 'Bond Calculator — Yield to Maturity (YTM) & Pricing',
    shortTitle: 'Bond Calculator (YTM)',
    description: 'Calculate Yield to Maturity for any bond from face value, coupon rate, market price, and years to maturity. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Investing',
    seoKeywords: ['bond calculator', 'yield to maturity calculator', 'YTM calculator', 'bond price calculator', 'bond yield calculator', 'current yield calculator', 'bond discount premium calculator'],
    schema: 'both',
    mathSolverExpression: 'YTM ≈ (C + (FV − P)/n) / ((FV + P)/2) | CurrentYield = Annual_Coupon / Market_Price | Bond_Price = Σ(C_t/(1+YTM)^t) + FV/(1+YTM)^n | premium if Price > FV, discount if Price < FV',
    lastVerified: '2026-01-15',
    relatedIds: ['average-return-calculator', 'mutual-fund-calculator', 'future-value-calculator'],
    loader: () => import('../finance/bond-calculator/index'),
  },
  {
    id: 'roth-ira-calculator',
    title: 'Roth IRA Calculator 2026 — Tax-Free Growth & Contribution Limits',
    shortTitle: 'Roth IRA Calculator',
    description: 'Project your Roth IRA balance with 2026 contribution limits ($7,500 base, $8,600 for 50+). See tax-free growth, contributions vs.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Retirement',
    seoKeywords: ['roth ira calculator', 'roth ira contribution limits 2026', 'roth ira growth calculator', 'roth ira vs traditional ira', 'roth ira tax savings calculator', 'roth ira retirement calculator'],
    schema: 'both',
    mathSolverExpression: 'FV = PMT × ((1+r)^n − 1)/r + PV × (1+r)^n | total_contributions = PMT × n | tax_free_earnings = FV − total_contributions | contribution_limit = $7,500 ($8,600 if age 50+) | tax_advantage = Roth_FV − Traditional_FV_after_tax',
    lastVerified: '2026-01-15',
    relatedIds: ['401k-calculator', 'social-security-calculator', 'ira-calculator', 'fire-calculator'],
    relatedPosts: ['401k-retirement-savings-guide', 'roth-ira-vs-traditional-ira-guide'],
    loader: () => import('../finance/roth-ira/index'),
  },
  {
    id: 'rent-affordability-calculator',
    title: 'Rent Affordability Calculator — How Much Rent Can I Afford?',
    shortTitle: 'Rent Affordability',
    description: 'Find your maximum safe rent based on income using the 30% Rule, 40x Rule (NYC), or conservative 25% rule. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['rent affordability calculator', 'how much rent can i afford', '30 percent rule rent', '40x rent rule', 'rent calculator income', 'apartment affordability calculator'],
    schema: 'both',
    mathSolverExpression: 'max_rent_30pct = monthly_income × 0.30 | max_rent_40x = annual_income / 40 | max_rent_25pct = monthly_income × 0.25 | remaining_cash = monthly_income − max_rent − monthly_debt_payments',
    lastVerified: '2026-01-15',
    relatedIds: ['house-affordability-calculator', 'budget-calculator', 'home-affordability-calculator'],
    relatedPosts: ['realestate-rent-affordability-guide'],
    loader: () => import('../finance/rent-affordability/index'),
  },
  {
    id: 'estate-tax-calculator',
    title: 'Estate Tax Calculator 2025 — Federal & State — Free Online Calculator',
    shortTitle: 'Estate Tax Calculator',
    description: 'Estimate federal estate tax based on your gross estate, deductions, and filing status. Free online calculator with formula guide and step-by-step results.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Taxes',
    seoKeywords: ['estate tax calculator', 'federal estate tax calculator', 'estate tax exemption 2025', 'estate tax by state', 'inheritance tax calculator', 'how much estate tax will i owe', 'california income tax calculator 2026', 'new york tax calculator 2026', 'texas sales tax calculator', '2026 tax calculator'],
    schema: 'both',
    mathSolverExpression: 'taxable_estate = gross_estate − deductions − exemption_amount($13.99M federal 2025) | federal_tax = taxable_estate × federal_rate | state_tax = taxable_estate × state_rate (if applicable) | total_tax = federal + state',
    lastVerified: '2026-01-15',
    relatedIds: ['income-tax-calculator', 'marriage-tax-calculator', 'capital-gains-tax-calculator'],
    loader: () => import('../finance/estate-tax/index'),
  },
  {
    id: 'social-security-calculator',
    title: 'Social Security Calculator — Age 62 vs 67 vs 70 (2025 Bend Points)',
    shortTitle: 'Social Security Calculator',
    description: 'Estimate your monthly Social Security benefit using the official PIA bend point formula. Free online calculator with formula guide and step-by-step results.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Retirement',
    seoKeywords: ['social security calculator', 'social security benefits calculator', 'when to claim social security', 'social security age 62 vs 67 vs 70', 'social security retirement calculator', 'ss benefit estimator', 'social security break even calculator', 'spousal benefit calculator'],
    schema: 'both',
    mathSolverExpression: 'PIA = 90% × AIME_up_to_$1,174 + 32% × AIME_$1,174_to_$7,078 + 15% × AIME_above_$7,078 | early_benefit = PIA × (1 − 5/9% × months_early_first_36 − 5/12% × months_early_beyond_36) | delayed_benefit = PIA × (1 + 0.667% × months_delayed_up_to_age_70)',
    lastVerified: '2026-05-18',
    relatedIds: ['pension-calculator', 'roth-ira-calculator', '401k-calculator', 'fire-calculator', 'rmd-calculator'],
    relatedPosts: ['how-much-do-you-need-to-retire', 'when-to-take-social-security'],
    loader: () => import('../finance/social-security/index'),
  },
  {
    id: 'annuity-payout-calculator',
    title: 'Annuity Payout Calculator — How Long Will Your Money Last?',
    shortTitle: 'Annuity Payout Calculator',
    description: 'Calculate how much monthly income a lump sum generates or how long savings will last with a given withdrawal. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Retirement',
    seoKeywords: ['annuity payout calculator', 'how long will my money last calculator', 'retirement payout calculator', 'lump sum payout calculator', '4 percent rule calculator', 'annuity withdrawal calculator', 'inflation adjusted annuity', 'drawdown calculator', 'retirement withdrawal calculator'],
    schema: 'both',
    mathSolverExpression: 'PMT = PV × r / (1 − (1+r)^(−n)) | n = ln(PMT / (PMT − PV×r)) / ln(1+r) | infinite_if: withdrawal ≤ interest_earned | inflation_adjusted_PMT = PMT / (1+0.03/m)^n',
    lastVerified: '2026-05-18',
    relatedIds: ['pension-calculator', 'fire-calculator', 'retirement-calculator', 'social-security-calculator'],
    relatedPosts: ['pension-calculator-guide', 'how-much-do-you-need-to-retire'],
    loader: () => import('../finance/annuity-payout/index'),
  },
  {
    id: 'debt-payoff-calculator',
    title: 'Debt Payoff Calculator — Snowball vs. Avalanche Strategy',
    shortTitle: 'Debt Payoff (Snowball/Avalanche)',
    description: 'Compare Debt Snowball vs. Debt Avalanche strategies with a side-by-side timeline and per-card payoff dates. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Debt Management',
    seoKeywords: ['debt payoff calculator', 'debt snowball calculator', 'debt avalanche calculator', 'credit card payoff calculator', 'snowball vs avalanche', 'fastest way to pay off debt', 'debt payoff strategy comparison', 'multiple debt payoff calculator'],
    schema: 'both',
    mathSolverExpression: 'snowball: pay_minimum_on_all_except_smallest_balance | avalanche: pay_minimum_on_all_except_highest_APR | total_interest = Σ(monthly_interest for each debt under strategy) | months_to_debt_free = earliest month where all balances ≤ 0',
    lastVerified: '2026-05-18',
    relatedIds: ['debt-consolidation-calculator', 'credit-card-payoff-calculator', 'student-loan-calculator'],
    relatedPosts: ['credit-card-debt-payoff-guide', 'debt-consolidation-guide'],
    loader: () => import('../finance/debt-payoff/index'),
  },
  {
    id: '401k-calculator',
    title: '401(k) Calculator — Retirement Projection with Employer Match',
    shortTitle: '401(k) Calculator',
    description: 'Project your 401(k) balance with salary growth and employer matching. See contribution breakdowns, compounding returns, and monthly retirement income.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    features: { aiProofWizard: true },
    seoKeywords: ['401k calculator', '401k retirement calculator', 'employer match calculator', '401k employer match', 'retirement 401k projection', '401k growth calculator'],
    schema: 'both',
    mathSolverExpression: 'FV = employee_contributions_total × ((1+r)^n − 1)/r + employer_match_total × ((1+r)^n − 1)/r | employer_match_total = salary × match_pct up to match_limit per year | balance_breakdown = employee + employer + earnings',
    lastVerified: '2026-04-01',
    relatedIds: ['roth-ira-calculator', 'ira-calculator', 'social-security-calculator', 'retirement-calculator'],
    relatedPosts: ['401k-retirement-savings-guide', 'roth-ira-vs-traditional-ira-guide'],
    loader: () => import('../finance/401k/index'),
  },
  {
    id: 'interest-rate-calculator',
    title: 'Interest Rate Calculator — Find the Rate You Were Charged',
    shortTitle: 'Interest Rate Calculator',
    description: 'Calculate the effective interest rate from a starting principal and final amount. Supports compound and simple interest across any time period.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['interest rate calculator', 'effective interest rate calculator', 'find interest rate', 'reverse interest calculator', 'compound interest rate calculator', 'ear calculator'],
    schema: 'both',
    mathSolverExpression: 'r_compound = (FV / PV)^(1/t) − 1 | r_simple = (FV / PV − 1) / t | effective_annual_rate = (1 + r_nominal/n)^n − 1 | solve for rate by isolating the rate variable in the time value of money equation',
    relatedPosts: ['compound-interest-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['interest-calculator', 'compound-interest-calculator', 'tvm-calculator'],
    loader: () => import('../finance/interest-rate/index'),
  },
  {
    id: 'sales-tax-calculator',
    title: 'Sales Tax Calculator — Add Tax or Extract Tax — Free Online Calculator',
    shortTitle: 'Sales Tax Calculator',
    description: 'Add sales tax to a price or extract the tax from a total amount collected. The "Extract Tax" mode is essential for e-commerce and retail business owners.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['sales tax calculator', 'tax calculator', 'reverse sales tax calculator', 'extract sales tax', 'sales tax backwards calculator', 'how much is sales tax', 'california income tax calculator 2026', 'new york tax calculator 2026', 'texas sales tax calculator', '2026 tax calculator'],
    schema: 'both',
    mathSolverExpression: 'price_with_tax = net_price × (1 + tax_rate) | tax_extracted = gross_total − gross_total / (1 + tax_rate) | net_price_from_gross = gross_total / (1 + tax_rate) | tax_amount = gross_total − net_price',
    lastVerified: '2026-01-15',
    relatedIds: ['vat-calculator', 'income-tax-calculator', 'discount-calculator'],
    loader: () => import('../finance/sales-tax/index'),
  },
  {
    id: 'house-affordability-calculator',
    title: 'House Affordability Calculator — How Much Can I Afford?',
    shortTitle: 'House Affordability',
    description: 'Find out the maximum home price you can afford based on your income, debts, and down payment. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Real Estate Finance',
    relatedIds: ['rent-vs-buy-calculator', 'rent-affordability-calculator', 'home-affordability-calculator', 'dti-ratio-calculator'],
    seoKeywords: ['house affordability calculator', 'how much house can i afford', 'home affordability calculator', 'mortgage affordability calculator', 'what house can i afford', 'home buying budget calculator'],
    schema: 'both',
    mathSolverExpression: 'max_home_price_front = (monthly_income × 0.28) × 12 × loan_term / mortgage_factor | max_home_price_back = (monthly_income × 0.36 − debts) × 12 × loan_term / mortgage_factor | overall_max = min(front_end_max, back_end_max)',
    lastVerified: '2026-01-15',
    relatedPosts: ['fha-loan-requirements-mip-down-payment-qualifying', 'how-much-house-can-i-afford', 'rent-vs-buy-analysis'],
    loader: () => import('../finance/house-affordability/index'),
  },
  {
    id: 'savings-calculator',
    title: 'Savings Calculator — Future Balance & Monthly Goal Planner',
    shortTitle: 'Savings Calculator',
    description: 'Calculate how much your savings will grow or how much to save monthly to reach a goal. Free online calculator with formula guide and step-by-step results.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    features: { aiProofWizard: true },
    relatedPosts: ['savings-calculator-complete-guide', 'compound-savings-why-starting-early-matters'],
    seoKeywords: ['savings calculator', 'savings goal calculator', 'how much to save per month', 'savings growth calculator', 'monthly savings calculator', 'high yield savings calculator'],
    schema: 'both',
    mathSolverExpression: 'FV = PV × (1+r)^n + PMT × ((1+r)^n − 1)/r | monthly_goal = (target_FV − PV × (1+r)^n) / (((1+r)^n − 1)/r) | total_saved = PV + Σ(PMT) | interest_earned = FV − total_saved',
    lastVerified: '2026-01-15',
    relatedIds: ['cd-calculator', 'budget-calculator', 'investment-calculator'],
    loader: () => import('../finance/savings/index'),
  },
  {
    id: 'tvm-calculator',
    title: 'TVM Calculator — Time Value of Money (HP 12C / TI BA II+ Compatible)',
    shortTitle: 'TVM Finance Calculator',
    description: 'Professional-grade TVM solver matching the HP 12C and TI BA II+ financial calculators. Free online calculator with formula guide and step-by-step results.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['tvm calculator', 'time value of money calculator', 'finance calculator', 'present value calculator', 'future value calculator', 'pv fv calculator', 'hp 12c calculator', 'ba ii plus calculator', 'annuity due calculator'],
    schema: 'both',
    mathSolverExpression: 'FV = PV×(1+r)^n + PMT×((1+r)^n − 1)/r | PV = FV/(1+r)^n + PMT×(1 − (1+r)^(−n))/r | solved algebraically for FV, PV, PMT, and N | Newton-Raphson iteration for Rate with decimal.js precision',
    lastVerified: '2026-05-18',
    relatedIds: ['present-value-calculator', 'future-value-calculator', 'interest-rate-calculator', 'loan-calculator', 'amortization-calculator'],
    relatedPosts: ['pension-calculator-guide'],
    loader: () => import('../finance/tvm-calculator/index'),
  },
  {
    id: 'mortgage-payoff-calculator',
    title: 'Mortgage Payoff Calculator — Pay Off Your Mortgage Early',
    shortTitle: 'Mortgage Payoff',
    description: 'Find your new debt-free date and total interest saved with extra monthly payments, yearly lump sums, or a one-time principal payment.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['mortgage payoff calculator', 'pay off mortgage early', 'extra mortgage payment calculator', 'mortgage payoff date calculator', 'how to pay off mortgage faster', 'mortgage interest savings', 'california mortgage calculator', 'texas mortgage calculator', 'florida mortgage calculator'],
    schema: 'both',
    mathSolverExpression: 'M = P × r(1+r)^n / ((1+r)^n − 1) | with_extra: new_payoff_date = find earliest month where balance ≤ 0 given M + extra_payment each month | interest_saved = total_interest_original − total_interest_with_extra',
    lastVerified: '2026-01-15',

    relatedPosts: ['mortgage-payoff-complete-guide', 'extra-mortgage-payment-strategies'],
    relatedIds: ['mortgage-amortization-calculator', 'amortization-calculator', 'refinance-calculator'],
    loader: () => import('../finance/mortgage-payoff/index'),
  },
  {
    id: 'mortgage-comparison-calculator',
    title: 'Mortgage Comparison Calculator — 15-Year vs 30-Year with PMI, Tax',
    shortTitle: '15-Year vs 30-Year Mortgage',
    description: 'Compare 15-year vs 30-year mortgages side by side with different rates, PMI, property taxes, and insurance. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Mortgages',
    seoKeywords: ['mortgage comparison calculator', '15 year vs 30 year mortgage calculator', '15 year vs 30 year mortgage comparison', 'mortgage term comparison calculator', 'should I get a 15 year or 30 year mortgage', 'mortgage PMI calculator', 'mortgage with taxes and insurance calculator', 'compare mortgage terms', 'fixed rate mortgage comparison', 'california mortgage calculator', 'texas mortgage calculator', 'florida mortgage calculator'],
    schema: 'both',
    mathSolverExpression: 'M = P × r(1+r)^n / ((1+r)^n − 1) | monthlyCost = M + propertyTax/12 + insurance/12 + PMI/12 | totalCost = monthlyCost × n | savings = totalCost30 − totalCost15 | PMI_applies if downPayment < 20%',
    lastVerified: '2026-01-15',
    relatedIds: ['mortgage-payoff-calculator', 'mortgage-amortization-calculator', 'refinance-calculator', 'fha-loan-calculator', 'va-mortgage-calculator', 'house-affordability-calculator'],
    loader: () => import('../finance/mortgage-comparison/index'),
  },
  {
    id: 'texas-mortgage-calculator',
    title: 'Texas Mortgage Calculator — Rates, Property Tax & Homestead Exemption',
    shortTitle: 'Texas Mortgage Calculator',
    description: 'Calculate your Texas mortgage payment including property taxes (~1.8%), PMI, and the Texas Homestead Exemption. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Mortgages',
    seoKeywords: ['texas mortgage calculator', 'texas mortgage rates', 'texas property tax calculator', 'texas home affordability calculator', 'texas homestead exemption', 'first time home buyer texas', 'texas mortgage payment calculator', 'houston mortgage calculator', 'dallas mortgage calculator', 'austin mortgage calculator', 'san antonio mortgage calculator', 'california mortgage calculator', 'florida mortgage calculator'],
    schema: 'both',
    mathSolverExpression: 'M = P x r(1+r)^n / ((1+r)^n - 1) | trueMonthlyCost = M + propertyTax/12 + PMI/12 | Texas Homestead Exemption reduces school tax base by $100,000',
    lastVerified: '2026-05-18',
    relatedIds: ['mortgage-payoff-calculator', 'mortgage-comparison-calculator', 'mortgage-amortization-calculator', 'refinance-calculator', 'house-affordability-calculator', 'new-york-mortgage-calculator'],
    relatedPosts: ['texas-mortgage-guide', 'mortgage-refinance-guide'],
    loader: () => import('../finance/texas-mortgage-calculator/index'),
  },
  {
    id: 'new-york-mortgage-calculator',
    title: 'New York Mortgage Calculator — Property Tax, STAR & SONYMA',
    shortTitle: 'New York Mortgage Calculator',
    description: 'Calculate your New York mortgage payment including property taxes (~1.6%), STAR school tax exemption, and mortgage recording tax closing costs.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Mortgages',
    seoKeywords: ['new york mortgage calculator', 'ny mortgage calculator', 'new york property tax calculator', 'ny star exemption', 'sonyma mortgage', 'new york mortgage recording tax', 'nyc mortgage calculator', 'california mortgage calculator', 'texas mortgage calculator', 'florida mortgage calculator'],
    schema: 'both',
    mathSolverExpression: 'M = P × r(1+r)^n / ((1+r)^n − 1) | trueMonthlyCost = M + propertyTax/12 + PMI/12 | STAR exemption reduces school tax base',
    lastVerified: '2026-05-18',
    relatedIds: ['mortgage-payoff-calculator', 'texas-mortgage-calculator', 'refinance-calculator', 'house-affordability-calculator'],
    relatedPosts: ['new-york-mortgage-guide'],
    loader: () => import('../finance/new-york-mortgage-calculator/index'),
  },
  {
    id: 'california-mortgage-calculator',
    title: 'California Mortgage Calculator — Prop 13, CalHFA & Mello-Roos',
    shortTitle: 'California Mortgage Calculator',
    description: 'Estimate CA mortgage payments with Prop 13 taxes, Mello-Roos, and PMI. Includes CalHFA down payment help and state income tax impact.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Mortgages',
    seoKeywords: ['california mortgage calculator', 'ca mortgage calculator', 'california property tax calculator', 'prop 13 calculator', 'mello roos calculator', 'calhfa calculator', 'los angeles mortgage calculator', 'san francisco mortgage calculator', 'san diego mortgage calculator', 'texas mortgage calculator', 'florida mortgage calculator'],
    schema: 'both',
    mathSolverExpression: 'M = P × r(1+r)^n / ((1+r)^n − 1) | trueMonthlyCost = M + propertyTax/12 + PMI/12 | Prop 13 limits tax to ~1% of assessed value',
    lastVerified: '2026-04-01',
    relatedIds: ['mortgage-payoff-calculator', 'texas-mortgage-calculator', 'new-york-mortgage-calculator', 'refinance-calculator'],
    loader: () => import('../finance/california-mortgage-calculator/index'),
  },
  {
    id: 'income-tax-calculator',
    title: 'Income Tax Calculator 2025 — Federal, FICA & State',
    shortTitle: 'Income Tax Calculator',
    description: 'Estimate your 2025 federal income tax, FICA, and state tax. See your marginal vs. effective tax rate, the exact bracket breakdown, and estimated take-home.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['income tax calculator', 'tax calculator 2025', 'federal income tax calculator', 'take home pay calculator', 'paycheck tax calculator', 'effective tax rate calculator', 'california income tax calculator 2026', 'new york tax calculator 2026', 'texas sales tax calculator', '2026 tax calculator'],
    schema: 'both',
    mathSolverExpression: 'taxable_income = gross − standard_deduction | federal_tax = Σ(bracket_rate × bracket_income for each bracket) | FICA = wages × 0.0765 (up to SS wage base) | state_tax = taxable_income × state_rate | effective_rate = total_tax / gross_income × 100%',
    lastVerified: '2026-01-15',
    relatedIds: ['capital-gains-tax-calculator', 'self-employment-tax-calculator', 'marriage-tax-calculator', 'salary-take-home'],
    relatedPosts: ['capital-gains-tax-guide', 'commission-calculator-guide', 'income-tax-guide', 'paycheck-deductions-guide', 'salary-negotiation-guide', 'self-employment-tax-guide'],
    loader: () => import('../finance/income-tax/index'),
  },
  {
    id: 'salary-calculator',
    title: 'Salary Calculator 2026 — Paycheck Converter with Take-Home Pay',
    shortTitle: 'Salary Calculator',
    description: 'Convert any salary between hourly, daily, weekly, bi-weekly, semi-monthly, monthly, and annual. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['salary calculator', 'paycheck calculator', 'hourly to salary calculator', 'salary to hourly calculator', 'annual to monthly salary', 'bi-weekly pay calculator', 'california salary calculator 2026', 'new york paycheck calculator', 'texas salary calculator', 'take home pay calculator'],
    schema: 'both',
    mathSolverExpression: 'annual = hourly × hours_per_week × 52 | hourly = annual / (hours_per_week × 52) | weekly = annual / 52 | biweekly = annual / 26 | semi_monthly = annual / 24 | monthly = annual / 12 | net = annual − federal_tax − FICA − state_tax',
    lastVerified: '2026-05-18',
    relatedIds: ['salary-take-home', 'paycheck-calculator', 'salary-to-hourly-calculator', 'salary-hourly-calculator', 'income-tax-calculator'],
    relatedPosts: ['commission-calculator-guide', 'paycheck-deductions-guide', 'salary-negotiation-guide'],
    loader: () => import('../finance/salary-calculator/index'),
  },
  {
    id: 'retirement-calculator',
    title: 'Retirement Savings Calculator — 401k & IRA Growth — Calculator',
    shortTitle: 'Retirement Calculator',
    description: 'Find out if you are on track for retirement. Enter your age, current savings, monthly contributions, and target retirement age to see your projected nest.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['retirement calculator', 'retirement savings calculator', 'how much do i need to retire', 'retirement planning calculator', '4% rule calculator', 'nest egg calculator'],
    schema: 'both',
    mathSolverExpression: 'FV = PV × (1+r)^n + PMT × ((1+r)^n − 1)/r | retirement_income = FV × 0.04 | income_gap = desired_annual_income − retirement_income | target_savings = desired_income / 0.04',
    lastVerified: '2026-01-15',
    relatedIds: ['401k-calculator', 'fire-calculator', 'annuity-payout-calculator', 'pension-calculator'],
    relatedPosts: ['401k-retirement-savings-guide', 'how-much-do-you-need-to-retire', 'pension-calculator-guide', 'roth-ira-vs-traditional-ira-guide', 'when-to-take-social-security'],
    loader: () => import('../finance/retirement/index'),
  },
  {
    id: 'amortization-calculator',
    title: 'Amortization Calculator with Extra Payments — Free Online Calculator',
    shortTitle: 'Amortization Calculator',
    description: 'See the full amortization schedule for any loan and calculate exactly how much time and interest extra monthly or annual payments save.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['amortization calculator', 'loan amortization schedule', 'extra payment calculator', 'pay off loan early calculator', 'amortization table', 'loan payoff calculator'],
    schema: 'both',
    mathSolverExpression: 'M = P × r(1+r)^n / ((1+r)^n − 1) | each_period: interest = balance × r, principal = M − interest, new_balance = balance − principal | with_extra: new_balance = balance − principal − extra_payment',
    lastVerified: '2026-01-15',
    relatedIds: ['repayment-calculator', 'mortgage-amortization-calculator', 'loan-calculator'],
    relatedPosts: ['amortization-schedules-extra-payments-save-thousands', 'business-loan-guide', 'canadian-mortgage-calculator-guide', 'how-loan-payments-work', 'mortgage-refinance-guide', 'pay-off-mortgage-early-strategies-that-work'],
    loader: () => import('../finance/amortization/index'),
  },
  {
    id: 'investment-calculator',
    title: 'Investment Calculator — Compound Growth with Variance Scenarios',
    shortTitle: 'Investment Calculator',
    description: 'Project the future value of any investment with regular contributions. See three return scenarios (expected, optimistic, pessimistic) and a breakdown of.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Investing',
    features: { aiProofWizard: true },
    relatedPosts: ['investment-calculator-guide', 'investment-return-scenarios-explained'],
    seoKeywords: ['investment calculator', 'future value calculator', 'investment growth calculator', 'investment return calculator', 'stock market calculator', 'portfolio calculator', 'compound interest calculator', 'monthly investment calculator'],
    schema: 'both',
    mathSolverExpression: 'FV = PV × (1+r)^n + PMT × ((1+r)^n − 1)/r | total_contributions = PV + PMT × n | market_returns = FV − total_contributions | scenarios: expected, optimistic(r+variance), pessimistic(r−variance)',
    lastVerified: '2026-05-18',
    relatedIds: ['compound-interest-calculator', 'future-value-calculator', 'roi-calculator', 'average-return-calculator', 'retirement-calculator'],
    loader: () => import('../finance/investment/index'),
  },
  {
    id: 'currency-calculator',
    title: 'Currency Converter — Live Exchange Rates for 30+ Global Currencies',
    shortTitle: 'Currency Converter',
    description: 'Convert between 30+ currencies using live ECB exchange rates with mid-market pricing. See exact rate, timestamp, inverse rate, and bank spread comparison.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['currency converter', 'currency calculator', 'exchange rate calculator', 'usd to eur', 'forex calculator', 'live currency rates'],
    schema: 'both',
    mathSolverExpression: 'converted_amount = base_amount × exchange_rate | inverse_rate = 1 / exchange_rate | cross_rate = currencyA_rate / currencyB_rate | timestamp tracks ECB publication time for audit trail',
    lastVerified: '2026-01-15',
    relatedIds: ['inflation-calculator', 'vat-calculator', 'eth-gas-fee-calculator'],
    loader: () => import('../finance/currency/index'),
  },
  {
    id: 'inflation-calculator',
    title: 'Inflation Calculator — Historical CPI Data — Free Online Calculator',
    shortTitle: 'Inflation Calculator',
    description: 'Calculate the inflation-adjusted value of any dollar amount from 1913 to today using official US CPI data from the Bureau of Labor Statistics.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['inflation calculator', 'cpi calculator', 'purchasing power calculator', 'historical inflation calculator', 'dollar value calculator', 'consumer price index calculator'],
    schema: 'both',
    mathSolverExpression: 'adjusted_value = original_value × (CPI_current / CPI_original) | cumulative_inflation = (CPI_current − CPI_original) / CPI_original × 100% | avg_annual_rate = (CPI_current / CPI_original)^(1/years) − 1',
    lastVerified: '2026-01-15',
    relatedIds: ['savings-calculator', 'cd-calculator', 'investment-calculator'],
    relatedPosts: ['inflation-impact-guide'],
    loader: () => import('../finance/inflation/index'),
  },
  {
    id: 'loan-calculator',
    title: 'Loan Calculator — Monthly Payments, APR & Amortization',
    shortTitle: 'Loan Calculator',
    description: 'Calculate monthly payments, total interest, and total cost for any personal or business loan. Includes a full amortization schedule with extra payment savings.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['loan calculator', 'personal loan calculator', 'monthly payment calculator', 'loan amortization calculator', 'loan payment calculator', 'loan interest calculator'],
    schema: 'both',
    mathSolverExpression: 'M = P × r(1+r)^n / ((1+r)^n − 1) | total_interest = M × n − P | total_cost = P + total_interest | amortization: each month interest = balance × r, principal = M − interest',
    lastVerified: '2026-01-15',
    relatedIds: ['personal-loan-calculator', 'amortization-calculator', 'business-loan-calculator', 'repayment-calculator'],
    relatedPosts: ['amortization-schedules-extra-payments-save-thousands', 'auto-loan-financing-guide', 'business-loan-guide', 'how-loan-payments-work', 'pay-off-mortgage-early-strategies-that-work', 'personal-loan-comparison-origination-fees-true-cost'],
    loader: () => import('../finance/loan-calculator/index'),
  },
  {
    id: 'personal-loan-calculator',
    title: 'Personal Loan Calculator — With Origination Fee & True Cost Breakdown',
    shortTitle: 'Personal Loan Calculator',
    description: 'Calculate your exact monthly payment, cash received, and true total cost with origination fees. Choose fee deducted from proceeds or added to balance.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['personal loan calculator', 'personal loan origination fee', 'loan payment calculator', 'personal loan amortization', 'personal loan total cost', 'actual cash received personal loan'],
    schema: 'both',
    mathSolverExpression: 'cash_received = loan_amount − origination_fee | M = loan_amount × r(1+r)^n / ((1+r)^n − 1) | total_cost = M × n + origination_fee | true_APR computed from net_proceeds and payment_stream using iterative solver',
    lastVerified: '2026-01-15',
    relatedIds: ['loan-calculator', 'apr-calculator', 'business-loan-calculator', 'debt-consolidation-calculator'],
    relatedPosts: ['credit-card-debt-payoff-guide', 'debt-consolidation-guide', 'how-loan-payments-work', 'personal-loan-comparison-origination-fees-true-cost'],
    loader: () => import('../finance/personal-loan/index'),
  },
  {
    id: 'budget-calculator',
    title: 'Budget Calculator — 50/30/20 Rule (Needs, Wants & Savings)',
    shortTitle: 'Budget Calculator',
    description: 'Build your monthly budget with the 50/30/20 framework. See your actual spending vs. ideal split across Needs, Wants, and Savings categories with a donut.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['budget calculator', '50 30 20 rule calculator', 'monthly budget calculator', 'budget planner', '50/30/20 budget', 'household budget calculator'],
    schema: 'both',
    mathSolverExpression: 'ideal_needs = income × 0.50 | ideal_wants = income × 0.30 | ideal_savings = income × 0.20 | actual_pct_needs = actual_needs / income | variance = actual_pct − ideal_pct for each category | balance = income − total_expenses',
    lastVerified: '2026-01-15',
    relatedIds: ['savings-calculator', 'net-worth-calculator', 'rent-affordability-calculator'],
    relatedPosts: ['50-30-20-budget-guide', 'net-worth-guide'],
    loader: () => import('../finance/budget-calculator/index'),
  },
  {
    id: 'irr-calculator',
    title: 'IRR Calculator — Internal Rate of Return with NPV (Free)',
    shortTitle: 'IRR Calculator',
    description: 'Calculate IRR and NPV for any investment with multiple cash flows over time. Add up to 10 years of projected cash flows and benchmark against S&P 500 and.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Business & Accounting',
    seoKeywords: ['IRR calculator', 'internal rate of return calculator', 'NPV calculator', 'net present value calculator', 'investment return calculator', 'IRR formula'],
    schema: 'both',
    mathSolverExpression: 'NPV = Σ(CF_t / (1+r)^t for t=0 to n) | IRR = the rate r where NPV = 0, solved iteratively | profitability = IRR > cost_of_capital | NPV_benchmark = NPV at market_return_rate',
    lastVerified: '2026-01-15',
    relatedIds: ['payback-period-calculator', 'roi-calculator', 'average-return-calculator', 'business-loan-calculator'],
    loader: () => import('../finance/irr-calculator/index'),
  },
  {
    id: 'apr-calculator',
    title: 'APR Calculator — True Annual Percentage Rate (vs. Interest Rate)',
    shortTitle: 'APR Calculator',
    description: 'Calculate the true APR of any loan by factoring in origination fees, closing costs, and other upfront charges. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['APR calculator', 'annual percentage rate calculator', 'interest rate vs APR', 'true cost of loan', 'APR vs interest rate', 'mortgage APR calculator'],
    schema: 'both',
    mathSolverExpression: 'APR ≈ 2 × n × total_fees / (P × (n+1)) + stated_rate | APR_exact = rate that makes PV of all payments equal net_proceeds | net_proceeds = P − total_fees | cost_difference = APR − stated_rate as percentage points',
    lastVerified: '2026-01-15',
    relatedIds: ['personal-loan-calculator', 'interest-rate-calculator', 'loan-calculator'],
    relatedPosts: ['personal-loan-comparison-origination-fees-true-cost'],
    loader: () => import('../finance/apr-calculator/index'),
  },
  {
    id: 'va-mortgage-calculator',
    title: 'VA Mortgage Calculator — VA Funding Fee, No PMI Payment Breakdown',
    shortTitle: 'VA Loan Calculator',
    description: 'Calculate your VA loan payment including the VA Funding Fee for first vs. subsequent use. Free online calculator with formula guide and step-by-step results.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Mortgages',
    seoKeywords: ['VA mortgage calculator', 'VA loan calculator', 'VA funding fee calculator', 'VA loan payment calculator', 'military home loan calculator', 'VA loan no PMI', 'california va loan calculator', 'texas va mortgage calculator'],
    schema: 'both',
    mathSolverExpression: 'funding_fee = loan_amount × VA_fee_rate(first_use: 2.15% regular, 2.4% reserves | subsequent: 3.3%) | disability_exemption = 0% fee | total_loan = loan + funding_fee_if_rolled_in | M = total_loan × r(1+r)^n / ((1+r)^n − 1)',
    relatedPosts: ['investment-growth-calculator-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['fha-loan-calculator', 'refinance-calculator', 'mortgage-amortization-calculator', 'house-affordability-calculator'],
    loader: () => import('../finance/va-mortgage/index'),
  },
  {
    id: 'heloc-calculator',
    title: 'HELOC Calculator — How Much Home Equity Can You Borrow?',
    shortTitle: 'HELOC Calculator',
    description: 'Calculate your maximum HELOC based on home value, mortgage balance, and CLTV limit (80-90%). Free online calculator with formula guide and step-by-step results.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Home Equity',
    seoKeywords: ['HELOC calculator', 'home equity line of credit calculator', 'CLTV calculator', 'home equity calculator', 'tapable equity calculator', 'HELOC payment calculator'],
    schema: 'both',
    mathSolverExpression: 'max_heloc = home_value × CLTV_limit − existing_mortgage_balance | tapable_equity = home_value − (mortgage + max_heloc) | interest_only_payment = drawn_amount × (annual_rate / 12) | CLTV = (mortgage + heloc) / home_value',
    lastVerified: '2026-01-15',
    relatedIds: ['home-equity-loan-calculator', 'house-affordability-calculator', 'mortgage-amortization-calculator'],
    loader: () => import('../finance/heloc/index'),
  },
  {
    id: 'rent-vs-buy-calculator',
    title: 'Rent vs. Buy Calculator — Find Your Break-Even Year',
    shortTitle: 'Rent vs. Buy',
    description: 'The definitive rent vs. buy analysis. Find the exact year buying becomes cheaper than renting, accounting for appreciation, equity, PMI, down payment.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Real Estate Finance',
    seoKeywords: ['rent vs buy calculator', 'should I rent or buy calculator', 'rent vs buy break even', 'is it better to rent or buy', 'rent vs buy analysis', 'home buying vs renting'],
    schema: 'both',
    mathSolverExpression: 'buy_net_cost = Σ(monthly_ownership_costs) − equity_gained − home_appreciation + selling_costs | rent_net_cost = Σ(rent_payments) + renter_insurance | break_even_year = first year where buy_net_cost ≤ rent_net_cost | opportunity_cost = down_payment × market_return',
    lastVerified: '2026-01-15',
    relatedIds: ['home-rent-vs-buy-calculator', 'house-affordability-calculator', 'rental-property-calculator'],
    relatedPosts: ['how-much-house-can-i-afford', 'realestate-rent-affordability-guide', 'rent-vs-buy-analysis'],
    loader: () => import('../finance/rent-vs-buy/index'),
  },
  {
    id: 'present-value-calculator',
    title: 'Present Value Calculator — How Much to Invest Today for a Future Goal',
    shortTitle: 'Present Value Calculator',
    description: 'Calculate how much money you need today to reach a future financial goal. Supports all compounding frequencies with formula display, growth timeline.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Business & Accounting',
    seoKeywords: ['present value calculator', 'PV calculator', 'time value of money calculator', 'discounted cash flow calculator', 'PV formula', 'future value to present value', 'how much to invest today calculator', 'lump sum vs future payment calculator'],
    schema: 'both',
    mathSolverExpression: 'PV = FV / (1 + r/m)^(n×m) | effective_annual_rate = (1 + r/m)^m − 1 | discount_factor = PV / FV | more_frequent_compounding_requires_less_PV_today',
    relatedPosts: ['pension-calculator-guide'],
    lastVerified: '2026-05-18',
    relatedIds: ['tvm-calculator', 'future-value-calculator', 'irr-calculator', 'investment-calculator'],
    loader: () => import('../finance/present-value/index'),
  },
  {
    id: 'interest-calculator',
    title: 'Interest Calculator — Simple & Compound Interest — Calculator',
    shortTitle: 'Interest Calculator',
    description: 'Calculate simple or compound interest for any principal, rate, and time period. Supports annual, monthly, and daily time periods and all compounding.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['interest calculator', 'simple interest calculator', 'compound interest calculator', 'how much interest will i pay', 'interest rate calculator', 'loan interest calculator'],
    schema: 'both',
    mathSolverExpression: 'simple_interest = P × r × t | compound_interest = P × (1 + r/n)^(n×t) − P | total_amount = P + interest | supports annual, monthly, and daily time periods with all compounding frequencies',
    lastVerified: '2026-01-15',
    relatedIds: ['compound-interest-calculator', 'simple-interest-calculator', 'interest-rate-calculator'],
    loader: () => import('../finance/interest-calculator/index'),
  },
  {
    id: 'payment-calculator',
    title: 'Loan Payment Calculator — See Your Monthly Payment Instantly',
    shortTitle: 'Payment Calculator',
    description: 'Calculate your monthly loan payment instantly. Solve for payment, loan amount, or term. Free online calculator with formula guide and step-by-step results.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['payment calculator', 'how much can i afford to borrow', 'loan payment calculator', 'solve for loan amount', 'loan term calculator', 'monthly payment calculator'],
    schema: 'both',
    mathSolverExpression: 'PMT = P × r(1+r)^n / ((1+r)^n − 1) | n = −log(1 − P×r/PMT) / log(1+r) solved iteratively | P = PMT × (1 − (1+r)^(−n)) / r | solves for any unknown given the other three TVM variables',
    lastVerified: '2026-01-15',
    relatedIds: ['loan-calculator', 'amortization-calculator', 'tvm-calculator'],
    relatedPosts: ['how-loan-payments-work'],
    loader: () => import('../finance/payment-calculator/index'),
  },
  {
    id: 'compound-interest-calculator',
    title: 'Compound Interest Calculator — Daily & Annual Growth',
    shortTitle: 'Compound Interest',
    description: 'Calculate how your investment grows over time with compound interest. Enter your principal, rate, and time period to see your future value and total.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    features: { aiProofWizard: true },
    seoKeywords: ['compound interest calculator', 'compound interest formula', 'investment growth calculator', 'future value calculator', 'interest compounding calculator', 'rule of 72'],
    schema: 'both',
    mathSolverExpression: 'A = P(1 + r/n)^(nt) | total_interest = A − P | effective_annual_rate = (1 + r/n)^n − 1 | Rule_of_72: years_to_double ≈ 72 / (r × 100) for quick estimation without logarithms',
    lastVerified: '2026-01-15',
    relatedIds: ['interest-calculator', 'investment-calculator', 'cd-calculator', 'future-value-calculator'],
    relatedPosts: ['compound-interest-guide', 'investment-growth-calculator-guide', 'savings-growth-guide', 'what-is-roi-and-how-to-calculate-it'],
    loader: () => import('../finance/compound-interest/index'),
  },
  {
    id: 'roi-calculator',
    title: 'Return on Investment (ROI) Calculator — With Annualized ROI',
    shortTitle: 'ROI Calculator',
    description: 'Calculate your return on investment with both basic ROI and annualized ROI (CAGR). Enter your initial investment, total return, and holding period to get.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['roi calculator', 'return on investment calculator', 'investment return calculator', 'roi formula', 'calculate roi percentage', 'profit calculator'],
    schema: 'both',
    mathSolverExpression: 'ROI = (total_return − initial_investment) / initial_investment × 100% | annualized_ROI(CAGR) = (total_return / initial_investment)^(1/years) − 1 | total_profit = total_return − initial_investment',
    lastVerified: '2026-01-15',
    relatedIds: ['investment-calculator', 'irr-calculator', 'average-return-calculator'],
    relatedPosts: ['what-is-roi-and-how-to-calculate-it'],
    loader: () => import('../finance/roi/index'),
  },
  {
    id: 'salary-to-hourly-calculator',
    title: 'Salary to Hourly Wage Converter — Annual to Hourly Rate',
    shortTitle: 'Salary to Hourly',
    description: 'Convert your annual salary to an equivalent hourly rate. Enter your salary and working hours to see your hourly, daily, weekly, and monthly rates.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['salary to hourly calculator', 'annual salary to hourly rate', 'hourly wage converter', 'salary converter', 'hourly rate calculator', 'wage calculator', 'california salary calculator 2026', 'new york paycheck calculator', 'texas salary calculator'],
    schema: 'both',
    mathSolverExpression: 'hourly_rate = annual_salary / (hours_per_week × weeks_per_year) | daily = hourly_rate × hours_per_day | weekly = hourly_rate × hours_per_week | monthly = annual_salary / 12',
    lastVerified: '2026-01-15',
    relatedIds: ['salary-hourly-calculator', 'salary-calculator', 'paycheck-calculator', 'salary-take-home'],
    loader: () => import('../finance/salary-to-hourly/index'),
  },
  {
    id: 'credit-card-payoff-calculator',
    title: 'Credit Card Payoff Calculator — Debt-Free Date & Total Interest',
    shortTitle: 'Credit Card Payoff',
    description: 'Calculate how much to pay monthly to be debt-free by a target date, or see your payoff timeline for a fixed payment. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['credit card payoff calculator', 'credit card debt calculator', 'pay off credit card by date', 'credit card interest calculator', 'debt free date calculator', 'how long to pay off credit card', 'true cost of minimum payments'],
    schema: 'both',
    mathSolverExpression: 'months_to_payoff_fixed = solve for n: balance = PMT × (1 − (1+r)^(−n)) / r | months_to_payoff_min = iterative where payment = max(balance×min_pct, min_fee) | total_interest = PMT × n − balance | target_payment = solver for PMT given target_date_n',
    lastVerified: '2026-01-15',
    relatedIds: ['debt-payoff-calculator', 'debt-consolidation-calculator', 'student-loan-calculator'],
    relatedPosts: ['credit-card-debt-payoff-guide', 'debt-consolidation-guide'],
    loader: () => import('../finance/credit-card-payoff/index'),
  },
  {
    id: 'net-worth-calculator',
    title: 'Net Worth Calculator — Assets, Liabilities & Net Worth',
    shortTitle: 'Net Worth Calculator',
    description: 'Calculate your total net worth by entering your assets and liabilities. Get a clear picture of your financial health with your net worth, debt-to-asset.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['net worth calculator', 'personal net worth', 'assets and liabilities calculator', 'net worth tracker', 'financial net worth', 'wealth calculator'],
    schema: 'both',
    mathSolverExpression: 'net_worth = Σ(all_assets) − Σ(all_liabilities) | debt_to_asset_ratio = total_liabilities / total_assets | financial_health: lower D/A ratio indicates stronger financial position',
    lastVerified: '2026-01-15',
    relatedIds: ['budget-calculator', 'savings-calculator', 'retirement-calculator'],
    relatedPosts: ['50-30-20-budget-guide', 'net-worth-guide'],
    loader: () => import('../finance/net-worth/index'),
  },
  {
    id: 'home-affordability-calculator',
    title: 'Home Affordability Calculator — Income & Debt Check',
    shortTitle: 'Home Affordability',
    description: 'Find out how much house you can afford based on your income, debts, and down payment. Calculates your maximum home price using front-end and back-end DTI.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Real Estate Finance',
    seoKeywords: ['home affordability calculator', 'how much house can i afford', 'mortgage affordability', 'dti calculator', 'home buying budget', 'maximum mortgage calculator'],
    schema: 'both',
    mathSolverExpression: 'front_end_max = (monthly_income × 0.28) × loan_term_months / amortization_factor | back_end_max = (monthly_income × 0.36 − monthly_debts) × loan_term_months / amortization_factor | overall_max = min(front_end, back_end)',
    relatedPosts: ['when-to-take-social-security'],
    lastVerified: '2026-01-15',
    relatedIds: ['house-affordability-calculator', 'dti-ratio-calculator', 'rent-affordability-calculator', 'down-payment-calculator'],
    loader: () => import('../finance/home-affordability/index'),
  },
  {
    id: 'rental-property-calculator',
    title: 'Rental Property Cash Flow Calculator — State-Specific Property Tax',
    shortTitle: 'Rental Property',
    description: 'Analyze rental property investments with state-specific tax rates for all 50 states. Calculate cash flow, cap rate, cash-on-cash return, NOI, DSCR, and.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Real Estate Finance',
    seoKeywords: ['rental property calculator', 'cash flow calculator rental', 'cap rate calculator', 'cash on cash return', 'rental property roi', 'real estate investment calculator'],
    schema: 'both',
    mathSolverExpression: 'NOI = rental_income − vacancy_loss − operating_expenses | cap_rate = NOI / property_value × 100% | cash_on_cash = annual_pre_tax_cash_flow / total_cash_invested × 100% | GRM = property_value / annual_rental_income | DSCR = NOI / debt_service',
    lastVerified: '2026-01-15',
    relatedIds: ['cap-rate-calculator', 'rent-vs-buy-calculator', 'arv-flipping-calculator', 'house-affordability-calculator'],
    loader: () => import('../finance/rental-property/index'),
  },
  {
    id: 'mortgage-amortization-calculator',
    title: 'Mortgage Amortization Calculator — Extra Payment Savings Chart',
    shortTitle: 'Mortgage Calculator',
    description: 'Calculate your monthly mortgage payment, full amortization schedule, and extra payment savings. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Real Estate Finance',
    seoKeywords: ['mortgage calculator', 'mortgage payment calculator', 'home loan calculator', 'amortization calculator', 'monthly mortgage payment', 'house payment calculator', 'california mortgage calculator', 'texas mortgage calculator', 'florida mortgage calculator'],
    schema: 'both',
    mathSolverExpression: 'M = P × r(1+r)^n / ((1+r)^n − 1) | schedule: each month interest = balance × r, principal = M − interest, new_balance = balance − principal | extra_payment: new_balance = balance − principal − extra | biweekly = M × 12 / 26',
    lastVerified: '2026-01-15',

    relatedPosts: ['mortgage-amortization-complete-guide'],
    relatedIds: ['mortgage-payoff-calculator', 'amortization-calculator', 'refinance-calculator', 'va-mortgage-calculator'],
    loader: () => import('../realestate/mortgage-amortization/index'),
  },
  {
    id: 'home-rent-vs-buy-calculator',
    title: 'Rent vs. Buy Calculator — Compare Costs Over Time — Calculator',
    shortTitle: 'Rent vs. Buy',
    description: 'Compare the true financial cost of renting vs. buying a home over your planned timeline. Accounts for appreciation, equity, taxes, and maintenance.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Real Estate Finance',
    seoKeywords: ['rent vs buy calculator', 'rent or buy', 'should i rent or buy a house', 'buy vs rent comparison', 'home buying calculator', 'rental vs ownership cost'],
    schema: 'both',
    mathSolverExpression: 'total_buy_cost = down_payment + closing_costs + Σ(monthly_mortgage + taxes + insurance + maintenance − equity_accumulated) | total_rent_cost = Σ(monthly_rent + renter_insurance) | net_difference = total_buy_cost − total_rent_cost over planned_horizon',
    lastVerified: '2026-01-15',
    relatedIds: ['rent-vs-buy-calculator', 'house-affordability-calculator', 'mortgage-amortization-calculator', 'closing-costs-calculator'],
    relatedPosts: ['how-much-house-can-i-afford', 'rent-vs-buy-analysis', 'realestate-rent-affordability-guide'],
    loader: () => import('../realestate/rent-vs-buy/index'),
  },
  {
    id: 'dti-ratio-calculator',
    title: 'Debt-to-Income (DTI) Ratio Calculator — Free Online Calculator & Guide',
    shortTitle: 'Debt-to-Income (DTI) Ratio Calculat',
    description: 'Calculate your front-end and back-end debt-to-income ratios to see if you qualify for a mortgage. Lenders typically require a DTI below 43%.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Real Estate Finance',
    seoKeywords: ['dti calculator', 'debt to income ratio', 'dti ratio calculator', 'mortgage dti', 'front end ratio', 'back end ratio'],
    schema: 'both',
    mathSolverExpression: 'front_end_DTI = monthly_housing_payment / gross_monthly_income × 100% | back_end_DTI = (housing_payment + total_debt_payments) / monthly_income × 100% | qualifies = front_end ≤ 28% AND back_end ≤ 43%',
    lastVerified: '2026-01-15',
    relatedIds: ['house-affordability-calculator', 'home-affordability-calculator', 'mortgage-amortization-calculator'],
    loader: () => import('../realestate/dti-ratio/index'),
  },
  {
    id: 'closing-costs-calculator',
    title: 'Closing Costs Estimator — Buyer & Seller Fee Breakdown',
    shortTitle: 'Closing Costs',
    description: 'Estimate buyer and seller closing costs for a real estate transaction. See itemized fees including origination, title insurance, agent commissions, and more.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Real Estate Finance',
    seoKeywords: ['closing costs calculator', 'closing costs estimator', 'home buying closing costs', 'seller closing costs', 'real estate closing fees', 'home purchase costs'],
    schema: 'both',
    mathSolverExpression: 'buyer_costs = origination_fee + title_insurance + appraisal + escrow + recording_fees | seller_costs = realtor_commission + transfer_tax + attorney_fees + other | total = buyer_costs + seller_costs | cash_to_close = down_payment + buyer_costs − deposits',
    relatedPosts: ['what-is-roi-and-how-to-calculate-it'],
    lastVerified: '2026-01-15',
    relatedIds: ['house-affordability-calculator', 'down-payment-calculator', 'mortgage-amortization-calculator'],
    loader: () => import('../realestate/closing-costs/index'),
  },
  {
    id: 'cap-rate-calculator',
    title: 'Cap Rate Calculator — NOI, Value & Investment Return',
    shortTitle: 'Cap Rate Calculator',
    description: 'Calculate the capitalization rate, NOI, and gross rent multiplier for any investment property. Essential for comparing rental property investments.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Real Estate Finance',
    seoKeywords: ['cap rate calculator', 'capitalization rate', 'noi calculator', 'rental property calculator', 'investment property cap rate', 'gross rent multiplier'],
    schema: 'both',
    mathSolverExpression: 'NOI = rental_income − vacancy − operating_expenses | cap_rate = NOI / property_value × 100% | GRM = property_value / annual_rental_income | higher cap rate implies higher return and typically higher risk',
    lastVerified: '2026-01-15',
    relatedIds: ['rental-property-calculator', 'arv-flipping-calculator', 'roi-calculator'],
    loader: () => import('../realestate/cap-rate/index'),
  },
  {
    id: 'repayment-calculator',
    title: 'Repayment Calculator — Amortization Schedule & Extra Payment Savings',
    shortTitle: 'Repayment Calculator',
    description: 'See the full amortization schedule for any loan with interactive year and month views. Add extra payments to see time and interest saved, then export to CSV.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['repayment calculator', 'loan amortization schedule', 'extra payment calculator', 'loan repayment calculator', 'amortization table', 'loan payoff calculator', 'how to pay off loan early', 'download amortization schedule csv'],
    schema: 'both',
    mathSolverExpression: 'M = P × r(1+r)^n / ((1+r)^n − 1) | each_period: interest = balance × r, principal = M − interest, new_balance = balance − principal | extra: new_balance = balance − principal − extra_payment | payoff_date = first period where balance ≤ 0',
    relatedPosts: ['when-to-take-social-security'],
    lastVerified: '2026-01-15',
    relatedIds: ['amortization-calculator', 'loan-calculator', 'mortgage-payoff-calculator'],
    loader: () => import('../finance/repayment/index'),
  },
  {
    id: 'college-cost-calculator',
    title: 'College Cost Calculator — 529 Savings & Tuition Projection',
    shortTitle: 'College Cost Calculator',
    description: 'Project college costs using College Board data, model 529 savings growth, and see your funding gap. Compare in-state, out-of-state, and private costs.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['college cost calculator', 'college savings calculator', '529 calculator', 'college tuition calculator', 'college savings projection', 'how much will college cost', 'college board data calculator', 'college funding calculator'],
    schema: 'both',
    mathSolverExpression: 'FV_tuition = current_cost × (1 + tuition_inflation)^years_until_college | FV_savings = PV × (1+r)^n + PMT × ((1+r)^n − 1)/r | funding_gap = FV_tuition − FV_savings | additional_PMT = gap / (((1+r)^n − 1)/r)',
    lastVerified: '2026-04-01',
    relatedIds: ['savings-calculator', 'student-loan-calculator', 'investment-calculator'],
    loader: () => import('../finance/college-cost/index'),
  },
  {
    id: 'fha-loan-calculator',
    title: 'FHA Loan Calculator — MIP Cost Breakdown & Upfront Premium Analysis',
    shortTitle: 'FHA Loan Calculator',
    description: 'Calculate your FHA loan monthly payment including all MIP costs. See the complete MIP cost breakdown over time — upfront premium (1.75% financed), annual.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Real Estate Finance',
    seoKeywords: ['fha loan calculator', 'fha mortgage calculator', 'fha mip calculator', 'fha loan payment', 'fha mortgage insurance premium', 'fha monthly payment'],
    schema: 'both',
    mathSolverExpression: 'upfront_MIP = loan_amount × 0.0175 (typically financed into loan) | annual_MIP_rate depends on LTV and loan_term (0.55% to 1.05%) | M = (P + upfront_MIP) × r(1+r)^n / ((1+r)^n − 1) + annual_MIP/12 | total_MIP_over_X_years = upfront + X_years_annual_MIP',
    lastVerified: '2026-01-15',
    relatedIds: ['va-mortgage-calculator', 'house-affordability-calculator', 'mortgage-amortization-calculator', 'refinance-calculator'],
    relatedPosts: ['fha-loan-requirements-mip-down-payment-qualifying'],
    loader: () => import('../realestate/fha-loan/index'),
  },
  {
    id: 'cd-calculator',
    title: 'CD Calculator 2026 — Compare Rates & Compounding (Ally, Marcus',
    shortTitle: 'CD Calculator',
    description: 'Calculate CD maturity amounts across all major US banks with real benchmark rates from Ally, Marcus, Discover, Capital One, and more.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['cd calculator', 'certificate of deposit calculator', 'cd rate calculator', 'cd maturity calculator', 'compound interest cd', 'cd ladder calculator', 'best cd rates 2026', 'cd compounding calculator'],
    schema: 'both',
    mathSolverExpression: 'A = P(1 + r/n)^(nt) | APY = (1 + r/n)^n − 1 | maturity_value = A | interest_earned = A − P | early_withdrawal_penalty = A × penalty_months_of_interest for the specific bank policy',
    relatedPosts: ['when-to-take-social-security'],
    lastVerified: '2026-01-15',
    relatedIds: ['savings-calculator', 'compound-interest-calculator', 'inflation-calculator'],
    loader: () => import('../finance/cd-calculator/index'),
  },
  {
    id: 'average-return-calculator',
    title: 'Average Return Calculator — CAGR vs. Simple Average (Volatility Drag)',
    shortTitle: 'Average Return Calculator',
    description: 'Calculate the compound annual growth rate (CAGR) and simple average return for any investment. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Investing',
    seoKeywords: ['average return calculator', 'cagr calculator', 'compound annual growth rate', 'volatility drag', 'cagr vs average return', 'investment return calculator', 'geometric mean return', 'simple average vs compound return'],
    schema: 'both',
    mathSolverExpression: 'CAGR = (ending_value / starting_value)^(1/years) − 1 | simple_avg = Σ(annual_returns) / n | volatility_drag = simple_avg − CAGR | geometric_mean = (Π(1+r_t))^(1/n) − 1 | higher volatility increases the gap',
    lastVerified: '2026-01-15',
    relatedIds: ['roi-calculator', 'investment-calculator', 'mutual-fund-calculator', 'irr-calculator'],
    loader: () => import('../finance/average-return/index'),
  },
  {
    id: 'boat-loan-calculator',
    title: 'Boat Loan Calculator — True Cost of Ownership (Maintenance & Storage)',
    shortTitle: 'Boat Loan Calculator',
    description: 'Calculate monthly boat loan payments including insurance, maintenance, and storage costs that can equal the loan payment itself.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['boat loan calculator', 'marine loan calculator', 'boat financing calculator', 'boat payment calculator', 'true cost of boat ownership', 'boat loan interest calculator', 'yacht loan calculator'],
    schema: 'both',
    mathSolverExpression: 'M = P × r(1+r)^n / ((1+r)^n − 1) | true_monthly_ownership = M + insurance + maintenance + storage | total_10yr_cost = true_monthly_ownership × 120 | total_20yr_cost = true_monthly_ownership × 240',
    relatedPosts: ['investment-growth-calculator-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['loan-calculator', 'personal-loan-calculator', 'business-loan-calculator'],
    loader: () => import('../finance/boat-loan/index'),
  },
  {
    id: 'vat-calculator',
    title: 'VAT Calculator — Add or Remove VAT (40+ Countries)',
    shortTitle: 'VAT Calculator',
    description: 'Calculate VAT for any amount across 40+ countries. Add VAT to a net price or remove it from a gross total. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Business & Accounting',
    seoKeywords: ['vat calculator', 'value added tax calculator', 'add vat calculator', 'remove vat calculator', 'vat rate by country', 'european vat calculator', 'vat reverse calculator', 'gst calculator'],
    schema: 'both',
    mathSolverExpression: 'price_with_vat = net_price × (1 + vat_rate) | vat_from_gross = gross_price × vat_rate / (1 + vat_rate) | net_from_gross = gross_price / (1 + vat_rate) | vat_amount = gross_price − net_price',
    lastVerified: '2026-01-15',
    relatedIds: ['sales-tax-calculator', 'commission-calculator', 'discount-calculator'],
    loader: () => import('../finance/vat-calculator/index'),
  },
  {
    id: 'discount-calculator',
    title: 'Discount Calculator — Stackable Discounts & Bulk Shopping Cart',
    shortTitle: 'Discount Calculator',
    description: 'Calculate stackable discounts applied sequentially (20% + 10% ≠ 30%). Includes a full shopping cart with add/remove items, per-item discounts, sales tax.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['discount calculator', 'stackable discount calculator', 'double discount calculator', 'shopping cart discount', 'bulk discount calculator', 'effective discount rate', 'coupon stack calculator', '20 percent off plus 10 percent off'],
    schema: 'both',
    mathSolverExpression: 'stacked_price = original × (1 − d1) × (1 − d2) × ... × (1 − dn) | effective_discount = 1 − stacked_price / original | item_total = Σ(price × quantity after sequential discounts) | grand_total = item_totals + sales_tax',
    lastVerified: '2026-01-15',
    relatedIds: ['sales-tax-calculator', 'vat-calculator', 'budget-calculator'],
    relatedPosts: ['percent-off-discount-guide', 'tipping-calculator-guide'],
    loader: () => import('../finance/discount-calculator/index'),
  },
  {
    id: 'mutual-fund-calculator',
    title: 'Mutual Fund Calculator — Expense Ratio Fee Impact (Index vs. Active)',
    shortTitle: 'Mutual Fund Calculator',
    description: 'Compare mutual fund growth with and without expense ratios. See how a 1% fee can cost 25-30% of returns over 30 years with interactive chart.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Investing',
    seoKeywords: ['mutual fund calculator', 'mutual fund return calculator', 'expense ratio calculator', 'mutual fund fee impact', 'index fund vs active fund', 'mutual fund growth calculator', 'expense ratio drag', 'vtsax vs active fund'],
    schema: 'both',
    mathSolverExpression: 'FV_no_fees = PV x (1+r)^n + PMT x ((1+r)^n - 1)/r | FV_with_fees = PV x (1+r-ER)^n + PMT x ((1+(r-ER))^n - 1)/(r-ER) | fee_impact = FV_no_fees - FV_with_fees | fee_drag_pct = fee_impact / FV_no_fees x 100%',
    lastVerified: '2026-05-15',
    relatedIds: ['average-return-calculator', 'investment-calculator', 'bond-calculator', 'future-value-calculator'],
    relatedPosts: ['mutual-fund-investing-guide'],
    loader: () => import('../finance/mutual-fund/index'),
  },
  {
    id: 'ira-calculator',
    title: 'IRA Calculator 2026 — Traditional vs. Roth (Side-by-Side Comparison)',
    shortTitle: 'IRA Calculator',
    description: 'Compare Traditional IRA vs. Roth IRA side-by-side with 2026 IRS contribution limits ($7,000 base, $8,000 age 50+). Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Retirement',
    seoKeywords: ['ira calculator', 'traditional vs roth ira', 'roth ira calculator 2026', 'traditional ira calculator', 'ira comparison calculator', 'ira contribution limits 2026', 'roth vs traditional which is better', 'ira breakeven tax rate'],
    schema: 'both',
    mathSolverExpression: 'Roth_FV = PMT × ((1+r)^n − 1)/r (tax_free at withdrawal) | Traditional_FV = PMT × ((1+r)^n − 1)/r × (1 − withdrawal_tax_rate) | breakeven_tax = rate where Roth_FV = Traditional_FV_after_tax | contribution_limit = $7,000 ($8,000 age 50+)',
    lastVerified: '2026-01-15',
    relatedIds: ['roth-ira-calculator', '401k-calculator', 'social-security-calculator', 'rmd-calculator'],
    relatedPosts: ['retirement-planning-guide', 'investment-basics-guide', 'tax-planning-for-retirement'],
    loader: () => import('../finance/ira-calculator/index'),
  },
  {
    id: 'paycheck-calculator',
    title: 'Paycheck Calculator 2026 — Hourly & Salary Take-Home Pay (All 50',
    shortTitle: 'Paycheck Calculator',
    description: 'Calculate your exact per-paycheck take-home pay for any pay frequency (weekly, bi-weekly, semi-monthly, monthly). Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['paycheck calculator', 'take home pay calculator', 'salary paycheck calculator', 'hourly paycheck calculator', 'paycheck calculator 2026', 'net pay calculator', 'paycheck tax calculator', 'after tax income calculator', 'biweekly paycheck calculator'],
    schema: 'both',
    mathSolverExpression: 'gross_per_period = annual_salary / pay_periods | federal_withholding = bracket_tax on (gross − pre_tax − std_deduction/pay_periods) | FICA = gross × 0.0765 / pay_periods | state_withholding = state_rate × gross | net_pay = gross − pre_tax − federal − FICA − state − post_tax',
    lastVerified: '2026-01-15',
    relatedIds: ['salary-take-home', 'salary-calculator', 'income-tax-calculator', 'salary-to-hourly-calculator'],
    relatedPosts: ['paycheck-deductions-guide', 'salary-negotiation-guide', 'self-employment-tax-guide'],
    loader: () => import('../finance/paycheck-calculator/index'),
  },
  {
    id: 'refinance-calculator',
    title: 'Refinance Calculator — Break-Even Analysis & Yes/No Recommendation',
    shortTitle: 'Refinance Calculator',
    description: 'Calculate whether refinancing your mortgage makes financial sense. Enter your current loan terms, new loan offer, closing costs, and planned stay to get a.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Mortgages',
    seoKeywords: ['refinance calculator', 'mortgage refinance calculator', 'should I refinance', 'refinance break even calculator', 'refinance vs no refinance', 'mortgage refi calculator', 'refinance savings calculator', 'closing costs vs savings'],
    schema: 'both',
    mathSolverExpression: 'old_M = P × r_old(1+r_old)^n_old / ((1+r_old)^n_old − 1) | new_M = new_loan_amount × r_new(1+r_new)^n_new / ((1+r_new)^n_new − 1) | break_even_months = closing_costs / (old_M − new_M) | total_savings = (old_M − new_M) × planned_stay_months − closing_costs',
    lastVerified: '2026-01-15',
    relatedIds: ['va-mortgage-calculator', 'fha-loan-calculator', 'mortgage-amortization-calculator', 'mortgage-payoff-calculator'],
    relatedPosts: ['mortgage-refinance-guide', 'how-much-house-can-i-afford', 'rent-vs-buy-analysis'],
    loader: () => import('../finance/refinance/index'),
  },
  {
    id: 'home-equity-loan-calculator',
    title: 'Home Equity Loan Calculator — LTV Limits & Equity Stack Visualization',
    shortTitle: 'Home Equity Loan',
    description: 'Calculate how much home equity you can borrow with a fixed-rate home equity loan. See max LTV by credit profile, monthly payment, and an equity stack bar.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Home Equity',
    seoKeywords: ['home equity loan calculator', 'home equity loan payment', 'second mortgage calculator', 'home equity loan rate', 'home equity borrowing calculator', 'heloan vs heloc', 'home equity loan monthly payment'],
    schema: 'both',
    mathSolverExpression: 'max_loan = home_value × max_LTV_pct − existing_mortgage | M = loan_amount × r(1+r)^n / ((1+r)^n − 1) | remaining_equity = home_value − existing_mortgage − loan_balance | LTV = (mortgage + loan) / home_value',
    lastVerified: '2026-01-15',
    relatedIds: ['heloc-calculator', 'house-affordability-calculator', 'mortgage-amortization-calculator'],
    loader: () => import('../finance/home-equity-loan/index'),
  },
  {
    id: 'down-payment-calculator',
    title: 'Down Payment Calculator — Savings Goal & PMI Warnings',
    shortTitle: 'Down Payment Calculator',
    description: 'Plan your home down payment savings. Enter your target home price, current savings, and monthly contribution to see your timeline, total PMI cost if under.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Real Estate Finance',
    seoKeywords: ['down payment calculator', 'home down payment calculator', 'how much down payment for house', 'down payment savings calculator', 'pmi calculator', '20 percent down calculator', 'how long to save for down payment', 'down payment goal calculator'],
    schema: 'both',
    mathSolverExpression: 'savings_goal = home_price × down_pct | months_to_goal = solve for n: PV×(1+r)^n + PMT×((1+r)^n−1)/r ≥ goal | PMI_rate = 0.0055 to 0.0125 if down_pct < 20% | monthly_PMI = loan_amount × PMI_rate / 12 | mortgage_estimate = remaining × monthly_factor',
    lastVerified: '2026-01-15',
    relatedIds: ['house-affordability-calculator', 'closing-costs-calculator', 'savings-calculator', 'home-affordability-calculator'],
    relatedPosts: ['how-much-house-can-i-afford', 'rent-vs-buy-analysis'],
    loader: () => import('../finance/down-payment/index'),
  },
  {
    id: 'payback-period-calculator',
    title: 'Payback Period Calculator — Simple & Discounted Payback (TVM)',
    shortTitle: 'Payback Period Calculator',
    description: 'Calculate the payback period for any investment. Toggle between simple payback and discounted payback (with time value of money).',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Business & Accounting',
    seoKeywords: ['payback period calculator', 'discounted payback calculator', 'investment payback period', 'tvm payback calculator', 'simple payback vs discounted', 'how long to recoup investment', 'capital budgeting calculator', 'payback period formula'],
    schema: 'both',
    mathSolverExpression: 'simple_payback = initial_investment / annual_cash_inflow (years) | discounted_payback = first year where Σ(CF_t/(1+r)^t) ≥ initial_investment | NPV = Σ(CF_t/(1+r)^t) − initial_investment (from t=1 to n) | profitability_index = PV_of_future_CF / initial_investment',
    lastVerified: '2026-01-15',
    relatedIds: ['irr-calculator', 'present-value-calculator', 'business-loan-calculator', 'asset-depreciation-calculator'],
    loader: () => import('../finance/payback-period/index'),
  },
  {
    id: 'future-value-calculator',
    title: 'Future Value Calculator — Compound Interest Formula & Growth Chart',
    shortTitle: 'Future Value Calculator',
    description: 'Calculate the future value of any investment with compound interest and optional monthly contributions. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Investing',
    seoKeywords: ['future value calculator', 'compound interest calculator', 'fv formula', 'future value with contributions', 'investment growth calculator', 'compound interest with monthly contributions', 'effective annual rate calculator', 'fv of annuity calculator'],
    schema: 'both',
    mathSolverExpression: 'FV = PV × (1 + r/n)^(nt) + PMT × ((1 + r/n)^(nt) − 1) / (r/n) | effective_annual_rate = (1 + r/n)^n − 1 | total_contributions = PV + Σ(PMT each period) | total_interest_earned = FV − total_contributions',
    lastVerified: '2026-01-15',
    relatedIds: ['present-value-calculator', 'tvm-calculator', 'investment-calculator', 'compound-interest-calculator'],
    relatedPosts: ['compound-interest-guide', 'inflation-impact-guide', 'investment-growth-calculator-guide'],
    loader: () => import('../finance/future-value/index'),
  },
  {
    id: 'arv-flipping-calculator',
    title: 'ARV & House Flipping Calculator — MAO, 70% Rule & Profit Gauge',
    shortTitle: 'ARV & Flipping',
    description: 'Calculate your Maximum Allowable Offer (MAO) for any fix-and-flip deal. Enter the After Repair Value, repair costs, holding costs, and target profit to.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Real Estate',
    seoKeywords: ['arv calculator', 'arv flipping calculator', 'maximum allowable offer calculator', 'house flipping calculator', '70 percent rule calculator', 'fix and flip calculator', 'mao calculator', 'real estate flipping calculator', 'flip profit calculator'],
    schema: 'both',
    mathSolverExpression: 'MAO_70pct = ARV × 0.70 − repair_costs (70% Rule) | MAO_target = ARV − repair_costs − holding_costs − selling_costs − target_profit | profit = ARV − purchase − repairs − holding − selling_costs | ROI = profit / (purchase + repairs) × 100%',
    lastVerified: '2026-01-15',
    relatedIds: ['rental-property-calculator', 'cap-rate-calculator', 'canadian-mortgage-calculator', 'roi-calculator'],
    loader: () => import('../finance/arv-flipping/index'),
  },
  {
    id: 'self-employment-tax-calculator',
    title: 'Self-Employment Tax Calculator — SECA, SS & Medicare Breakdown (2026)',
    shortTitle: 'Self-Employment Tax',
    description: 'Calculate your self-employment (SECA) tax with a full Social Security and Medicare breakdown. Free, instant, and accurate.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Taxes',
    seoKeywords: ['self employment tax calculator', 'seca tax calculator', 'self employed social security tax', 'self employed medicare tax', '1099 tax calculator', 'schedule se calculator', 'self employment tax rate 2026', 'qbi deduction calculator', 'self employed fica calculator', 'california income tax calculator 2026', 'new york tax calculator 2026', 'texas sales tax calculator', '2026 tax calculator'],
    schema: 'both',
    mathSolverExpression: 'SECA_SS = min(net_profit × 0.124, SS_wage_base_remaining) | SECA_Medicare = net_profit × 0.029 (uncapped) | deductible_half = SECA_total × 0.50 | QBI_deduction = 20% of qualified_business_income (subject to phaseout) | total_SECA = SS_portion + Medicare_portion',
    lastVerified: '2026-01-15',
    relatedIds: ['capital-gains-tax-calculator', 'income-tax-calculator', 'marriage-tax-calculator'],
    relatedPosts: ['income-tax-guide', 'self-employment-tax-guide'],
    loader: () => import('../finance/self-employment-tax/index'),
  },
  {
    id: 'depreciation-calculator',
    title: 'Depreciation Calculator — MACRS (200% DB) & Straight Line with',
    shortTitle: 'Depreciation (MACRS/SL)',
    description: 'Calculate year-by-year depreciation schedules using Straight Line or MACRS (200% Declining Balance with half-year convention).',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Business & Accounting',
    seoKeywords: ['depreciation calculator', 'macrs depreciation calculator', 'straight line depreciation calculator', '200 percent declining balance calculator', 'half year convention depreciation', 'irs depreciation calculator', 'business asset depreciation', 'depreciation schedule calculator', 'tax depreciation calculator'],
    schema: 'both',
    mathSolverExpression: 'MACRS_year1 = cost × table_pct_1 (half_year: 7.14% for 15yr, 20% for 5yr) | MACRS_year_t = cost × IRS_table_pct_t | SL = (cost − salvage) / life with half_year convention in year 1 and n+1 | book_value_t = cost − Σ(depreciation for years 1 to t)',
    relatedPosts: ['pension-calculator-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['asset-depreciation-calculator', 'self-employment-tax-calculator', 'business-loan-calculator'],
    loader: () => import('../finance/depreciation/index'),
  },
  {
    id: 'eth-gas-fee-calculator',
    title: 'ETH Gas Fee Calculator — Ethereum Transaction Fee Estimator',
    shortTitle: 'ETH Gas Fee',
    description: 'Estimate Ethereum gas fees for any transaction type — standard transfer, ERC-20 token, Uniswap swap, NFT mint, or complex contract.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['eth gas fee calculator', 'ethereum gas calculator', 'gas fee estimator', 'ethereum transaction fee calculator', 'gwei to usd converter', 'eth gas price calculator', 'eip-1559 gas calculator'],
    schema: 'both',
    mathSolverExpression: 'total_fee_ETH = gas_units × (base_fee + priority_fee) / 1e9 | total_fee_USD = total_fee_ETH × ETH_price_in_USD | speed_tiers: slow(low_priority), standard(average), fast(high_priority) affecting priority_fee only',
    lastVerified: '2026-01-15',
    relatedIds: ['currency-converter', 'investment-calculator', 'bitcoin-calculator'],
    loader: () => import('../finance/eth-gas-fee/index'),
  },
  {
    id: 'fire-calculator',
    title: 'FIRE Calculator — Financial Independence, Retire Early (4% Rule &',
    shortTitle: 'FIRE Calculator',
    description: 'Calculate your path to financial independence with the FIRE framework. Enter your age, net worth, income, and expenses to see your FIRE number, estimated.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Retirement',
    seoKeywords: ['fire calculator', 'financial independence calculator', 'retire early calculator', '4 percent rule calculator', 'lean fire calculator', 'fat fire calculator', 'coast fire calculator', 'fire number calculator', 'trinity study calculator', 'fire age calculator', 'savings rate calculator'],
    schema: 'both',
    mathSolverExpression: 'FIRE_number = annual_expenses / 0.04 (4% Rule) | FIRE_age = current_age + years_to_FIRE | years_to_FIRE = solve n: PV×(1+r)^n + PMT×((1+r)^n−1)/r ≥ FIRE_number | savings_rate = (income − expenses) / income × 100% | Coast_FV_needed = FIRE_number / (1+r)^(retire_age − coast_age)',
    lastVerified: '2026-01-15',
    relatedIds: ['pension-calculator', 'retirement-calculator', 'annuity-payout-calculator', 'social-security-calculator'],
    relatedPosts: ['how-much-do-you-need-to-retire'],
    loader: () => import('../finance/fire-calculator/index'),
  },
  {
    id: 'salary-hourly-calculator',
    title: 'Salary to Hourly Wage Converter — Quick Rate Calculator',
    shortTitle: 'Salary to Hourly',
    description: 'Convert your annual salary to an equivalent hourly rate based on hours per week and weeks per year. See daily, weekly, monthly, and annual breakdowns.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['salary to hourly calculator', 'hourly wage calculator', 'annual to hourly converter', 'hourly rate calculator', 'salary converter', 'wage calculator', 'california salary calculator 2026', 'new york paycheck calculator', 'texas salary calculator'],
    schema: 'both',
    mathSolverExpression: 'Hourly = Annual / (WeeksPerYear x HoursPerWeek) | Pay = Rate x Hours',
    relatedPosts: ['what-is-roi-and-how-to-calculate-it'],
    lastVerified: '2026-01-15',
    relatedIds: ['salary-to-hourly-calculator', 'salary-calculator', 'paycheck-calculator'],
    loader: () => import('../finance/salary-hourly/index'),
  },
  {
    id: 'salary-take-home',
    title: 'Salary Take-Home Pay Calculator — Net Income After Tax & Deductions',
    shortTitle: 'Take-Home Pay',
    description: 'Calculate your true take-home pay after federal income tax, FICA, and state taxes. See your net annual salary, per-paycheck amount, and complete tax.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Personal Finance',
    seoKeywords: ['take home pay calculator', 'salary take home calculator', 'net pay calculator', 'after tax salary calculator', 'salary calculator 2025', 'paycheck tax breakdown', 'effective tax rate calculator', 'salary after taxes', 'annual take home pay', 'net income calculator', 'california salary calculator 2026', 'new york paycheck calculator', 'texas salary calculator'],
    schema: 'both',
    mathSolverExpression: 'Net = Gross - PreTaxDeductions - FederalTax - FICA - StateTax | FederalTax = Sum(bracket marginal rates on taxable income)',
    lastVerified: '2026-01-15',
    relatedIds: ['income-tax-calculator', 'paycheck-calculator', 'salary-calculator'],
    loader: () => import('../finance/salary-take-home/index'),
  },
  {
    id: 'capital-gains-tax-calculator',
    title: 'Capital Gains Tax Calculator — Short vs. Long Term (2026 Brackets)',
    shortTitle: 'Capital Gains Tax',
    description: 'Calculate capital gains tax for stocks, crypto, and real estate. Enter purchase price, sale price, holding period, income, and filing status.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Taxes',
    relatedIds: ['self-employment-tax-calculator', 'income-tax-calculator', 'marriage-tax-calculator'],
    seoKeywords: ['capital gains tax calculator', 'long term capital gains', 'short term capital gains', 'capital gains tax rate 2025', 'capital gains tax rate 2026', 'investment tax calculator', 'stock sale tax calculator', 'crypto tax calculator', 'capital gains bracket', 'niit calculator', 'california income tax calculator 2026', 'new york tax calculator 2026', 'texas sales tax calculator', '2026 tax calculator'],
    schema: 'both',
    mathSolverExpression: 'Gain = SalePrice - CostBasis | LTCGRate = bracket lookup (0%/15%/20% based on income + filing status) | NIIT = 3.8% if AGI > $200k(S)/$250k(MFJ) | TotalTax = Federal + NIIT + State',
    lastVerified: '2026-01-15',
    relatedPosts: ['capital-gains-tax-guide', 'income-tax-guide'],
    loader: () => import('../finance/capital-gains-tax/index'),
  },
  {
    id: 'tax-calculator',
    title: 'Tax Calculator — Federal Income Tax, Brackets & Effective Rate',
    shortTitle: 'Tax Calculator',
    description: 'Estimate your federal income tax using progressive tax brackets. See marginal rate, effective rate, and whether you will owe or get a refund.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Taxes',
    seoKeywords: ['income tax calculator', 'tax bracket calculator', 'federal tax estimator', 'federal income tax calculator', 'effective tax rate calculator', 'progressive tax calculator', 'marginal tax rate calculator', '2025 tax calculator', 'california income tax calculator 2026', 'new york tax calculator 2026', 'texas sales tax calculator', '2026 tax calculator'],
    schema: 'both',
    mathSolverExpression: 'Tax = Σ(bracket_rate × bracket_income) for each bracket',
    lastVerified: '2026-01-15',
    relatedIds: ['income-tax', 'self-employment-tax', 'capital-gains-tax', 'salary-take-home'],
    loader: () => import('../finance/tax-calculator/index'),
  },

  {
    id: 'sip-calculator',
    title: 'SIP Calculator — SIP Returns & Wealth Growth Projection',
    shortTitle: 'SIP Calculator',
    description: 'Calculate SIP returns with monthly investments and lump sum contributions. See total invested, total returns, and maturity value with yearly wealth projection.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Investing',
    seoKeywords: ['sip calculator', 'systematic investment plan calculator', 'sip return calculator', 'sip maturity calculator', 'monthly investment calculator', 'sip planner', 'mutual fund sip calculator'],
    schema: 'both',
    mathSolverExpression: 'FV = LS x (1 + r)^n + P x [((1 + r)^n - 1) / r] x (1 + r)',
    lastVerified: '2026-05-15',
    relatedIds: ['investment-calculator', 'compound-interest-calculator', 'mutual-fund-calculator', 'retirement-calculator'],
    relatedPosts: ['sip-investment-guide'],
    loader: () => import('../finance/sip-calculator/index'),
  },
  {
    id: 'swp-calculator',
    title: 'SWP Calculator — Systematic Withdrawal Plan Income & Corpus Longevity',
    shortTitle: 'SWP Calculator',
    description: 'Calculate how long your retirement corpus lasts with monthly SWP withdrawals. Simulate month-by-month balance depletion with yearly balance chart.',
    category: 'Finance',
    categorySlug: 'finance',
    subCategory: 'Retirement Planning',
    seoKeywords: ['swp calculator', 'systematic withdrawal plan calculator', 'retirement withdrawal calculator', 'monthly withdrawal calculator', 'corpus longevity calculator', 'retirement income planner'],
    schema: 'both',
    mathSolverExpression: 'Balance_t = Balance_t-1 x (1 + r/12) - Withdrawal',
    lastVerified: '2026-05-15',
    relatedIds: ['retirement-calculator', 'annuity-payout-calculator', 'mutual-fund-calculator', 'investment-calculator'],
    relatedPosts: ['swp-retirement-guide'],
    loader: () => import('../finance/swp-calculator/index'),
  },
];