import type { CalculatorEntry } from '../../types/calculator';

export const healthCalculators: CalculatorEntry[] = [
  {
    id: 'bmi-calculator',
    title: 'BMI & Ideal Weight Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'BMI Calculator',
    description: 'Calculate your Body Mass Index and ideal weight range for your height. Features a WHO classification visual gauge with color-coded BMI bands, needle.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Body Composition',
    relatedIds: ['tdee-calculator', 'body-fat-calculator', 'bmr-calculator', 'ideal-weight-calculator', 'healthy-weight-calculator'],
    seoKeywords: ['bmi calculator', 'body mass index calculator', 'ideal weight calculator', 'bmi chart', 'healthy weight calculator', 'calculate bmi'],
    schema: 'both',
    mathSolverExpression: 'BMI = weight(kg) / height(m)^2 | body mass index classification',
    lastVerified: '2026-01-15',
    relatedPosts: ['bmi-guide-health', 'body-fat-percentage-guide', 'daily-water-intake-guide', 'dog-age-human-years-guide', 'heat-index-calculator-everyday', 'pregnancy-due-date-guide', 'sleep-cycle-calculator-guide'],
    loader: () => import('../health/bmi/index'),
  },
  {
    id: 'tdee-calculator',
    title: 'Free TDEE Calculator — Find Your Daily Calorie Needs in 60 Seconds',
    shortTitle: 'TDEE Calculator',
    description: 'Find your maintenance calories in seconds. Uses Mifflin-St Jeor and Katch-McArdle equations with BMR/TEF/EAT/NEAT breakdown.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Nutrition',
    relatedIds: ['bmr-calculator', 'bmi-calculator', 'macro-calculator', 'calories-burned-calculator'],
    seoKeywords: ['tdee calculator', 'total daily energy expenditure', 'calorie calculator', 'bmr calculator', 'maintenance calories', 'how many calories should i eat'],
    schema: 'both',
    mathSolverExpression: 'TDEE = BMR × AF | total daily energy expenditure with activity factor',
    lastVerified: '2026-01-15',
    relatedPosts: ['tdee-calculator-guide'],
    loader: () => import('../health/tdee/index'),
  },
  {
    id: 'due-date-calculator',
    title: 'Pregnancy Due Date Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'Due Date Calculator',
    description: 'Calculate your estimated due date from LMP, conception date, or IVF transfer date. View current pregnancy week, trimester milestones timeline, and days.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Pregnancy',
    relatedIds: ['pregnancy-weight-gain-calculator', 'pregnancy-conception-calculator', 'period-ovulation-calculator'],
    seoKeywords: ['due date calculator', 'pregnancy due date', 'when is my due date', 'pregnancy calculator', 'conception date calculator', 'how many weeks pregnant'],
    schema: 'both',
    mathSolverExpression: 'EDD = LMP + 280 days | Naegeles rule for estimated due date',
    lastVerified: '2026-01-15',
    relatedPosts: ['pregnancy-due-date-guide'],
    loader: () => import('../health/due-date/index'),
  },
  {
    id: 'pregnancy-calculator',
    title: 'Pregnancy Calculator — Due Date, Trimester & Milestones',
    shortTitle: 'Pregnancy Calculator',
    description: 'Track your pregnancy week by week. Calculate due date, current trimester, gestational age, and key milestones from your last menstrual period.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Pregnancy',
    relatedIds: ['due-date-calculator', 'pregnancy-weight-gain-calculator', 'pregnancy-conception-calculator'],
    seoKeywords: ['pregnancy calculator', 'due date calculator', 'pregnancy trimester calculator', 'gestational age calculator', 'pregnancy milestones', 'how many weeks pregnant', 'pregnancy tracker', 'pregnancy week by week'],
    schema: 'both',
    mathSolverExpression: 'Due Date = LMP + 280 days | Naegeles rule for estimated due date',
    lastVerified: '2026-01-15',
    relatedPosts: ['pregnancy-due-date-guide'],
    loader: () => import('../health/pregnancy-calculator/index'),
  },
  {
    id: 'bmr-calculator',
    title: 'Basal Metabolic Rate (BMR) Calculator — Free Online Calculator & Guide',
    shortTitle: 'BMR Calculator',
    description: 'Calculate your Basal Metabolic Rate using Mifflin-St Jeor, Harris-Benedict, and Katch-McArdle formulas. Free, instant, and accurate.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Nutrition',
    relatedIds: ['tdee-calculator', 'bmi-calculator', 'macro-calculator'],
    seoKeywords: ['bmr calculator', 'basal metabolic rate', 'mifflin st jeor calculator', 'harris benedict calculator', 'resting metabolic rate', 'katch mcardle formula'],
    schema: 'both',
    mathSolverExpression: 'BMR = 10w + 6.25h - 5a + S (M:+5, F:-161) | Mifflin-St Jeor formula',
    lastVerified: '2026-01-15',
    relatedPosts: ['bmr-weight-management-guide', 'daily-calorie-intake-guide', 'tdee-calculator-guide'],
    loader: () => import('../health/bmr/index'),
  },
  {
    id: 'heart-rate-zones-calculator',
    title: 'Target Heart Rate Zone Calculator — Free Online Calculator & Guide',
    shortTitle: 'Heart Rate Zones',
    description: 'Calculate your 5 training heart rate zones using the Karvonen formula or percentage of max HR. Free, instant, and accurate.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Fitness',
    relatedIds: ['calories-burned-calculator', 'pace-calculator', 'one-rep-max-calculator'],
    seoKeywords: ['heart rate zone calculator', 'target heart rate calculator', 'fat burning heart rate', 'karvonen formula', 'max heart rate calculator', 'training zones'],
    schema: 'both',
    mathSolverExpression: 'THR = (HRmax - HRrest) × %Intensity + HRrest | Karvonen formula for target heart rate',
    lastVerified: '2026-01-15',
    relatedPosts: ['heart-rate-zone-training-guide', 'heat-index-calculator-everyday', 'sleep-cycle-calculator-guide'],
    loader: () => import('../health/heart-rate-zones/index'),
  },
  {
    id: 'water-intake-calculator',
    title: 'Daily Water Intake Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'Water Intake',
    description: 'Calculate your recommended daily water intake based on body weight, activity level, and climate. Free, instant, and accurate.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Nutrition',
    relatedIds: ['macro-calculator', 'protein-calculator', 'fat-intake-calculator', 'carbohydrate-calculator'],
    seoKeywords: ['water intake calculator', 'how much water should i drink', 'daily water intake', 'hydration calculator', 'water consumption calculator', 'how much water per day'],
    schema: 'both',
    mathSolverExpression: 'Water(L) = Weight(kg) × 0.033 | recommended daily water intake',
    lastVerified: '2026-01-15',
    relatedPosts: ['daily-water-intake-guide', 'heat-index-calculator-everyday'],
    loader: () => import('../health/water-intake/index'),
  },
  {
    id: 'body-fat-calculator',
    title: 'Body Fat Percentage Calculator — U.S. Navy Method — Calculator',
    shortTitle: 'Body Fat Calculator',
    description: 'Calculate your body fat percentage using the U.S. Navy circumference method. Uses neck, abdomen (men), and waist/hip (women) measurements with anatomical.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Body Composition',
    relatedIds: ['bmi-calculator', 'army-body-fat-calculator', 'lean-body-mass-calculator', 'overweight-calculator'],
    seoKeywords: ['body fat calculator', 'body fat percentage', 'us navy body fat', 'circumference method', 'body composition calculator', 'estimate body fat'],
    schema: 'both',
    mathSolverExpression: 'BF%(M) = 86.010 × log10(abdomen-neck) - 70.041 × log10(height) + 36.76 | U.S. Navy body fat method',
    lastVerified: '2026-01-15',
    relatedPosts: ['bmi-guide-health', 'body-fat-percentage-guide'],
    loader: () => import('../health/body-fat/index'),
  },
  {
    id: 'ideal-weight-calculator',
    title: 'Ideal Body Weight Calculator — 4 Medical Formulas — Calculator',
    shortTitle: 'Ideal Weight Calculator',
    description: 'Calculate your ideal body weight using Devine, Robinson, Miller, and Hamwi formulas. Get the average across all four plus healthy BMI range for your height.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Body Composition',
    relatedIds: ['bmi-calculator', 'healthy-weight-calculator', 'lean-body-mass-calculator', 'body-type-calculator'],
    seoKeywords: ['ideal weight calculator', 'ideal body weight', 'devine formula', 'hamwi formula', 'healthy weight range', 'how much should i weigh'],
    schema: 'both',
    mathSolverExpression: 'Devine(M): 50 + 2.3(in>60) | avg of Devine, Robinson, Miller, Hamwi formulas',
    lastVerified: '2026-01-15',
    loader: () => import('../health/ideal-weight/index'),
  },
  {
    id: 'macro-calculator',
    title: 'Daily Macro Calculator — Personalized Macros by Diet',
    shortTitle: 'Macro Calculator',
    description: 'Calculate your daily macronutrient targets based on TDEE, fitness goal, and diet preference. Free online calculator with formula guide and step-by-step results.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Nutrition',
    relatedIds: ['protein-calculator', 'carbohydrate-calculator', 'fat-intake-calculator', 'macro-point-calculator', 'tdee-calculator'],
    seoKeywords: ['macro calculator', 'macronutrient calculator', 'protein calculator', 'carb calculator', 'fat calculator', 'diet macros', 'keto macros'],
    schema: 'both',
    mathSolverExpression: 'P(g)=Cal×P%/4 | C(g)=Cal×C%/4 | F(g)=Cal×F%/9 | macronutrient energy split',
    lastVerified: '2026-01-15',
    relatedPosts: ['bmr-weight-management-guide', 'daily-calorie-intake-guide', 'daily-protein-intake-guide', 'macro-calculator-guide', 'tdee-calculator-guide'],
    loader: () => import('../health/macro/index'),
  },
  {
    id: 'pregnancy-weight-gain-calculator',
    title: 'Pregnancy Weight Gain Calculator — IOM Guidelines — Calculator',
    shortTitle: 'Pregnancy Weight Gain',
    description: 'Track your pregnancy weight gain against IOM guidelines based on pre-pregnancy BMI. Features worked examples, quick reference BMI-based ranges.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Pregnancy',
    relatedIds: ['due-date-calculator', 'pregnancy-conception-calculator'],
    seoKeywords: ['pregnancy weight gain calculator', 'gestational weight gain', 'iom guidelines', 'pregnancy weight tracker', 'how much weight to gain during pregnancy', 'bmi pregnancy weight gain'],
    schema: 'both',
    mathSolverExpression: 'IOM ranges: Under<25→28-40lb, Normal→25-35lb, Over→15-25lb, Obese→11-20lb | gestational weight gain guidelines',
    lastVerified: '2026-05-18',
    loader: () => import('../health/pregnancy-gain/index'),
  },
  {
    id: 'pregnancy-conception-calculator',
    title: 'Pregnancy Conception & Fertile Window Calculator — Calculator',
    shortTitle: 'Conception Calculator',
    description: 'Calculate your fertile window, peak fertility days, and estimated ovulation date using LMP, cycle, or next period methods.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Pregnancy',
    relatedIds: ['due-date-calculator', 'pregnancy-weight-gain-calculator', 'period-ovulation-calculator'],
    seoKeywords: ['conception calculator', 'fertile window calculator', 'ovulation calculator', 'when to conceive', 'fertility calculator', 'best days to get pregnant'],
    schema: 'both',
    mathSolverExpression: 'Ovulation = CycleLen - 14 | FertileWindow = Ovulation-5 to Ovulation+1 day | peak fertility probability',
    lastVerified: '2026-05-18',
    loader: () => import('../health/pregnancy-conception/index'),
  },
  {
    id: 'pace-calculator',
    title: 'Running Pace Calculator — Split Generator — Free Online Calculator',
    shortTitle: 'Pace Calculator',
    description: 'Calculate running pace, time, or distance. Includes auto-generated race split table with wristband view for marathon, half marathon, 10K, 5K, and custom.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Fitness',
    relatedIds: ['heart-rate-zones-calculator', 'calories-burned-calculator', 'one-rep-max-calculator'],
    seoKeywords: ['pace calculator', 'running pace calculator', 'marathon pace calculator', 'race split generator', 'running time calculator', 'pace chart'],
    schema: 'both',
    mathSolverExpression: 'Pace(min/km) = Time(min) / Dist(km) | Speed(km/h) = Dist(km) / Time(h)',
    lastVerified: '2026-01-15',
    relatedPosts: ['heart-rate-zone-training-guide'],
    loader: () => import('../health/pace/index'),
  },
  {
    id: 'army-body-fat-calculator',
    title: 'Army Body Fat Calculator — AR 600-9 Tape Test & ABCP Standards',
    shortTitle: 'Army Body Fat',
    description: 'Calculate body fat using the official U.S. Army AR 600-9 tape test method. Includes pass/fail by age bracket, screening weight reference.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Body Composition',
    relatedIds: ['body-fat-calculator', 'bmi-calculator', 'lean-body-mass-calculator', 'overweight-calculator'],
    seoKeywords: ['army body fat calculator', 'army tape test', 'ar 600-9', 'body fat army standards', 'military body fat calculator', 'army body composition program', 'abcp calculator'],
    schema: 'both',
    mathSolverExpression: 'BF%(M)=86.010×log10(abdomen-neck)-70.041×log10(H)+36.76 | AR 600-9 circumference method',
    lastVerified: '2026-05-18',
    relatedPosts: ['body-fat-percentage-guide'],
    loader: () => import('../health/army-body-fat/index'),
  },
  {
    id: 'carbohydrate-calculator',
    title: 'Carbohydrate Calculator — Training-Based Carbs — Calculator',
    shortTitle: 'Carb Calculator',
    description: 'Calculate your daily carbohydrate needs based on weight, goal, and training volume. Includes glycogen loading timeline for endurance events and food.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Nutrition',
    relatedIds: ['macro-calculator', 'protein-calculator', 'fat-intake-calculator'],
    seoKeywords: ['carb calculator', 'carbohydrate calculator', 'glycogen loading', 'carbs for endurance', 'low carb calculator', 'how many carbs per day'],
    schema: 'both',
    mathSolverExpression: 'Carbs(g) = Weight(kg) × g/kg(3-5 low, 5-7 mod, 7-10 high, 10-12 extreme) | training-based carbohydrate needs',
    relatedPosts: ['bmi-guide-health'],
    lastVerified: '2026-01-15',
    loader: () => import('../health/carbohydrate/index'),
  },
  {
    id: 'lean-body-mass-calculator',
    title: 'Lean Body Mass Calculator — 3 Formulas — Free Online Calculator',
    shortTitle: 'LBM Calculator',
    description: 'Calculate your lean body mass using Boer, James, and Hume formulas simultaneously. Get estimated fat mass and lean mass percentage without body fat.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Body Composition',
    relatedIds: ['bmi-calculator', 'body-fat-calculator', 'ideal-weight-calculator', 'healthy-weight-calculator'],
    seoKeywords: ['lean body mass calculator', 'lbm calculator', 'lean mass calculator', 'boer formula', 'fat free mass', 'body composition calculator'],
    schema: 'both',
    mathSolverExpression: 'LBM(M)=0.407w+0.267h-19.2 | LBM(F)=0.252w+0.473h-48.3 | Boer formula for lean body mass',
    lastVerified: '2026-01-15',
    loader: () => import('../health/lean-body-mass/index'),
  },
  {
    id: 'healthy-weight-calculator',
    title: 'Healthy Weight Calculator — BMI, WHtR & Frame Size',
    shortTitle: 'Healthy Weight',
    description: 'Determine your healthy weight range using BMI, Waist-to-Height Ratio (WHtR), and frame size adjustment. Features the "waist less than half your height" rule.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Body Composition',
    relatedIds: ['bmi-calculator', 'ideal-weight-calculator', 'overweight-calculator', 'body-type-calculator'],
    seoKeywords: ['healthy weight calculator', 'healthy weight range', 'whtr calculator', 'waist to height ratio', 'ideal weight for height', 'frame size weight'],
    schema: 'both',
    mathSolverExpression: 'HealthyRange = [18.5×h², 24.9×h²] | WHtR < 0.5 for low cardiometabolic risk',
    lastVerified: '2026-01-15',
    loader: () => import('../health/healthy-weight/index'),
  },
  {
    id: 'calorie-calculator',
    title: 'Calorie Calculator — Daily Intake, BMR & Weight Management',
    shortTitle: 'Calorie Calculator',
    description: 'Calculate your daily calorie needs using BMR and activity level. Compare intake vs. burned to plan weight loss, gain, or maintenance.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Nutrition',
    relatedIds: ['calories-burned-calculator', 'tdee-calculator', 'bmi-calculator', 'macro-calculator'],
    seoKeywords: ['calorie calculator', 'daily calorie needs', 'bmr calculator', 'tdee calculator', 'calorie deficit calculator', 'weight loss calories', 'maintenance calories', 'calorie intake vs burned'],
    schema: 'both',
    mathSolverExpression: 'BMR = 10W + 6.25H - 5A + 5 (male) | BMR = 10W + 6.25H - 5A - 161 (female)',
    lastVerified: '2026-01-15',
    relatedPosts: ['bmi-guide-health', 'bmr-weight-management-guide', 'daily-calorie-intake-guide', 'daily-protein-intake-guide', 'daily-water-intake-guide', 'dog-age-human-years-guide', 'macro-calculator-guide', 'tdee-calculator-guide'],
    loader: () => import('../health/calorie-calculator/index'),
  },
  {
    id: 'calories-burned-calculator',
    title: 'Calories Burned Calculator — MET Compendium — Free Online Calculator',
    shortTitle: 'Calories Burned',
    description: 'Calculate calories burned for 100+ activities using MET values from the Compendium of Physical Activities. Free, instant, and accurate.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Fitness',
    relatedIds: ['tdee-calculator', 'heart-rate-zones-calculator', 'pace-calculator', 'macro-calculator'],
    seoKeywords: ['calories burned calculator', 'exercise calorie calculator', 'met calculator', 'calories burned running', 'calories burned walking', 'calories burned lifting'],
    schema: 'both',
    mathSolverExpression: 'Calories = MET × weight(kg) × duration(hr) | based on Compendium of Physical Activities',
    lastVerified: '2026-01-15',
    relatedPosts: ['heart-rate-zone-training-guide'],
    loader: () => import('../health/calories-burned/index'),
  },
  {
    id: 'one-rep-max-calculator',
    title: 'One Rep Max Calculator — 3 Formulas + % Table — Free Online Calculator',
    shortTitle: '1RM Calculator',
    description: 'Calculate your one rep max using Epley, Brzycki, and Lombardi formulas. Includes auto-generated 50–100% percentage breakdown table for barbell training.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Fitness',
    relatedIds: ['pace-calculator', 'heart-rate-zones-calculator', 'calories-burned-calculator'],
    seoKeywords: ['one rep max calculator', '1rm calculator', 'epley formula', 'brzycki formula', 'max bench press calculator', 'percentage breakdown'],
    schema: 'both',
    mathSolverExpression: '1RM = w × (1 + r/30) | Epley formula for estimated one rep max',
    lastVerified: '2026-01-15',
    loader: () => import('../health/one-rep-max/index'),
  },
  {
    id: 'protein-calculator',
    title: 'Protein Calculator — Evidence-Based Daily Intake — Calculator',
    shortTitle: 'Protein Calculator',
    description: 'Calculate your daily protein needs based on the evidence-based range of 1.6–2.2 g/kg. Includes per-meal breakdown, MPS optimization, and food equivalent guide.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Nutrition',
    relatedIds: ['macro-calculator', 'carbohydrate-calculator', 'fat-intake-calculator'],
    seoKeywords: ['protein calculator', 'how much protein per day', 'protein intake calculator', 'protein for muscle gain', 'protein for fat loss', 'daily protein needs'],
    schema: 'both',
    mathSolverExpression: 'Protein(g) = Weight(kg) × (1.6 to 2.2) g/kg | evidence-based daily protein intake range',
    lastVerified: '2026-01-15',
    relatedPosts: ['daily-protein-intake-guide', 'macro-calculator-guide'],
    loader: () => import('../health/protein/index'),
  },
  {
    id: 'fat-intake-calculator',
    title: 'Fat Intake Calculator — AHA Saturated Fat Guidelines',
    shortTitle: 'Fat Intake',
    description: 'Calculate your daily fat intake recommendation with a saturated/monounsaturated/polyunsaturated breakdown. Free, instant, and accurate.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Nutrition',
    relatedIds: ['macro-calculator', 'protein-calculator', 'carbohydrate-calculator'],
    seoKeywords: ['fat intake calculator', 'daily fat intake', 'saturated fat limit', 'dietary fat guidelines', 'healthy fats calculator', 'macronutrient calculator'],
    schema: 'both',
    mathSolverExpression: 'Fat(g) = (Cal × Fat%) / 9 | SatFat < 7% of total calories | AHA dietary fat guidelines',
    lastVerified: '2026-01-15',
    loader: () => import('../health/fat-intake/index'),
  },
  {
    id: 'period-ovulation-calculator',
    title: 'Period & Ovulation Calculator — Private Calendar & Fertility Tracking',
    shortTitle: 'Period & Ovulation',
    description: 'Track your menstrual cycle and predict periods, ovulation dates, and fertile windows for 3 months. Free, instant, and accurate.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Reproductive Health',
    relatedIds: ['pregnancy-conception-calculator', 'due-date-calculator'],
    seoKeywords: ['period calculator', 'ovulation calculator', 'menstrual cycle tracker', 'fertile window calculator', 'period tracker', 'ovulation predictor', 'cycle tracker'],
    schema: 'both',
    mathSolverExpression: 'CycleDay1 = period start | Ovulation ≈ day 14 of 28-day cycle | NextPeriod = Start + CycleLength',
    lastVerified: '2026-05-18',
    loader: () => import('../health/period-ovulation/index'),
  },
  {
    id: 'gfr-calculator',
    title: 'GFR Calculator — 2021 CKD-EPI eGFR with CKD Stage (Race-Free)',
    shortTitle: 'GFR Calculator',
    description: 'Free eGFR calculator using the 2021 CKD-EPI race-free equation. Enter creatinine, age, and sex to get your kidney function, CKD stage, normal ranges by age, and what your number means.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Medical',
    relatedIds: ['bsa-calculator', 'bac-calculator', 'blood-type-calculator'],
    seoKeywords: ['gfr calculator', 'egfr calculator', 'kidney function calculator', 'ckd epi formula', 'glomerular filtration rate', 'kidney disease stages', 'creatinine clearance'],
    schema: 'both',
    mathSolverExpression: 'eGFR = 142 × min(Scr/κ,1)^α × max(Scr/κ,1)^-1.2 × 0.9938^Age × (1.012 if female) | 2021 CKD-EPI equation',
    lastVerified: '2026-01-15',
    relatedPosts: ['gfr-kidney-function-complete-guide'],
    loader: () => import('../health/gfr/index'),
  },
  {
    id: 'body-type-calculator',
    title: 'Body Type Calculator — Fashion Shape, WHR & Somatotype Guide',
    shortTitle: 'Body Type Calculator',
    description: 'Determine your body shape from bust, waist, and hip measurements. Classifies Pear, Apple, Hourglass, Rectangle, and Inverted Triangle with WHR health risk.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Body Composition',
    relatedIds: ['bmi-calculator', 'healthy-weight-calculator', 'ideal-weight-calculator'],
    seoKeywords: ['body type calculator', 'body shape calculator', 'pear apple hourglass', 'what is my body shape', 'waist to hip ratio calculator', 'whr health risk', 'somatotype calculator'],
    schema: 'both',
    mathSolverExpression: 'BodyShape = f(bust, waist, hip) | WHratio = waist/hip | pear, apple, hourglass, rectangle, inverted triangle',
    lastVerified: '2026-05-18',
    loader: () => import('../health/body-type/index'),
  },
  {
    id: 'bsa-calculator',
    title: 'Body Surface Area (BSA) Calculator — Mosteller, Du Bois & Haycock',
    shortTitle: 'BSA Calculator',
    description: 'Calculate your body surface area using Mosteller, Du Bois, and Haycock formulas. Includes formula comparison, BSA reference chart, chemotherapy dosing.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Medical',
    relatedIds: ['gfr-calculator', 'bmi-calculator', 'ideal-weight-calculator'],
    seoKeywords: ['bsa calculator', 'body surface area', 'mosteller formula', 'du bois formula', 'chemotherapy dosing', 'burn surface area calculator', 'cardiac index'],
    schema: 'both',
    mathSolverExpression: 'BSA(m²) = sqrt(weight(kg) × height(cm) / 3600) | Mosteller formula for body surface area',
    lastVerified: '2026-05-18',
    loader: () => import('../health/bsa/index'),
  },
  {
    id: 'bac-calculator',
    title: 'BAC Calculator — Widmark Formula, Custom ABV & Impairment Guide',
    shortTitle: 'BAC Calculator',
    description: 'Estimate your blood alcohol concentration using the Widmark formula with custom ABV support for craft beer, wine, and liquor.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Medical',
    relatedIds: ['gfr-calculator', 'bsa-calculator', 'blood-type-calculator'],
    seoKeywords: ['bac calculator', 'blood alcohol calculator', 'widmark formula', 'alcohol impairment', 'blood alcohol content', 'how drunk am i', 'bac chart', 'alcohol metabolism'],
    schema: 'both',
    mathSolverExpression: 'BAC = (drinks × grams_alcohol) / (weight_lbs × 453.592 × rho) × 100 - 0.015 × hours | Widmark formula with custom ABV',
    relatedPosts: ['daily-calorie-intake-guide'],
    lastVerified: '2026-05-18',
    loader: () => import('../health/bac/index'),
  },
  {
    id: 'macro-point-calculator',
    title: 'Macro Point Calculator — Nutrient Scoring System — Calculator',
    shortTitle: 'Macro Points',
    description: 'Score any food using a macronutrient-weighted points formula based on calories, saturated fat, sugar, and protein. Not affiliated with Weight Watchers.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Nutrition',
    relatedIds: ['macro-calculator', 'protein-calculator', 'fat-intake-calculator', 'carbohydrate-calculator'],
    seoKeywords: ['macro point calculator', 'food points calculator', 'nutrition score calculator', 'dietary points system', 'healthy food scoring', 'macronutrient points'],
    schema: 'both',
    mathSolverExpression: 'Points = cal×0.0305 + satFat×0.275 + sugar×0.12 - protein×0.098 | nutrient density scoring system',
    lastVerified: '2026-05-18',
    loader: () => import('../health/macro-point/index'),
  },
  {
    id: 'overweight-calculator',
    title: 'Overweight & Cardiovascular Risk Calculator — Free Online Calculator',
    shortTitle: 'Overweight Risk',
    description: 'Assess your weight and cardiovascular risk by combining BMI with waist-to-height ratio (WHtR). Free, instant, and accurate.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Body Composition',
    relatedIds: ['bmi-calculator', 'healthy-weight-calculator', 'body-fat-calculator', 'army-body-fat-calculator'],
    seoKeywords: ['overweight calculator', 'cardiovascular risk calculator', 'waist to height ratio', 'visceral fat', 'am i overweight', 'healthy weight range', 'obesity risk assessment'],
    schema: 'both',
    mathSolverExpression: 'BMI = w/h² | WHtR = waist/height | combined BMI + WHtR cardiovascular risk assessment',
    lastVerified: '2026-01-15',
    loader: () => import('../health/overweight/index'),
  },
  {
    id: 'chocolate-toxicity-calculator',
    title: 'Dog Chocolate Toxicity Calculator — Theobromine & Caffeine Risk',
    shortTitle: 'Chocolate Toxicity',
    description: 'Check if chocolate is toxic for your dog. Calculates theobromine and caffeine intake based on chocolate type, amount eaten, and dog weight.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Pet Health',
    relatedIds: ['dog-cat-age-calculator', 'dog-cat-pregnancy-calculator', 'bmi-calculator'],
    seoKeywords: ['chocolate toxicity calculator', 'dog chocolate poisoning', 'theobromine calculator', 'is chocolate bad for dogs', 'dog ate chocolate', 'pet poison control', 'chocolate toxic dose dog', 'ASPCA poison control'],
    schema: 'both',
    mathSolverExpression: 'Risk = (Theobromine + Caffeine) / WeightKg | Severity thresholds: >20mg/kg = vomiting, >60mg/kg = seizures',
    relatedPosts: ['tdee-calculator-guide'],
    lastVerified: '2026-01-15',
    loader: () => import('../health/chocolate-toxicity/index'),
  },
  {
    id: 'dog-cat-age-calculator',
    title: 'Dog & Cat Age in Human Years — Epigenetic Clock Formula + Life Stages',
    shortTitle: 'Dog & Cat Age in',
    description: 'Calculate dog and cat age in human years with the NIH epigenetic clock formula. Includes AAHA/AAFP life stages, size-adjusted aging, and reference milestones.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Pet Health',
    relatedIds: ['dog-cat-pregnancy-calculator', 'chocolate-toxicity-calculator', 'bmi-calculator'],
    seoKeywords: ['dog age calculator', 'cat age calculator', 'dog years to human years', 'cat years to human years', 'pet age calculator', 'how old is my dog', 'dog years chart', 'epigenetic dog age', 'pet life stages', 'dog age formula'],
    schema: 'both',
    mathSolverExpression: 'DogEpigenetic = 16 × ln(Age) + 31 | Cat = 15 (yr1) + 9 (yr2) + 4×(Age-2) | Traditional = Age × 7',
    lastVerified: '2026-05-18',
    loader: () => import('../health/dog-cat-age/index'),
  },
  {
    id: 'dog-cat-pregnancy-calculator',
    title: 'Dog & Cat Pregnancy Calculator — Whelping Due Date & Calendar',
    shortTitle: 'Pet Pregnancy',
    description: 'Calculate the due date for a pregnant dog (63 days gestation) or cat (65 days gestation). Free online calculator with formula guide and step-by-step results.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Pet Health',
    relatedIds: ['dog-cat-age-calculator', 'chocolate-toxicity-calculator', 'due-date-calculator', 'pregnancy-calculator'],
    seoKeywords: ['dog pregnancy calculator', 'cat pregnancy calculator', 'dog gestation calculator', 'cat gestation calculator', 'whelping date calculator', 'when will my dog give birth', 'dog due date calculator', 'pet pregnancy calculator', 'dog breeding calculator'],
    relatedPosts: ['dog-age-human-years-guide', 'pregnancy-due-date-guide'],
    schema: 'both',
    mathSolverExpression: 'DogDueDate = BreedingDate + 63 days (range 58-68) | CatDueDate = BreedingDate + 65 days (range 63-67)',
    lastVerified: '2026-05-18',
    loader: () => import('../health/dog-cat-pregnancy/index'),
  },
  {
    id: 'blood-type-calculator',
    title: 'Blood Type Calculator — Punnett Square & Inheritance Probability',
    shortTitle: 'Blood Type',
    description: 'Predict possible blood types for a child based on parent ABO and Rh types. Visualize inheritance with Punnett square probabilities.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Medical',
    relatedIds: ['bsa-calculator', 'gfr-calculator', 'bac-calculator', 'bmi-calculator'],
    seoKeywords: ['blood type calculator', 'punnett square blood type', 'blood type inheritance', 'child blood type calculator', 'abo blood type calculator', 'blood type genetics', 'rh factor calculator', 'blood group inheritance', 'parent blood type predictor'],
    relatedPosts: ['gfr-kidney-function-complete-guide', 'bmi-guide-health'],
    schema: 'both',
    mathSolverExpression: 'ABO: 3-allele system (I^A, I^B, i) with co-dominance | Rh: R (dominant) × r (recessive) | Punnett: 16 grid combinations',
    lastVerified: '2026-01-15',
    loader: () => import('../health/blood-type/index'),
  },
  {
    id: 'pig-gestation-calculator',
    title: 'Pig Gestation Calculator — 3-3-3 Rule & Farrowing Date Predictor',
    shortTitle: 'Pig Gestation',
    description: 'Calculate pig farrowing dates using the 3-3-3 rule (114 days). Pregnancy milestones, breed-specific adjustments, and farrowing preparation timeline included.',
    category: 'Health & Fitness',
    categorySlug: 'health',
    subCategory: 'Pet Health',
    relatedIds: ['gestation-period-calculator', 'due-date-calculator', 'dog-cat-pregnancy-calculator'],
    seoKeywords: ['pig gestation calculator', 'pig farrowing date', '3-3-3 rule pig', 'sow pregnancy calculator', 'pig breeding calculator', 'pig gestation period', 'swine gestation', 'potbelly pig pregnancy', 'pig pregnancy timeline', 'farrowing date calculator'],
    schema: 'both',
    mathSolverExpression: 'Gestation = 114 days = 3 months + 3 weeks + 3 days | Farrowing Date = Breeding Date + 114 days',
    lastVerified: '2026-05-19',
    loader: () => import('../health/pig-gestation/index'),
  },
];
