import type { CalculatorEntry } from '../../types/calculator';

export const industrialCalculators: CalculatorEntry[] = [
  {
    id: 'pressure-converter',
    title: 'Pressure Converter — PSI, Bar, kPa, MPa, atm & More',
    shortTitle: 'Pressure Converter',
    description: 'Convert between PSI, bar, kPa, MPa, atmospheres, torr, and inches of mercury. Free online pressure unit converter with instant results and common.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['pressure converter', 'psi to bar', 'kpa to psi', 'bar to psi', 'pressure unit converter', 'psi to kpa', 'convert pressure', 'torque to bar', 'psi to atm', 'mmhg to kpa'],
    schema: 'both',
    mathSolverExpression: 'P = F / A | convert between psi, bar, Pa, kPa, MPa, atm, torr, inHg',
    lastVerified: '2026-01-15',
    relatedIds: ['force-converter', 'torque-converter', 'temperature-converter', 'speed-converter'],
    loader: () => import('../industrial/pressure-converter/index'),
  },
  {
    id: 'torque-converter',
    title: 'Torque Converter - Nm to ft-lbs, kgf-cm, kip-ft & More Units',
    shortTitle: 'Torque Converter',
    description: 'Convert torque units: Nm to ft-lbs, kgf-cm to Nm, kip-ft to kNm. Free calculator for automotive repair and engineering torque conversions.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['torque converter', 'nm to ft-lb', 'ft-lbs to nm', 'torque wrench converter', 'newton meters to foot pounds', 'torque unit converter', 'nm to lb ft', 'kgf cm to nm', 'torque conversion calculator'],
    schema: 'both',
    mathSolverExpression: 'tau = F x r | convert between N-m, lb-ft, in-lb, kgf-cm, kip-ft, ozf-in, kN-m',
    lastVerified: '2026-05-17',
    relatedPosts: ['btu-calculator-guide'],
    relatedIds: ['pressure-converter', 'force-converter', 'speed-converter', 'energy-converter', 'power-converter'],
    loader: () => import('../industrial/torque-converter/index'),
  },
  {
    id: 'energy-converter',
    title: 'Energy Converter — Joules, Calories, kWh, BTU & More',
    shortTitle: 'Energy Converter',
    description: 'Convert between joules, calories, kilowatt-hours, BTUs, electronvolts, and more. Free online energy unit converter for physics, nutrition, and engineering.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['energy converter', 'joules to calories', 'kwh to btu', 'calories to joules', 'energy unit converter', 'btu to kwh', 'joules to kwh', 'cal to j', 'convert energy units', 'electronvolts to joules'],
    schema: 'both',
    mathSolverExpression: 'E = F x d | convert between J, cal, kWh, BTU, eV',
    lastVerified: '2026-01-15',
    relatedIds: ['power-converter', 'force-converter', 'torque-converter', 'temperature-converter'],
    loader: () => import('../industrial/energy-converter/index'),
  },
  {
    id: 'power-converter',
    title: 'Power Converter — Watts, Horsepower, BTU/h & More',
    shortTitle: 'Power Converter',
    description: 'Convert between watts, horsepower (mechanical, electric, metric), BTU per hour, and more. Free online power unit converter for engines and appliances.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['power converter', 'hp to kw', 'kw to hp', 'watts to horsepower', 'btu to watts', 'horsepower converter', 'power unit converter', 'engine power converter', 'w to hp', 'mechanical horsepower to kw'],
    schema: 'both',
    mathSolverExpression: 'P = W / t | convert between W, hp, kW, BTU/h, ft-lbf/s, kcal/s',
    lastVerified: '2026-05-17',
    relatedPosts: ['btu-calculator-guide'],
    relatedIds: ['energy-converter', 'torque-converter', 'force-converter', 'speed-converter'],
    loader: () => import('../industrial/power-converter/index'),
  },
  {
    id: 'force-converter',
    title: 'Force Converter - Newtons to lbf, kgf, kN, Kips & Dynes Online',
    shortTitle: 'Force Converter',
    description: 'Convert force units: newtons to lbf, kgf to N, kips to kN, dynes to pounds. Free calculator for structural engineering and physics force conversions.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['force converter', 'newtons to pounds', 'lbf to n', 'kgf to n', 'force unit converter', 'newtons to lb', 'dynes to newtons', 'pound force to newtons', 'convert force units', 'kip to n'],
    schema: 'both',
    mathSolverExpression: 'F = m x a | convert between N, kN, lbf, kip, kgf, dyn, pdl',
    lastVerified: '2026-05-17',
    relatedPosts: ['btu-calculator-guide'],
    relatedIds: ['pressure-converter', 'torque-converter', 'weight-converter', 'energy-converter', 'speed-converter'],
    loader: () => import('../industrial/force-converter/index'),
  },
  {
    id: 'density-converter',
    title: 'Density Converter — kg/m³, g/cm³, lb/ft³, Specific Gravity & More',
    shortTitle: 'Density Converter',
    description: 'Convert between kg/m³, g/cm³, lb/ft³, lb/in³, specific gravity, and more. Free online density unit converter for materials science and engineering.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['density converter', 'kg/m3 to lb/ft3', 'g/cm3 to kg/m3', 'specific gravity to density', 'density unit converter', 'lb/in3 to kg/m3', 'water density', 'material density converter', 'sg to density', 'pound per cubic foot to kg m3'],
    schema: 'both',
    mathSolverExpression: 'ρ = m / V | convert between kg/m³, g/cm³, lb/ft³, SG',
    lastVerified: '2026-01-15',
    relatedIds: ['weight-converter', 'volume-converter', 'hardness-converter', 'viscosity-converter'],
    relatedPosts: ['industrial-unit-converter-guide'],
    loader: () => import('../industrial/density-converter/index'),
  },
  {
    id: 'angle-converter',
    title: 'Angle Converter — Degrees, Radians, Gradians, Arcminutes & More',
    shortTitle: 'Angle Converter',
    description: 'Convert between degrees, radians, gradians, arcminutes, arcseconds, milliradians, and turns. Free online calculator with formula guide and step-by-step results.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['angle converter', 'degrees to radians', 'radians to degrees', 'gradians to degrees', 'arcminutes to degrees', 'angle unit converter', 'deg to rad', 'rad to deg', 'convert angles', 'milliradians to degrees'],
    schema: 'both',
    mathSolverExpression: 'Î¸ = s / r | convert between deg, rad, grad, arcmin, arcsec',
    lastVerified: '2026-01-15',
    relatedIds: ['speed-converter', 'length-converter', 'torque-converter', 'frequency-converter'],
    relatedPosts: ['industrial-unit-converter-guide'],
    loader: () => import('../industrial/angle-converter/index'),
  },
  {
    id: 'frequency-converter',
    title: 'Frequency Converter — Hz, kHz, MHz, GHz, RPM & More',
    shortTitle: 'Frequency Converter',
    description: 'Convert between hertz, kilohertz, megahertz, gigahertz, RPM, radians per second, and BPM. Free online frequency unit converter for electronics and audio.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['frequency converter', 'hz to khz', 'mhz to ghz', 'rpm to hz', 'frequency unit converter', 'hz to rpm', 'khz to mhz', 'convert frequency', 'ghz to mhz', 'rad s to hz'],
    schema: 'both',
    mathSolverExpression: 'f = 1 / T | convert between Hz, kHz, MHz, GHz, RPM',
    lastVerified: '2026-01-15',
    relatedIds: ['speed-converter', 'angle-converter', 'power-converter', 'electrical-converter'],
    relatedPosts: ['industrial-unit-converter-guide'],
    loader: () => import('../industrial/frequency-converter/index'),
  },
  {
    id: 'fuel-economy-converter',
    title: 'Fuel Economy Converter — MPG, L/100km, km/L & More',
    shortTitle: 'Fuel Economy Converter',
    description: 'Convert between miles per gallon (US/UK), liters per 100 km, km per liter, and gallons per 100 miles. Free online fuel economy converter for drivers and fleets.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['fuel economy converter', 'mpg to l 100km', 'l 100km to mpg', 'uk mpg to us mpg', 'km l to mpg', 'fuel consumption converter', 'us mpg to uk mpg', 'convert mpg', 'liters per 100km to mpg', 'gallons per 100 miles'],
    schema: 'both',
    mathSolverExpression: 'MPG = 235.215 / (L/100km) | convert between MPG, L/100km, km/L',
    lastVerified: '2026-01-15',
    relatedIds: ['speed-converter', 'volume-converter', 'weight-converter', 'hardness-converter'],
    loader: () => import('../industrial/fuel-economy-converter/index'),
  },
  {
    id: 'hardness-converter',
    title: 'Hardness Converter — HRC, HRB, HB, Vickers, Shore & More',
    shortTitle: 'Hardness Converter',
    description: 'Convert between Rockwell (HRC, HRB, HRA), Brinell (HBW), Vickers (HV), and Shore hardness scales per ASTM E140. Free online hardness converter for metallurgy.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['hardness converter', 'hrc to hb', 'rockwell to brinell', 'vickers to rockwell', 'hardness conversion chart', 'hrc to hv', 'hbw to hrc', 'rockwell c to brinell', 'metal hardness converter', 'astm e140 hardness conversion'],
    schema: 'both',
    mathSolverExpression: 'HRC â†” HB â†” HV | hardness scale conversion per ASTM E140',
    lastVerified: '2026-01-15',
    relatedIds: ['density-converter', 'viscosity-converter', 'weight-converter', 'force-converter'],
    loader: () => import('../industrial/hardness-converter/index'),
  },
  {
    id: 'viscosity-converter',
    title: 'Viscosity Converter — Poise, Stokes, Centipoise, Centistokes & More',
    shortTitle: 'Viscosity Converter',
    description: 'Convert between pascal-seconds, poise, centipoise, stokes, centistokes, and more. Free online viscosity unit converter for lubricants and fluids.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['viscosity converter', 'centipoise to centistokes', 'cps to cst', 'poise to stokes', 'viscosity unit converter', 'pa s to poise', 'cp to cst', 'dynamic viscosity converter', 'kinematic viscosity converter', 'oil viscosity converter'],
    schema: 'both',
    mathSolverExpression: 'Î· = Ï„ / γÌ‡ | convert between P, St, cP, cSt, Pa·s',
    relatedPosts: ['electricity-cost-calculator-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['density-converter', 'hardness-converter', 'temperature-converter', 'pressure-converter'],
    loader: () => import('../industrial/viscosity-converter/index'),
  },
  {
    id: 'electrical-converter',
    title: 'Electrical Unit Converter — Volts, Amps, Ohms, Farads & More',
    shortTitle: 'Electrical Converter',
    description: 'Convert between volts, amps, ohms, farads, henries, siemens, and coulombs with metric prefixes. Free, instant, and accurate.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['electrical converter', 'volts to millivolts', 'amps to milliamps', 'ohms to kilohms', 'farads to microfarads', 'capacitance converter', 'resistance converter', 'voltage converter', 'current converter', 'electrical unit converter'],
    schema: 'both',
    mathSolverExpression: 'V = I x R | convert between V, A, Ω, F, H, S, C',
    lastVerified: '2026-01-15',
    relatedIds: ['power-converter', 'energy-converter', 'frequency-converter', 'data-storage-converter'],
    loader: () => import('../industrial/electrical-converter/index'),
  },
  {
    id: 'temperature-converter',
    title: 'Temperature Converter — Celsius, Fahrenheit, Kelvin & Rankine',
    shortTitle: 'Temperature Converter',
    description: 'Convert between Celsius, Fahrenheit, Kelvin, and Rankine instantly. Free online temperature converter for cooking, science, weather, and engineering.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['temperature converter', 'celsius to fahrenheit', 'fahrenheit to celsius', 'kelvin to celsius', 'temperature conversion', 'c to f', 'f to c', 'oven temperature converter', 'body temperature converter', 'convert temperature units'],
    schema: 'both',
    mathSolverExpression: '°F = °C x 9/5 + 32 | convert between °C, °F, K, °R',
    lastVerified: '2026-01-15',
    relatedIds: ['oven-temperature-converter', 'pressure-converter', 'energy-converter', 'viscosity-converter'],
    loader: () => import('../industrial/temperature-converter/index'),
  },
  {
    id: 'length-converter',
    title: 'Length Converter — Meters, Feet, Inches, Miles & More',
    shortTitle: 'Length Converter',
    description: 'Convert between meters, feet, inches, centimeters, kilometers, miles, nautical miles, and more. Free, instant, and accurate.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['length converter', 'meters to feet', 'feet to meters', 'inches to cm', 'cm to inches', 'km to miles', 'miles to km', 'length unit converter', 'distance converter', 'convert length units'],
    schema: 'both',
    mathSolverExpression: 'd = |x2 - x1| | convert between m, ft, in, cm, km, mi, nmi',
    lastVerified: '2026-01-15',
    relatedIds: ['area-converter', 'volume-converter', 'speed-converter', 'angle-converter'],
    relatedPosts: ['industrial-unit-converter-guide'],
    loader: () => import('../industrial/length-converter/index'),
  },
  {
    id: 'weight-converter',
    title: 'Weight Converter — Kilograms, Pounds, Ounces, Stone & More',
    shortTitle: 'Weight Converter',
    description: 'Convert between kilograms, pounds, ounces, stone, metric tonnes, and US tons. Free online weight converter for fitness, cooking, shipping, and science.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['weight converter', 'kg to lbs', 'lbs to kg', 'pounds to kilograms', 'ounces to grams', 'stone to kg', 'weight unit converter', 'mass converter', 'ton to kg', 'gram to ounce'],
    schema: 'both',
    mathSolverExpression: 'W = m x g | convert between kg, lb, oz, st, t, ton',
    lastVerified: '2026-01-15',
    relatedIds: ['density-converter', 'volume-converter', 'force-converter', 'hardness-converter'],
    loader: () => import('../industrial/weight-converter/index'),
  },
  {
    id: 'volume-converter',
    title: 'Volume Converter — Liters, Gallons, Cups, Cubic Meters & More',
    shortTitle: 'Volume Converter',
    description: 'Convert between liters, gallons, cups, fluid ounces, cubic meters, cubic feet, and more. Free online calculator with formula guide and step-by-step results.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['volume converter', 'liters to gallons', 'gallons to liters', 'cups to ml', 'ml to cups', 'cubic meters to cubic feet', 'fluid ounces to ml', 'volume unit converter', 'tbsp to ml', 'qt to l'],
    schema: 'both',
    mathSolverExpression: 'V = l x w x h | convert between L, gal, cup, fl oz, m³, ft³',
    lastVerified: '2026-01-15',
    relatedIds: ['weight-converter', 'density-converter', 'length-converter', 'area-converter', 'fuel-economy-converter'],
    loader: () => import('../industrial/volume-converter/index'),
  },
  {
    id: 'speed-converter',
    title: 'Speed Converter — km/h, mph, Knots, Mach & Speed of Light',
    shortTitle: 'Speed Converter',
    description: 'Convert between km/h, mph, knots, meters per second, Mach number, and the speed of light. Free online calculator with formula guide and step-by-step results.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['speed converter', 'kmh to mph', 'mph to kmh', 'knots to mph', 'mach to kmh', 'm/s to mph', 'speed unit converter', 'wind speed converter', 'convert speed units', 'knots to kmh'],
    schema: 'both',
    mathSolverExpression: 'v = d / t | convert between km/h, mph, m/s, knots, Mach',
    lastVerified: '2026-05-17',
    relatedPosts: ['btu-calculator-guide'],
    relatedIds: ['torque-converter', 'pressure-converter', 'angle-converter', 'force-converter', 'length-converter'],
    loader: () => import('../industrial/speed-converter/index'),
  },
  {
    id: 'area-converter',
    title: 'Area Converter — m², ft², Acres, Hectares, Square Miles & More',
    shortTitle: 'Area Converter',
    description: 'Convert between square meters, square feet, acres, hectares, square kilometers, square miles, and more. Free, instant, and accurate.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['area converter', 'square meters to square feet', 'sq ft to sq m', 'acres to hectares', 'hectares to acres', 'square miles to km2', 'area unit converter', 'land converter', 'property area converter', 'convert area units'],
    schema: 'both',
    mathSolverExpression: 'A = l x w | convert between m², ft², ac, ha, km², mi²',
    lastVerified: '2026-05-17',
    relatedPosts: ['btu-calculator-guide'],
    relatedIds: ['length-converter', 'volume-converter', 'speed-converter', 'cooking-converter'],
    loader: () => import('../industrial/area-converter/index'),
  },
  {
    id: 'data-storage-converter',
    title: 'Data Storage Converter — Bytes, KB, MB, GB, TB, KiB, MiB & More',
    shortTitle: 'Data Storage Converter',
    description: 'Convert between bytes, kilobytes, megabytes, gigabytes, terabytes, kibibytes, mebibytes, and more. Free, instant, and accurate.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['data storage converter', 'gb to mb', 'mb to gb', 'kb to mb', 'tb to gb', 'bytes to mb', 'gib to gb', 'storage unit converter', 'binary to decimal converter', 'file size converter'],
    schema: 'both',
    mathSolverExpression: '1 KB = 1024 B | convert between B, KB, MB, GB, TB, KiB, MiB',
    lastVerified: '2026-05-17',
    relatedPosts: ['btu-calculator-guide'],
    relatedIds: ['electrical-converter', 'frequency-converter', 'speed-converter'],
    loader: () => import('../industrial/data-storage-converter/index'),
  },
  {
    id: 'cooking-converter',
    title: 'Cooking Measurement Converter — Cups, Tbsp, Tsp, mL, Grams & More',
    shortTitle: 'Cooking Converter',
    description: 'Convert between cups, tablespoons, teaspoons, milliliters, fluid ounces, pints, quarts, gallons, and water-weight equivalents.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['cooking converter', 'cups to ml', 'tbsp to ml', 'tsp to ml', 'cups to grams', 'cooking measurement converter', 'recipe converter', 'baking converter', 'fluid ounces to cups', 'kitchen measurement converter'],
    schema: 'both',
    mathSolverExpression: '1 cup = 240 mL | convert between cup, tbsp, tsp, mL, fl oz, pt, qt, gal',
    lastVerified: '2026-05-17',
    relatedPosts: ['btu-calculator-guide'],
    relatedIds: ['volume-converter', 'weight-converter', 'temperature-converter', 'oven-temperature-converter'],
    loader: () => import('../industrial/cooking-converter/index'),
  },
  {
    id: 'cbm-calculator',
    title: 'CBM & Dimensional Weight Calculator — Sea, Air & Courier Freight',
    shortTitle: 'CBM Calculator',
    description: 'Calculate cubic meters (CBM) and dimensional weight for any shipment. Supports air (1:6000), sea (1:1000), and courier (1:5000) dim factors.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Industrial & Trades',
    seoKeywords: ['cbm calculator', 'cubic meter calculator', 'dimensional weight calculator', 'freight calculator', 'air freight volume calculator', 'sea freight calculator', 'shipping cbm', 'chargeable weight calculator', 'container load calculator', 'logistics calculator'],
    schema: 'both',
    mathSolverExpression: 'CBM = L x W x H x Packages | DimWeightAir = LxWxH(cm)/6000 | Chargeable = max(Actual, Dim) | Container 20ft = 33 CBM, 40ft = 67 CBM',
    lastVerified: '2026-05-17',
    relatedPosts: ['btu-calculator-guide'],
    relatedIds: ['volume-converter', 'weight-converter', 'length-converter', 'area-converter'],
    loader: () => import('../industrial/cbm-calculator/index'),
  },
  {
    id: 'oven-temperature-converter',
    title: 'Oven Temperature Converter — °C, °F, and Gas Mark Conversions',
    shortTitle: 'Oven Temperature Converter — °C,',
    description: 'Convert oven temperatures between Celsius, Fahrenheit, and Gas Mark instantly. Includes common oven temperature terms and fan oven adjustments.',
    category: 'Industrial & Trades',
    categorySlug: 'industrial',
    subCategory: 'Unit Converters',
    seoKeywords: ['oven temperature converter', 'gas mark to celsius', 'celsius to fahrenheit oven', 'oven temperature conversion', 'fan oven conversion', 'baking temperature converter', 'gas mark converter', 'cooking temperature converter'],
    schema: 'both',
    mathSolverExpression: '°C = (°F - 32) x 5/9 | Gas Mark | convert between °C, °F, Gas Mark',
    relatedPosts: ['btu-calculator-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['temperature-converter', 'cooking-converter', 'volume-converter'],
    loader: () => import('../industrial/oven-temperature-converter/index'),
  },
];
