import type { CalculatorEntry } from '../../types/calculator';

export const mathCalculators: CalculatorEntry[] = [
  {
    id: 'area-perimeter-calculator',
    title: 'Area & Perimeter Calculator — Circle, Rectangle, Triangle & More',
    shortTitle: 'Area & Perimeter',
    description: 'Calculate area and perimeter for seven shapes: circle, rectangle, square, triangle, trapezoid, parallelogram, and hexagon. Includes interactive diagrams.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Geometry',
    seoKeywords: ['area calculator', 'perimeter calculator', 'area of circle calculator', 'area of rectangle', 'area of triangle calculator', 'geometric shapes calculator'],
    schema: 'both',
    mathSolverExpression: 'A = πr² | P = 2πr | calculate area and perimeter of circles, rectangles, triangles, squares, trapezoids, parallelograms, and hexagons',
    lastVerified: '2026-05-15',
    relatedIds: ['circle-calculator', 'triangle-calculator', 'pythagorean-theorem-calculator', 'volume-surface-calculator'],
    relatedPosts: ['pythagorean-theorem-guide'],
    loader: () => import('../math/area-perimeter/index'),
  },
  {
    id: 'average-calculator',
    title: 'Average Calculator — Mean, Median & Data Summarizer',
    shortTitle: 'Average Calculator',
    description: 'Find mean, median, min, max, and sum from any data set. Smart parser strips dollar signs, commas, and percent signs so you can paste directly from spreadsheets.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['average calculator', 'mean calculator', 'median calculator', 'data average', 'statistical average', 'summarize data', 'central tendency'],
    schema: 'both',
    mathSolverExpression: "x̄ = (x₁ + x₂ + ... + xₙ) / n | arithmetic mean of a data set",
    lastVerified: '2026-05-17',
    relatedIds: ['mean-median-mode-calculator', 'standard-deviation-calculator', 'statistics-calculator', 'z-score-calculator'],
    relatedPosts: ['standard-deviation-statistics-guide', 'probability-math-guide'],
    loader: () => import('../math/average/index'),
  },
  {
    id: 'basic-calculator',
    title: 'Basic Calculator — Number Pad, History & Memory — Calculator',
    shortTitle: 'Basic Calc',
    description: 'A full-featured basic calculator with number pad, history tape, and order-of-operations support. Perfect for quick calculations with a running log.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['basic calculator', 'simple calculator', 'online calculator', 'free calculator', 'math calculator', 'history tape calculator', 'desktop calculator'],
    schema: 'both',
    mathSolverExpression: 'perform basic arithmetic operations (+, -, ×, /) with order-of-operations support',
    lastVerified: '2026-01-15',
    relatedIds: ['scientific-calculator', 'big-number-calculator', 'binary-hex-calculator', 'long-division-calculator', 'math-percentage-calculator'],
    relatedPosts: ['fractions-math-guide'],
    loader: () => import('../math/basic-calc/index'),
  },
  {
    id: 'big-number-calculator',
    title: 'Arbitrary Precision Calculator — Big Integer Arithmetic',
    shortTitle: 'Arbitrary Precision',
    description: 'Perform exact arbitrary-precision integer arithmetic with BigInt. Add, subtract, multiply, divide, and exponentiate numbers with hundreds of digits.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['arbitrary precision calculator', 'big integer arithmetic', 'bignum calculator', 'large number calculator', 'arbitrary precision arithmetic', 'bigint calculator', 'unlimited precision calculator', 'cryptography calculator'],
    schema: 'both',
    mathSolverExpression: 'arbitrary-precision integer arithmetic using JavaScript BigInt',
    lastVerified: '2026-05-17',
    relatedIds: ['basic-calculator', 'scientific-calculator', 'exponent-calculator', 'binary-hex-calculator'],
    relatedPosts: ['fractions-math-guide'],
    loader: () => import('../math/big-number/index'),
  },
  {
    id: 'binary-hex-calculator',
    title: 'Binary & Hex Calculator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Binary & Hex',
    description: 'Convert between Decimal, Binary, Hex, and Octal with positional value breakdown. Perform arithmetic and bitwise operations (AND, OR, XOR, NOT, shifts).',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['binary calculator', 'hex calculator', 'base converter', 'binary to decimal', 'hex to binary', 'octal converter', 'bitwise calculator', 'binary addition', 'binary AND OR XOR', 'number base conversion', 'hexadecimal calculator'],
    schema: 'both',
    mathSolverExpression: 'convert between bases or perform binary/hex arithmetic and bitwise operations',
    lastVerified: '2026-01-15',
    relatedIds: ['scientific-notation-calculator', 'big-number-calculator', 'basic-calculator', 'roman-numeral-converter', 'rounding-calculator'],
    loader: () => import('../math/binary-hex/index'),
  },
  {
    id: 'circle-calculator',
    title: 'Circle Calculator — Radius, Diameter, Circumference & Area Solver',
    shortTitle: 'Circle Calculator',
    description: 'Find radius, diameter, circumference, and area from any single known circle measurement. Shows reverse engineering steps for all four circle properties.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Geometry',
    seoKeywords: ['circle calculator', 'radius calculator', 'diameter calculator', 'circumference calculator', 'area of circle calculator', 'find radius from circumference', 'circle measurements'],
    schema: 'both',
    mathSolverExpression: 'calculate radius, diameter, circumference, or area of a circle given any one measurement',
    lastVerified: '2026-05-17',
    relatedIds: ['area-perimeter-calculator', 'triangle-calculator', 'volume-surface-calculator', 'pythagorean-theorem-calculator'],
    relatedPosts: ['pythagorean-theorem-guide'],
    loader: () => import('../math/circle/index'),
  },
  {
    id: 'common-factor-calculator',
    title: 'Common Factor Calculator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Common Factors',
    description: 'Find all common factors shared by two numbers. Lists every divisor that divides both numbers evenly, with the Greatest Common Factor (GCF) highlighted.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['common factor calculator', 'common factors', 'greatest common factor', 'shared divisors', 'factor comparison', 'GCF calculator'],
    schema: 'both',
    mathSolverExpression: 'find all common factors shared by two integers',
    lastVerified: '2026-01-15',
    relatedIds: ['factor-calculator', 'gcf-calculator', 'lcm-calculator', 'prime-factorization-calculator'],
    loader: () => import('../math/common-factor/index'),
  },
  {
    id: 'confidence-interval-calculator',
    title: 'Confidence Interval Calculator — Free Online Calculator & Guide',
    shortTitle: 'Confidence Interval',
    description: 'Calculate confidence intervals for a population mean. Breaks out the Margin of Error (MOE), critical Z-value, and standard error.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['confidence interval calculator', 'margin of error calculator', 'CI calculator', 'confidence level calculator', 'Z-value calculator', 'MOE calculator', 'statistical inference'],
    schema: 'both',
    mathSolverExpression: 'CI = x̄ ± Z × (σ/√n) | confidence interval for population mean',
    lastVerified: '2026-01-15',
    relatedIds: ['z-score-calculator', 'p-value-calculator', 'sample-size-calculator', 'statistics-calculator', 'standard-deviation-calculator'],
    relatedPosts: ['probability-math-guide', 'standard-deviation-statistics-guide'],
    loader: () => import('../math/confidence-interval/index'),
  },
  {
    id: 'conversion-calculator',
    title: 'Conversion Calculator — Convert Weight, Length & Temperature',
    shortTitle: 'Conversion',
    description: 'Convert between hundreds of units across 8 categories including weight, length, temperature, volume, area, speed, and currency.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['unit converter', 'conversion calculator', 'metric converter', 'inches to cm', 'lbs to kg', 'fahrenheit to celsius', 'temperature converter', 'length converter', 'weight converter', 'currency converter'],
    schema: 'both',
    mathSolverExpression: 'Convert between units using base-unit standardization and conversion factors',
    lastVerified: '2026-05-17',
    relatedIds: ['scientific-notation-calculator', 'fraction-to-decimal-calculator', 'binary-hex-calculator', 'time-zone-calculator'],
    relatedPosts: ['industrial-unit-converter-guide', 'fractions-math-guide'],
    loader: () => import('../math/conversion/index'),
  },
  {
    id: 'date-calculator',
    title: 'Date Calculator — Add & Subtract Days, Weeks, Months & Business Days',
    shortTitle: 'Date Calculator',
    description: 'Add or subtract years, months, weeks, and days from any date. Includes a business-days-only mode that skips weekends, leap year handling, and month-end.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['date calculator', 'add days calculator', 'business days calculator', 'date math', 'days from date', 'project deadline calculator', '90 days from today', 'weekday calculator', 'due date calculator', 'leap year calculator'],
    schema: 'both',
    mathSolverExpression: 'Result = StartDate ± (Years + Months + Weeks + Days)',
    lastVerified: '2026-05-18',
    relatedIds: ['time-duration-calculator', 'day-counter-calculator', 'day-of-week-calculator', 'time-calculator'],
    relatedPosts: ['age-calculator-guide'],
    loader: () => import('../math/date/index'),
  },
  {
    id: 'distance-calculator',
    title: 'Distance Calculator — Euclidean Distance in 1D, 2D & 3D Space',
    shortTitle: 'Distance Calculator',
    description: 'Calculate the Euclidean distance between two points in 1D, 2D, or 3D space. Shows the distance formula, step-by-step calculation, midpoint, and slope.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['distance calculator', 'distance formula calculator', 'distance between two points', '2D distance', '3D distance', 'midpoint calculator', 'Euclidean distance', 'Pythagorean distance', 'coordinate geometry'],
    schema: 'both',
    mathSolverExpression: 'd = √((x₂−x₁)²+(y₂−y₁)²) | distance between two points in 1D, 2D, or 3D',
    lastVerified: '2026-05-18',
    relatedIds: ['slope-calculator', 'pythagorean-theorem-calculator', 'triangle-calculator', 'quadratic-equation-calculator'],
    loader: () => import('../math/distance/index'),
  },
  {
    id: 'exponent-calculator',
    title: 'Exponent Calculator — Powers, Roots & Scientific Notation for Any Base',
    shortTitle: 'Exponent Calculator',
    description: 'Raise any base to any power including negative, fractional, and decimal exponents. Shows expanded form, scientific notation, power-rule breakdown, and.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['exponent calculator', 'power calculator', 'exponentiation', 'calculate exponents', 'negative exponent calculator', 'fractional exponent', 'scientific notation exponent'],
    schema: 'both',
    mathSolverExpression: 'b^n where n is any real number exponent — compute powers, roots, and scientific notation',
    lastVerified: '2026-05-17',
    relatedIds: ['log-calculator', 'nth-root-calculator', 'scientific-notation-calculator', 'big-number-calculator', 'half-life-calculator'],
    relatedPosts: ['fractions-math-guide', 'probability-math-guide'],
    loader: () => import('../math/exponent/index'),
  },
  {
    id: 'factor-calculator',
    title: 'Factor Calculator — Find All Factors, Factor Pairs & Prime Check',
    shortTitle: 'Factor Calculator',
    description: 'Find all factors of any positive integer with a complete factor pairs table, total factor count, sum of factors, and primality test.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['factor calculator', 'factor pairs', 'prime factor finder', 'factor table', 'find factors', 'divisors calculator', 'factor list', 'factor pairs calculator', 'prime checker', 'perfect number calculator', 'deficient abundant calculator'],
    schema: 'both',
    mathSolverExpression: 'find all positive integer factors and factor pairs of n, classify as prime/composite/perfect/deficient/abundant',
    lastVerified: '2026-05-18',
    relatedIds: ['common-factor-calculator', 'gcf-calculator', 'lcm-calculator', 'prime-factorization-calculator'],
    loader: () => import('../math/factor/index'),
  },
  {
    id: 'fraction-calculator',
    title: 'Fraction Calculator — Add, Subtract, Multiply, Divide Fractions',
    shortTitle: 'Fraction Calculator',
    description: 'Add, subtract, multiply, and divide fractions with step-by-step solutions. Shows LCM for common denominators and simplifies using GCD.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['fraction calculator', 'add fractions', 'subtract fractions', 'multiply fractions', 'divide fractions', 'fraction solver', 'fraction arithmetic'],
    schema: 'both',
    mathSolverExpression: 'add, subtract, multiply, or divide fractions a/b and c/d',
    lastVerified: '2026-05-17',
    relatedIds: ['fraction-to-decimal-calculator', 'ratio-calculator', 'math-percentage-calculator', 'gcf-calculator', 'lcm-calculator'],
    relatedPosts: ['fractions-math-guide'],
    loader: () => import('../math/fraction/index'),
  },
  {
    id: 'fraction-to-decimal-calculator',
    title: 'Fraction to Decimal Converter — Free Online Calculator & Formula Guide',
    shortTitle: 'Fraction Converter',
    description: 'Convert fractions to decimals, decimals to fractions, and mixed numbers to decimals. Automatically simplifies fractions using GCD.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['fraction to decimal calculator', 'decimal to fraction calculator', 'fraction converter', 'simplify fractions calculator', 'mixed number converter', 'fraction decimal conversion'],
    schema: 'both',
    mathSolverExpression: 'a/b = a ÷ b | convert between fractions, decimals, and mixed numbers',
    relatedPosts: ['fractions-math-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['fraction-calculator', 'math-percentage-calculator', 'ratio-calculator', 'rounding-calculator'],
    loader: () => import('../math/fraction-to-decimal/index'),
  },
  {
    id: 'gcf-calculator',
    title: 'GCF Calculator — Greatest Common Factor with Euclidean Algorithm &',
    shortTitle: 'Greatest Common Factor',
    description: 'Find the Greatest Common Factor (also called GCD or HCF) of two numbers using both the Euclidean algorithm with step-by-step division and prime.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['GCF calculator', 'greatest common factor', 'greatest common divisor', 'GCD calculator', 'Euclidean algorithm', 'Venn diagram factors', 'prime factors GCF', 'highest common factor', 'HCF calculator', 'co-prime checker', 'fraction simplifier'],
    schema: 'both',
    mathSolverExpression: 'GCF(a, b) = largest positive integer dividing both a and b, computed via Euclidean algorithm and prime factorization',
    lastVerified: '2026-05-18',
    relatedIds: ['lcm-calculator', 'factor-calculator', 'common-factor-calculator', 'prime-factorization-calculator'],
    loader: () => import('../math/gcf/index'),
  },
  {
    id: 'gdp-calculator',
    title: 'GDP Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'GDP Calculator',
    description: 'Calculate Nominal and Real GDP using the expenditure approach: GDP = C + I + G + (X − M). Free online calculator with formula guide and step-by-step results.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['GDP calculator', 'Gross Domestic Product', 'nominal GDP', 'real GDP', 'GDP deflator', 'economic calculator', 'expenditure approach', 'C+I+G+(X-M)', 'macroeconomics'],
    schema: 'both',
    mathSolverExpression: 'GDP = C + I + G + (X − M) | Real GDP = Nominal GDP / (Deflator × 100)',
    lastVerified: '2026-01-15',
    relatedIds: ['average-calculator', 'math-percentage-calculator', 'statistics-calculator', 'big-number-calculator'],
    loader: () => import('../math/gdp/index'),
  },
  {
    id: 'gpa-calculator',
    title: 'GPA Calculator — Weighted & Unweighted Grade Point Average',
    shortTitle: 'GPA Calculator',
    description: 'Compute weighted and unweighted GPA from course grades and credits. Target GPA mode shows the exact grades needed in remaining courses to reach your goal.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['GPA calculator', 'grade point average', 'weighted GPA', 'unweighted GPA', 'target GPA', 'college GPA', 'semester GPA', 'cumulative GPA', 'grade calculator'],
    schema: 'both',
    mathSolverExpression: 'GPA = Σ(GPA Value × Credits × Weight) / Σ(Credits)',
    lastVerified: '2026-05-18',
    relatedIds: ['grade-calculator', 'average-calculator', 'mean-median-mode-calculator', 'statistics-calculator'],
    relatedPosts: ['gpa-calculator-guide'],
    loader: () => import('../math/gpa/index'),
  },
  {
    id: 'grade-calculator',
    title: 'Final Grade Calculator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Final Grade',
    description: 'Determine what score you need on your final exam to achieve your target overall grade. Supports any current grade, desired grade, and exam weight combination.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['final grade calculator', 'exam score calculator', 'grade needed on final', 'final exam calculator', 'what do I need on my final', 'grade calculator'],
    schema: 'both',
    mathSolverExpression: 'Grade Needed = (Desired − Current × (1 − Weight)) / Weight',
    lastVerified: '2026-01-15',
    relatedIds: ['gpa-calculator', 'math-percentage-calculator', 'percent-error-calculator', 'average-calculator'],
    loader: () => import('../math/grade/index'),
  },
  {
    id: 'half-life-calculator',
    title: 'Half-Life Calculator — Exponential Decay, Carbon Dating & Drug',
    shortTitle: 'Half-Life Calculator — Exponential ',
    description: 'Calculate radioactive decay, carbon dating, and drug elimination using the exponential decay formula. Free, instant, and accurate.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['half-life calculator', 'radioactive decay calculator', 'half life formula', 'exponential decay', 'nuclear decay calculator', 'carbon dating calculator', 'Nt = N0 * (1/2)^(t/t1/2)', 'decay constant', 'drug half-life calculator', 'pharmacokinetics calculator', 'radioactive dating'],
    schema: 'both',
    mathSolverExpression: 'N(t) = N₀ · (½)^(t / t₁₂⁄₂)',
    lastVerified: '2026-05-18',
    relatedIds: ['exponent-calculator', 'log-calculator', 'scientific-calculator', 'probability-calculator', 'molarity-calculator'],
    relatedPosts: ['fractions-math-guide', 'probability-math-guide'],
    loader: () => import('../math/half-life/index'),
  },
  {
    id: 'height-calculator',
    title: 'Child Height Predictor — Mid-Parental Height (Tanner Method)',
    shortTitle: 'Height Predictor',
    description: "Predict a child's adult height using the Mid-Parental Height (Tanner) method with gender-specific adjustments. Includes expected range (±2 in), worked examples for pediatricians and parents, and guidance on when height predictions warrant medical follow-up.",
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['height calculator', 'child height predictor', 'mid-parental height', 'Tanner method', 'how tall will my child be', 'growth predictor', 'pediatric height estimate', 'adult height calculator', 'genetic height potential', 'child growth calculator'],
    schema: 'both',
    mathSolverExpression: 'Boy: (M+F+13)/2 | Girl: (M+F-13)/2 | Mid-Parental Height formula with ±2 inch expected range',
    lastVerified: '2026-05-18',
    relatedIds: ['weight-calculator', 'mass-calculator', 'density-calculator', 'average-calculator', 'bmi-calculator'],
    relatedPosts: ['bmi-calculator-guide'],
    loader: () => import('../math/height/index'),
  },
  {
    id: 'lcm-calculator',
    title: 'LCM Calculator — Least Common Multiple (GCD Method)',
    shortTitle: 'LCM Calculator',
    description: 'Find the Least Common Multiple of two or more numbers using both the efficient GCD-based formula and the prime factorization method side by side.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['LCM calculator', 'least common multiple', 'common multiple finder', 'LCM of numbers', 'prime factorization LCM', 'multiples list', 'lowest common multiple', 'LCM of 3 numbers', 'common denominator calculator', 'LCD calculator', 'LCM GCD relationship'],
    schema: 'both',
    mathSolverExpression: 'LCM(a, b) = (a × b) / GCD(a, b) for 2+ numbers via pairwise chaining — comprehensive LCM calculation with two solution methods',
    lastVerified: '2026-05-18',
    relatedIds: ['gcf-calculator', 'factor-calculator', 'common-factor-calculator', 'prime-factorization-calculator'],
    loader: () => import('../math/lcm/index'),
  },
  {
    id: 'log-calculator',
    title: 'Logarithm Calculator — Custom Base, Natural Log, Common Log &',
    shortTitle: 'Log Calculator',
    description: 'Calculate logarithms in any custom base with the change of base formula explained step-by-step. Free, instant, and accurate.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['log calculator', 'logarithm calculator', 'custom base log', 'change of base formula', 'log base 2', 'natural log calculator', 'log base 10'],
    schema: 'both',
    mathSolverExpression: 'log base b of x',
    lastVerified: '2026-05-17',
    relatedIds: ['exponent-calculator', 'nth-root-calculator', 'scientific-calculator', 'scientific-notation-calculator'],
    relatedPosts: ['fractions-math-guide', 'probability-math-guide'],
    loader: () => import('../math/log/index'),
  },
  {
    id: 'long-division-calculator',
    title: 'Long Division Calculator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Long Division',
    description: 'Perform long division with the traditional tableau format. Shows each step — divide, multiply, subtract, bring down — just like the classroom method.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['long division calculator', 'division tableau', 'long division steps', 'traditional division', 'math division solver', 'quotient remainder calculator', 'divide step by step'],
    schema: 'both',
    mathSolverExpression: 'dividend ÷ divisor = quotient + remainder/divisor | long division',
    lastVerified: '2026-01-15',
    relatedIds: ['basic-calculator', 'fraction-calculator', 'big-number-calculator', 'rounding-calculator'],
    loader: () => import('../math/long-division/index'),
  },
  {
    id: 'math-percentage-calculator',
    title: 'Percentage Calculator — Find Percentages of Any Number',
    shortTitle: 'Percentage',
    description: 'Calculate percentages in five different ways: what is X% of Y, X is what percent of Y, percent change, add or subtract a percentage.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['percentage calculator', 'percent calculator', 'find percentage', 'percent change calculator', 'percentage increase', 'percentage decrease', 'tip calculator'],
    schema: 'both',
    mathSolverExpression: 'what is X% of Y? X is what percent of Y? percent change from X to Y',
    lastVerified: '2026-01-15',
    relatedPosts: ['percentage-calculator-complete-guide'],
    relatedIds: ['percent-error-calculator', 'fraction-calculator', 'ratio-calculator', 'grade-calculator', 'gpa-calculator'],
    loader: () => import('../math/percentage/index'),
  },
  {
    id: 'matrix-calculator',
    title: 'Matrix Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Matrix Calculator',
    description: 'Calculate the determinant and inverse of square matrices from 2×2 to 5×5. Shows step-by-step calculation with LaTeX-style formatting for college assignments.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['matrix calculator', 'determinant calculator', 'matrix inverse', '2x2 determinant', '3x3 determinant', 'linear algebra calculator', 'matrix solver', 'invert matrix'],
    schema: 'both',
    mathSolverExpression: 'det(A) and A⁻¹ for n×n matrices | linear algebra',
    lastVerified: '2026-01-15',
    relatedIds: ['quadratic-equation-calculator', 'distance-calculator', 'basic-calculator', 'scientific-calculator'],
    loader: () => import('../math/matrix/index'),
  },
  {
    id: 'mean-median-mode-calculator',
    title: 'Mean, Median, Mode & Range Calculator — Central Tendency Made Simple',
    shortTitle: 'Mean Median Mode',
    description: 'Calculate the mean, median, mode, sum, and range from any data set with step-by-step median breakdown for even-numbered datasets.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['mean calculator', 'median calculator', 'mode calculator', 'range calculator', 'mean median mode calculator', 'average calculator', 'descriptive statistics', 'central tendency'],
    schema: 'both',
    mathSolverExpression: 'x̄ = Σx/n | median = middle value (sorted) | range = max − min',
    lastVerified: '2026-05-17',
    relatedIds: ['average-calculator', 'standard-deviation-calculator', 'statistics-calculator', 'z-score-calculator'],
    relatedPosts: ['standard-deviation-statistics-guide', 'probability-math-guide'],
    loader: () => import('../math/mean-median-mode/index'),
  },
  {
    id: 'number-sequence-calculator',
    title: 'Number Sequence Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'Number Sequences',
    description: 'Identify arithmetic, geometric, and Fibonacci sequences. Find common difference, common ratio, nth-term formula, and compute next terms.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['number sequence calculator', 'sequence solver', 'arithmetic sequence', 'geometric sequence', 'Fibonacci sequence', 'nth term calculator', 'find next term'],
    schema: 'both',
    mathSolverExpression: 'identify the sequence pattern and find the nth term',
    lastVerified: '2026-01-15',
    relatedIds: ['probability-calculator', 'permutation-combination-calculator', 'exponent-calculator', 'factor-calculator'],
    loader: () => import('../math/number-sequence/index'),
  },
  {
    id: 'nth-root-calculator',
    title: 'Root Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Root Calculator',
    description: 'Calculate any nth root — square roots, cube roots, and beyond. Shows both radical form and fractional exponent equivalent with step-by-step verification.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['root calculator', 'nth root', 'square root calculator', 'cube root calculator', 'radical calculator', 'fractional exponent', 'x^(1/n) calculator', 'nth root solver'],
    schema: 'both',
    mathSolverExpression: 'ⁿ√x = x^(1/n) | nth root of a number',
    lastVerified: '2026-01-15',
    relatedIds: ['exponent-calculator', 'log-calculator', 'scientific-calculator', 'scientific-notation-calculator'],
    loader: () => import('../math/nth-root/index'),
  },
  {
    id: 'p-value-calculator',
    title: 'P-value Calculator — Statistical Significance from Z & T Test Scores',
    shortTitle: 'P-value Calculator — Statistical Si',
    description: 'Compute p-values from Z-scores or T-scores for one-tailed and two-tailed hypothesis tests. Free online calculator with formula guide and step-by-step results.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['p-value calculator', 'statistical significance', 'hypothesis testing', 'Z-test p-value', 'T-test p-value', 'reject null hypothesis', 'p-value from z-score'],
    schema: 'both',
    mathSolverExpression: 'p = P(Z ≥ |z|) for two-tailed | p = P(Z ≥ z) for one-tailed | p-value from test statistic for hypothesis testing',
    lastVerified: '2026-05-17',
    relatedIds: ['z-score-calculator', 'confidence-interval-calculator', 'sample-size-calculator', 'statistics-calculator', 'correlation-calculator'],
    relatedPosts: ['probability-math-guide', 'standard-deviation-statistics-guide'],
    loader: () => import('../math/p-value/index'),
  },
  {
    id: 'percent-error-calculator',
    title: 'Percent Error Calculator — Lab Accuracy & Experimental Precision',
    shortTitle: 'Percent Error',
    description: 'Calculate percent error, absolute error, signed error, accuracy, and relative error between accepted and experimental values.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['percent error calculator', 'percentage error calculator', 'accepted value vs experimental', 'lab error calculator', 'chemistry error calculator', 'relative error calculator'],
    schema: 'both',
    mathSolverExpression: 'percent error = |(accepted - experimental) / accepted| * 100%',
    lastVerified: '2026-05-17',
    relatedIds: ['math-percentage-calculator', 'fraction-calculator', 'ratio-calculator', 'statistics-calculator'],
    relatedPosts: ['standard-deviation-statistics-guide', 'probability-math-guide'],
    loader: () => import('../math/percent-error/index'),
  },
  {
    id: 'permutation-combination-calculator',
    title: 'Permutation and Combination Calculator — Free Online Calculator',
    shortTitle: 'Permutations & Combos',
    description: 'Calculate permutations (nPr) and combinations (nCr) with step-by-step factorial breakdown. Toggle between order matters vs.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['permutation calculator', 'combination calculator', 'nPr calculator', 'nCr calculator', 'permutation vs combination', 'factorial calculator', 'combinatorics'],
    schema: 'both',
    mathSolverExpression: 'P(n,r) = n!/(n−r)! | C(n,r) = n!/(r!(n−r)!)',
    relatedPosts: ['fractions-math-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['probability-calculator', 'number-sequence-calculator', 'factor-calculator', 'statistics-calculator'],
    loader: () => import('../math/permutation-combination/index'),
  },
  {
    id: 'prime-factorization-calculator',
    title: 'Prime Factorization Calculator — Factor Tree & Prime Decomposition',
    shortTitle: 'Prime Factors',
    description: 'Break any integer into its unique prime factors with an interactive factor tree. Detects perfect squares, cubes, and handles numbers up to one million.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['prime factorization calculator', 'prime factors', 'factor tree', 'prime number decomposition', 'prime factor tree', 'fundamental theorem of arithmetic', 'prime factorization', 'factor tree generator', 'perfect square test', 'RSA factorization', 'unique factorization', 'prime factor exponents'],
    schema: 'both',
    mathSolverExpression: 'n = p₁^a × p₂^b × p₃^c | unique prime factorization of any integer via Fundamental Theorem of Arithmetic with factor tree',
    lastVerified: '2026-05-18',
    relatedIds: ['factor-calculator', 'common-factor-calculator', 'gcf-calculator', 'lcm-calculator'],
    relatedPosts: ['fractions-math-guide', 'probability-math-guide'],
    loader: () => import('../math/prime-factorization/index'),
  },
  {
    id: 'probability-calculator',
    title: 'Probability Calculator — Joint, Union & Conditional Event',
    shortTitle: 'Probability',
    description: 'Compute joint (A∩B), union (A∪B), conditional P(A|B), and complement probabilities for independent or mutually exclusive events with Venn diagram.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['probability calculator', 'P(A and B)', 'P(A or B)', 'conditional probability', 'independent events', 'mutually exclusive events', 'venn diagram', 'addition rule', 'complement rule', 'P(A|B)'],
    schema: 'both',
    mathSolverExpression: "P(A∪B) = P(A) + P(B) - P(A∩B) | P(A|B) = P(A∩B)/P(B) | compute joint, union, conditional, and complement probabilities",
    lastVerified: '2026-05-17',
    relatedIds: ['permutation-combination-calculator', 'number-sequence-calculator', 'z-score-calculator', 'statistics-calculator', 'p-value-calculator'],
    relatedPosts: ['betting-odds-explained-guide', 'probability-math-guide', 'standard-deviation-statistics-guide'],
    loader: () => import('../math/probability/index'),
  },
  {
    id: 'pythagorean-theorem-calculator',
    title: 'Right Triangle Calculator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Right Triangle',
    description: 'Solve right triangles using the Pythagorean theorem and SOH CAH TOA trigonometry. Find sides, angles, area, and perimeter with a dynamic SVG triangle and.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Geometry',
    seoKeywords: ['right triangle calculator', 'pythagorean theorem calculator', 'hypotenuse calculator', 'SOH CAH TOA', 'triangle angles calculator', 'triangle solver', 'a squared plus b squared', 'pythagorean triples'],
    schema: 'both',
    mathSolverExpression: 'a² + b² = c² | solve right triangle sides, angles, and apply SOH CAH TOA',
    lastVerified: '2026-01-15',
    relatedIds: ['triangle-calculator', 'distance-calculator', 'slope-calculator', 'area-perimeter-calculator'],
    relatedPosts: ['pythagorean-theorem-guide'],
    loader: () => import('../math/pythagorean/index'),
  },
  {
    id: 'quadratic-equation-calculator',
    title: 'Quadratic Equation Solver — Find Roots, Vertex & Discriminant',
    shortTitle: 'Quadratic Solver',
    description: 'Solve any quadratic ax²+bx+c=0 with the quadratic formula. Get real or complex roots, discriminant, vertex, axis of symmetry, factored form, and Vieta.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['quadratic equation calculator', 'quadratic formula calculator', 'solve quadratic equation', 'quadratic solver', 'roots of quadratic equation', 'discriminant calculator', 'vertex calculator', 'factored form', 'parabola calculator'],
    schema: 'both',
    mathSolverExpression: 'x = (−b ± √(b²−4ac)) / (2a) | solve quadratic equations, find vertex, discriminant, axis of symmetry',
    lastVerified: '2026-05-17',
    relatedIds: ['distance-calculator', 'slope-calculator', 'pythagorean-theorem-calculator', 'matrix-calculator', 'equation-solver', 'factoring-calculator'],
    relatedPosts: ['pythagorean-theorem-guide', 'fractions-math-guide'],
    loader: () => import('../math/quadratic/index'),
  },
  {
    id: 'random-number-generator',
    title: 'Random Number Generator — Cryptographically Secure RNG with Web',
    shortTitle: 'Random Numbers',
    description: 'Generate cryptographically secure random numbers using Web Crypto API. Customizable range, count, decimal precision, unique values, and batch statistics.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['random number generator', 'random number', 'RNG', 'secure random numbers', 'crypto random', 'randomizer', 'lottery number generator'],
    schema: 'both',
    mathSolverExpression: 'generate cryptographically secure random integers within a specified range',
    lastVerified: '2026-05-18',
    relatedIds: ['probability-calculator', 'statistics-calculator', 'dice-roller', 'number-sequence-calculator'],
    loader: () => import('../math/random-number/index'),
  },
  {
    id: 'ratio-calculator',
    title: 'Ratio Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Ratio Calculator',
    description: 'Simplify ratios, find missing values in proportions, and scale dimensions. Includes common aspect ratio presets (16:9, 4:3, 1:1, 21:9) for digital.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['ratio calculator', 'proportion calculator', 'aspect ratio calculator', 'simplify ratio', '16:9 calculator', 'ratio solver', 'cross multiplication', 'scale calculator'],
    schema: 'both',
    mathSolverExpression: 'A/B = C/D | solve proportions and simplify ratios',
    lastVerified: '2026-01-15',
    relatedIds: ['fraction-calculator', 'math-percentage-calculator', 'fraction-to-decimal-calculator', 'rounding-calculator'],
    loader: () => import('../math/ratio/index'),
  },
  {
    id: 'rounding-calculator',
    title: 'Rounding Calculator — Round to Any Place Value with Number Line',
    shortTitle: 'Rounding Calculator',
    description: 'Round numbers to the nearest million, thousand, hundred, ten, unit, tenth, hundredth, thousandth, or ten-thousandth. Free, instant, and accurate.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['rounding calculator', 'round numbers', 'round to nearest ten', 'round to nearest hundred', 'rounding tool', 'number line rounding', 'estimation calculator', 'round to nearest tenth', 'round to nearest hundredth', 'midpoint rounding', 'round half up', 'bankers rounding comparison', 'significant figures'],
    schema: 'both',
    mathSolverExpression: 'round(x) to the specified place value using standard round-half-up convention with visual number line',
    relatedPosts: ['fractions-math-guide'],
    lastVerified: '2026-05-18',
    relatedIds: ['scientific-notation-calculator', 'math-percentage-calculator', 'fraction-to-decimal-calculator', 'binary-hex-calculator'],
    loader: () => import('../math/rounding/index'),
  },
  {
    id: 'sample-size-calculator',
    title: 'Sample Size Calculator — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Sample Size',
    description: 'Determine the ideal sample size for surveys and research studies. Adjust for population size, confidence level, and margin of error.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['sample size calculator', 'survey sample size', 'margin of error calculator', 'confidence level calculator', 'statistical significance', 'market research sample size'],
    schema: 'both',
    mathSolverExpression: 'n = z²p(1−p)/e² | required sample size for a given confidence level and margin of error',
    lastVerified: '2026-01-15',
    relatedIds: ['confidence-interval-calculator', 'z-score-calculator', 'p-value-calculator', 'statistics-calculator'],
    loader: () => import('../math/sample-size/index'),
  },
  {
    id: 'scientific-calculator',
    title: 'Online Scientific Calculator — Trig, Log, Memory Functions',
    shortTitle: 'Scientific Calc',
    description: 'Full-featured online scientific calculator with trigonometric functions, logarithms, memory operations, and calculation history.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['scientific calculator', 'math calculator', 'trig calculator', 'online scientific calculator', 'free calculator', 'memory calculator', 'math solver'],
    schema: 'both',
    mathSolverExpression: 'perform trigonometric, logarithmic, exponential, and other advanced mathematical functions',
    lastVerified: '2026-05-17',
    relatedIds: ['basic-calculator', 'big-number-calculator', 'log-calculator', 'exponent-calculator', 'matrix-calculator'],
    relatedPosts: ['fractions-math-guide'],
    loader: () => import('../math/scientific/index'),
  },
  {
    id: 'scientific-notation-calculator',
    title: 'Scientific Notation Calculator — Free Online Calculator & Guide',
    shortTitle: 'Sci Notation',
    description: 'Convert between decimal and scientific notation. Learn how the decimal point jumps left or right with an interactive movement visualization.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['scientific notation calculator', 'decimal to scientific notation', 'scientific to decimal', 'E notation', 'significant figures', 'powers of 10', 'standard form calculator'],
    schema: 'both',
    mathSolverExpression: 'a × 10ⁿ | convert between decimal and scientific notation',
    lastVerified: '2026-01-15',
    relatedIds: ['exponent-calculator', 'rounding-calculator', 'binary-hex-calculator', 'scientific-calculator'],
    loader: () => import('../math/scientific-notation/index'),
  },
  {
    id: 'slope-calculator',
    title: 'Slope Calculator — Find Line Slope & Equation from Two Points',
    shortTitle: 'Slope Calculator',
    description: 'Calculate slope between two points with all three equation forms, distance, midpoint, and angle. Includes simplified fraction and interactive coordinate graph.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['slope calculator', 'find slope between two points', 'line equation calculator', 'slope intercept form calculator', 'point slope form calculator', 'rise over run calculator', 'standard form of a line', 'slope fraction', 'linear equation calculator'],
    schema: 'both',
    mathSolverExpression: 'm = (y₂ − y₁) / (x₂ − x₁) | y = mx + b | y − y₁ = m(x − x₁) | Ax + By = C | calculate slope, line equation forms, intercept, and distance between two points',
    lastVerified: '2026-05-17',
    relatedIds: ['distance-calculator', 'pythagorean-theorem-calculator', 'quadratic-equation-calculator', 'equation-solver', 'linear-functions-calculator'],
    relatedPosts: ['pythagorean-theorem-guide'],
    loader: () => import('../math/slope/index'),
  },
  {
    id: 'standard-deviation-calculator',
    title: 'Standard Deviation Calculator — Variance, Mean & Coefficient of',
    shortTitle: 'Standard Deviation',
    description: 'Compute standard deviation, variance, mean, median, range, and coefficient of variation from any dataset. Free online calculator with step-by-step results.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['standard deviation calculator', 'variance calculator', 'statistics calculator', 'mean median calculator', 'sample standard deviation', 'population standard deviation'],
    schema: 'both',
    mathSolverExpression: 'σ = √(Σ(xᵢ−x̄)²/n) | s = √(Σ(xᵢ−x̄)²/(n−1)) | population or sample standard deviation',
    lastVerified: '2026-05-17',
    relatedIds: ['average-calculator', 'mean-median-mode-calculator', 'statistics-calculator', 'z-score-calculator', 'confidence-interval-calculator'],
    relatedPosts: ['gpa-calculator-guide', 'probability-math-guide', 'standard-deviation-statistics-guide'],
    loader: () => import('../math/standard-deviation/index'),
  },
  {
    id: 'statistics-calculator',
    title: 'Statistics Calculator — Box Plot, Quartiles, IQR & Outlier Detector',
    shortTitle: 'Statistics',
    description: 'Comprehensive descriptive statistics calculator with a dynamic box-and-whisker plot. Computes the five-number summary, quartiles, IQR, standard deviation.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['statistics calculator', 'box and whisker plot', 'descriptive statistics', 'quartile calculator', 'IQR calculator', 'outlier detector', 'five number summary', 'data analysis'],
    schema: 'both',
    mathSolverExpression: 'Q1, Q2, Q3, IQR = Q3−Q1 | outliers = x < Q1−1.5×IQR or x > Q3+1.5×IQR',
    lastVerified: '2026-05-17',
    relatedIds: ['average-calculator', 'mean-median-mode-calculator', 'standard-deviation-calculator', 'z-score-calculator', 'confidence-interval-calculator'],
    relatedPosts: ['standard-deviation-statistics-guide', 'probability-math-guide'],
    loader: () => import('../math/statistics/index'),
  },
  {
    id: 'time-calculator',
    title: 'Time & Hours Calculator — Work Shift Time, Breaks & Gross Pay',
    shortTitle: 'Time & Hours',
    description: 'Calculate time differences between start and end times with automatic overnight detection, break deductions, and optional gross pay computation.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['time calculator', 'hours calculator', 'time difference', 'work hours calculator', 'payroll hours', 'overtime calculator', 'timesheet calculator', 'hourly pay calculator', 'time card calculator', 'shift hours'],
    schema: 'both',
    mathSolverExpression: 'Total Time = EndTime − StartTime − Break | Gross Pay = Decimal Hours × Hourly Rate',
    lastVerified: '2026-05-18',
    relatedIds: ['time-duration-calculator', 'time-card-calculator', 'time-zone-calculator', 'date-calculator'],
    relatedPosts: ['age-calculator-guide', 'fractions-math-guide'],
    loader: () => import('../math/time/index'),
  },
  {
    id: 'time-card-calculator',
    title: 'Time Card Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Time Card Calculator',
    description: 'Track weekly work hours with day-by-day entries. Calculates regular and overtime hours, handles 12hr/24hr time formats, overnight shifts, and optional pay.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['time card calculator', 'work hours tracker', 'timesheet calculator', 'overtime calculator', 'weekly time card', 'payroll hours', 'lunch break deduction', 'work schedule tracker'],
    schema: 'both',
    mathSolverExpression: 'Hours = End − Start − Break | Overtime = Total − Threshold',
    lastVerified: '2026-01-15',
    relatedIds: ['time-calculator', 'time-duration-calculator', 'date-calculator', 'day-counter-calculator'],
    loader: () => import('../math/time-card/index'),
  },
  {
    id: 'time-zone-calculator',
    title: 'Time Zone Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Time Zone Calculator',
    description: 'Convert time between 24 time zones worldwide with business hours overlay. Green-yellow-gray color-coded grid shows the best meeting times across multiple.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['time zone converter', 'world time', 'meeting time finder', 'time zone map', 'EST to PST', 'UTC converter', 'business hours overlay', 'international call time', 'global time'],
    schema: 'both',
    mathSolverExpression: 'TargetTime = SourceTime − SourceOffset + TargetOffset',
    lastVerified: '2026-01-15',
    relatedIds: ['time-calculator', 'time-duration-calculator', 'date-calculator', 'conversion-calculator'],
    relatedPosts: ['age-calculator-guide', 'fractions-math-guide'],
    loader: () => import('../math/time-zone/index'),
  },
  {
    id: 'triangle-calculator',
    title: 'Triangle Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Triangle Solver',
    description: 'Solve any triangle using SSS, SAS, or ASA input modes. Computes all sides, angles, area, and perimeter with dynamic SVG visualization.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Geometry',
    seoKeywords: ['triangle calculator', 'triangle solver', 'SSS triangle', 'SAS triangle', 'ASA triangle', 'law of cosines', 'law of sines', 'triangle area calculator', 'triangle angles'],
    schema: 'both',
    mathSolverExpression: 'solve triangle given three sides or two sides and included angle or two angles and included side',
    relatedPosts: ['pythagorean-theorem-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['pythagorean-theorem-calculator', 'area-perimeter-calculator', 'circle-calculator', 'volume-surface-calculator'],
    loader: () => import('../math/triangle/index'),
  },
  {
    id: 'volume-surface-calculator',
    title: 'Volume & Surface Area Calculator — Free Online Calculator & Guide',
    shortTitle: 'Volume & Surface Area',
    description: 'Calculate volume and surface area of spheres, cubes, rectangular prisms, cylinders, cones, and pyramids. Free, instant, and accurate.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Geometry',
    seoKeywords: ['volume calculator', 'surface area calculator', 'volume of sphere calculator', 'cylinder volume calculator', 'cone volume calculator', '3d shapes calculator', 'shape net'],
    schema: 'both',
    mathSolverExpression: 'V = ⁴⁄₃πr³ (sphere) | V = πr²h (cylinder) | calculate volume and surface area of 3D shapes',
    lastVerified: '2026-01-15',
    relatedIds: ['area-perimeter-calculator', 'circle-calculator', 'triangle-calculator', 'pythagorean-theorem-calculator'],
    loader: () => import('../math/volume-surface/index'),
  },
  {
    id: 'z-score-calculator',
    title: 'Z-Score Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Z-Score Calculator — Free Online Ca',
    description: 'Calculate the Z-score from a raw score, population mean, and standard deviation. Visualizes the result on a standard normal distribution curve with shaded.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['z-score calculator', 'standard score calculator', 'z-score table lookup', 'normal distribution calculator', 'bell curve calculator', 'percentile calculator', 'standard normal distribution'],
    schema: 'both',
    mathSolverExpression: 'z = (x − μ) / σ | standardize a raw score on the normal distribution',
    lastVerified: '2026-01-15',
    relatedIds: ['p-value-calculator', 'standard-deviation-calculator', 'confidence-interval-calculator', 'statistics-calculator'],
    loader: () => import('../math/z-score/index'),
  },
  {
    id: 'roman-numeral-converter',
    title: 'Roman Numeral Converter — Quick & Accurate Online Calculator & Guide',
    shortTitle: 'Roman Numerals',
    description: 'Convert numbers to Roman numerals and back, including date conversion. Features subtractive notation breakdown and tattoo verification.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['roman numeral converter', 'number to roman', 'roman to number', 'roman numeral date', 'MCMXCIV', 'roman numeral tattoo', 'numeral conversion'],
    schema: 'both',
    mathSolverExpression: 'I=1, V=5, X=10, L=50, C=100, D=500, M=1000',
    relatedPosts: ['fractions-math-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['binary-hex-calculator', 'scientific-notation-calculator', 'date-calculator', 'number-sequence-calculator'],
    loader: () => import('../math/roman-numeral/index'),
  },
  {
    id: 'density-calculator',
    title: 'Density Calculator — Solve Density, Mass & Volume with Formula',
    shortTitle: 'Density Calculator',
    description: 'Calculate density, mass, or volume using ρ = m/V with the formula triangle mnemonic. Includes unit conversion between g/cm³, kg/m³, and lbs/ft³ with.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['density calculator', 'density formula', 'mass volume density', 'density triangle', 'specific gravity calculator', 'ρ=m/V', 'density converter', 'material density reference', 'buoyancy calculator'],
    schema: 'both',
    mathSolverExpression: 'ρ = m / V | m = ρ × V | V = m / ρ | calculate density, mass, or volume',
    lastVerified: '2026-05-18',
    relatedIds: ['mass-calculator', 'weight-calculator', 'speed-calculator', 'molarity-calculator'],
    loader: () => import('../math/density/index'),
  },
  {
    id: 'mass-calculator',
    title: 'Mass Calculator — Free Online Calculator with Step-by-Step Guide',
    shortTitle: 'Mass Calculator',
    description: 'Calculate mass, density, or volume using m = ρ × V. Shows planetary weight comparison on Earth, Moon, Mars, and Jupiter with unit conversions.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['mass calculator', 'mass from density', 'density volume mass', 'weight on other planets', 'planetary weight', 'mass formula', 'ρV triangle'],
    schema: 'both',
    mathSolverExpression: 'm = ρ × V | mass from density and volume with planetary weight comparison',
    lastVerified: '2026-01-15',
    relatedIds: ['density-calculator', 'weight-calculator', 'speed-calculator', 'molarity-calculator'],
    loader: () => import('../math/mass/index'),
  },
  {
    id: 'weight-calculator',
    title: 'Weight Calculator — W = m × g with Planetary Gravity Comparison',
    shortTitle: 'Weight Calculator',
    description: 'Calculate weight, mass, or gravitational acceleration using the W = mg formula. Compare weight across Earth, Moon, Mars, Jupiter, and the Sun.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['weight calculator', 'W=mg', 'mass to weight', 'gravity calculator', 'weight on planets', 'Newton to lbf', 'force calculator', 'weight on moon', 'weight on mars', 'mass vs weight', 'gravitational acceleration calculator'],
    schema: 'both',
    mathSolverExpression: 'W = m × g | m = W / g | g = W / m | calculate weight, mass, or gravity with planetary comparison',
    relatedPosts: ['pythagorean-theorem-guide'],
    lastVerified: '2026-05-18',
    relatedIds: ['density-calculator', 'mass-calculator', 'speed-calculator', 'height-calculator', 'force-calculator'],
    loader: () => import('../math/weight/index'),
  },
  {
    id: 'speed-calculator',
    title: 'Speed Calculator — S = D/T with Pace, Unit Conversion & Race Planning',
    shortTitle: 'Speed Calculator',
    description: 'Calculate speed, distance, or time using S = D/T. Converts between mph, km/h, m/s, and knots with simultaneous display. Free, instant, and accurate.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['speed calculator', 'distance time speed', 'pace calculator', 'mph to kmh', 'speed converter', 'running pace', 'S=DT formula', 'knots to mph', 'marathon pace calculator', 'cycling speed', 'average speed calculator', 'race time predictor'],
    schema: 'both',
    mathSolverExpression: 'S = D / T | D = S × T | T = D / S | calculate speed, distance, or time with pace and multi-unit conversion',
    lastVerified: '2026-05-18',
    relatedIds: ['distance-calculator', 'density-calculator', 'mass-calculator', 'time-calculator', 'conversion-calculator', 'pace-calculator'],
    loader: () => import('../math/speed/index'),
  },
  {
    id: 'molarity-calculator',
    title: 'Molarity Calculator — Calculate Solution Concentration in mol/L',
    shortTitle: 'Molarity Calculator',
    description: 'Calculate molarity, mass, or volume of chemical solutions. Auto-detects compounds and shows step-by-step derivation of moles and concentration.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['molarity calculator', 'solution concentration', 'moles per liter', 'chemistry calculator', 'molar concentration', 'M=n/V', 'solution preparation'],
    schema: 'both',
    mathSolverExpression: 'M = n / V = (m / MM) / V | molar concentration of a solution',
    lastVerified: '2026-05-17',
    relatedIds: ['molecular-weight-calculator', 'density-calculator', 'mass-calculator', 'ph-calculator-math'],
    relatedPosts: ['fractions-math-guide', 'probability-math-guide'],
    loader: () => import('../math/molarity/index'),
  },
  {
    id: 'molecular-weight-calculator',
    title: 'Molecular Weight Calculator — Molar Mass from Formulas',
    shortTitle: 'Mol Weight',
    description: 'Calculate molecular weight from any chemical formula with element breakdown and mass percentage composition. Supports hydrates and parentheses.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['molecular weight calculator', 'molar mass', 'chemical formula parser', 'molecular mass', 'atomic weight calculator', 'composition percentage', 'hydrate calculator'],
    schema: 'both',
    mathSolverExpression: 'MW = Σ(atomic weight × count) | molecular weight from chemical formula',
    lastVerified: '2026-05-17',
    relatedIds: ['molarity-calculator', 'density-calculator', 'mass-calculator', 'ph-calculator-math'],
    relatedPosts: ['fractions-math-guide', 'standard-deviation-statistics-guide'],
    loader: () => import('../math/molecular-weight/index'),
  },
  {
    id: 'time-duration-calculator',
    title: 'Time Duration Calculator — Exact Hours, Days & Weeks Between Dates',
    shortTitle: 'Time Duration',
    description: 'Calculate the exact duration between two dates and times down to the second. Supports business days mode and multiple output formats for project.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['time duration calculator', 'time between dates', 'hours between dates', 'business days calculator', 'elapsed time calculator', 'project duration', 'date time difference'],
    schema: 'both',
    mathSolverExpression: 'Duration = EndDateTime - StartDateTime | Calculate elapsed time between two date-time values',
    lastVerified: '2026-05-18',
    relatedIds: ['date-calculator', 'day-counter-calculator', 'time-calculator', 'day-of-week-calculator'],
    loader: () => import('../math/time-duration/index'),
  },
  {
    id: 'day-counter-calculator',
    title: 'Day Counter — Count Days Between Dates with Business Day Mode',
    shortTitle: 'Day Counter',
    description: 'Count the exact number of days between two dates with precision down to the day. Includes business days exclusion, end-date inclusion toggle, and.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['day counter', 'days between dates', 'date difference calculator', 'business days counter', 'days until date', 'date calculator', 'days since date', 'day count', 'working days between dates', 'calendar days'],
    schema: 'both',
    mathSolverExpression: 'Days = EndDate - StartDate | Count days between two dates with business day option',
    lastVerified: '2026-05-18',
    relatedIds: ['date-calculator', 'time-duration-calculator', 'day-of-week-calculator', 'time-calculator'],
    relatedPosts: ['age-calculator-guide'],
    loader: () => import('../math/day-counter/index'),
  },
  {
    id: 'day-of-week-calculator',
    title: 'Day of the Week Calculator — Free Online Calculator & Formula Guide',
    shortTitle: 'Day of Week',
    description: "Find the day of the week for any date using Zeller's congruence. Features a perpetual calendar algorithm explanation and historical context.",
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['day of week calculator', 'what day was I born', 'Zeller congruence', 'day of the week any date', 'perpetual calendar', 'day finder', 'historical day calculator'],
    schema: 'both',
    mathSolverExpression: "h = (q + ⌊13(m+1)/5⌋ + K + ⌊K/4⌋ + ⌊J/4⌋ - 2J) mod 7 | Zeller's congruence",
    lastVerified: '2026-01-15',
    relatedIds: ['date-calculator', 'day-counter-calculator', 'time-duration-calculator', 'roman-numeral-converter'],
    loader: () => import('../math/day-of-week/index'),
  },
  // dice-roller lives at /everyday/dice-roller/ (its natural home); the duplicate
  // /math/ entry was removed to avoid two URLs sharing identical content.
  {
    id: 'ph-calculator-math',
    title: 'pH Calculator — Convert Between pH, pOH, and Hydrogen Ion',
    shortTitle: 'pH Calculator',
    description: 'Calculate pH from hydrogen ion concentration, convert between pH and pOH, and classify solutions as acidic, basic, or neutral.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['ph calculator', 'ph to h+ concentration', 'poh calculator', 'acid base calculator', 'ph scale calculator', 'hydrogen ion concentration', 'chemistry calculator', 'h+ concentration calculator'],
    schema: 'both',
    mathSolverExpression: 'pH = -log₁₀[H⁺], pOH = 14 - pH',
    lastVerified: '2026-01-15',
    relatedIds: ['molarity-calculator', 'molecular-weight-calculator', 'log-calculator', 'scientific-calculator'],
    loader: () => import('../math/ph-calculator/index'),
  },
  {
    id: 'correlation-calculator',
    title: 'Correlation Calculator — Pearson Correlation Coefficient r',
    shortTitle: 'Correlation',
    description: 'Calculate the Pearson correlation coefficient between two variables. Shows r, r², strength, and direction with step-by-step work.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['correlation calculator', 'pearson correlation', 'correlation coefficient', 'r value calculator', 'correlation statistics', 'linear correlation', 'covariance calculator', 'correlation analysis'],
    schema: 'both',
    mathSolverExpression: 'r = (n∑xy - ∑x∑y) / √((n∑x² - (∑x)²)(n∑y² - (∑y)²))',
    relatedPosts: ['probability-math-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['standard-deviation-calculator', 'statistics-calculator', 'z-score-calculator', 'p-value-calculator'],
    loader: () => import('../math/correlation-calculator/index'),
  },
  {
    id: 'descriptive-stats',
    title: 'Descriptive Statistics Calculator — Mean, Median, Mode, IQR & More',
    shortTitle: 'Descriptive Stats',
    description: 'Compute key descriptive statistics for any dataset: mean, median, mode, range, variance, standard deviation, quartiles, and IQR.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Statistics',
    seoKeywords: ['descriptive statistics calculator', 'mean median mode calculator', 'standard deviation calculator', 'variance calculator', 'quartile calculator', 'iqr calculator', 'statistics summary', 'data summary calculator'],
    schema: 'both',
    mathSolverExpression: 'x̄ = ∑x/n, s = √(∑(x-x̄)²/(n-1))',
    lastVerified: '2026-01-15',
    relatedIds: ['statistics-calculator', 'mean-median-mode-calculator', 'standard-deviation-calculator', 'z-score-calculator'],
    loader: () => import('../math/descriptive-stats/index'),
  },
  {
    id: 'equation-solver',
    title: 'Equation Solver — Solve Linear & Quadratic Equations',
    shortTitle: 'Equation Solver',
    description: 'Solve linear (ax + b = 0) and quadratic (ax² + bx + c = 0) equations instantly. Shows discriminant, roots, and step-by-step solutions.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['equation solver', 'quadratic equation solver', 'linear equation solver', 'solve equations', 'algebra solver', 'quadratic formula', 'equation calculator', 'math equation solver'],
    schema: 'both',
    mathSolverExpression: 'ax² + bx + c = 0 → x = (-b ± √(b²-4ac))/(2a)',
    lastVerified: '2026-01-15',
    relatedIds: ['quadratic-equation-calculator', 'slope-calculator', 'distance-calculator', 'matrix-calculator'],
    loader: () => import('../math/equation-solver/index'),
  },
  {
    id: 'system-of-equations',
    title: 'System of Equations Solver — 2-Variable Linear System',
    shortTitle: 'System Solver',
    description: 'Solve systems of two linear equations using the Cramer Rule determinant method. Get step-by-step solutions for unique, infinite, or no solution cases.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['system of equations solver', 'simultaneous equations', 'two variable equations', 'cramers rule', 'solve system of equations', 'linear system solver', 'algebra system solver', 'equation system'],
    schema: 'both',
    mathSolverExpression: 'a₁x + b₁y = c₁, a₂x + b₂y = c₂',
    lastVerified: '2026-05-15',
    relatedIds: ['equation-solver', 'matrix-calculator', 'slope-calculator', 'distance-calculator'],
    relatedPosts: ['pythagorean-theorem-guide'],
    loader: () => import('../math/system-of-equations/index'),
  },
  {
    id: 'base-converter',
    title: 'Number Base Converter — Convert Between Any Bases 2-36',
    shortTitle: 'Base Converter',
    description: 'Convert numbers between any two bases from binary (base 2) to base 36. Supports hexadecimal, octal, binary, and all custom bases.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['base converter', 'number base converter', 'binary to hex', 'hex to decimal', 'base conversion', 'binary converter', 'hex converter', 'octal converter', 'base 36 converter'],
    schema: 'both',
    mathSolverExpression: 'convert(n, from_base, to_base) | convert between binary, octal, decimal, hex, and arbitrary bases 2-36',
    lastVerified: '2026-05-17',
    relatedIds: ['binary-hex-calculator', 'scientific-notation-calculator', 'big-number-calculator', 'rounding-calculator'],
    relatedPosts: ['fractions-math-guide', 'probability-math-guide'],
    loader: () => import('../math/base-converter/index'),
  },
  {
    id: 'derivative-calculator',
    title: 'Derivative Calculator — Differentiate Polynomials Step by Step',
    shortTitle: 'Derivative Calc',
    description: 'Compute derivatives of polynomial expressions using the power rule. Get step-by-step differentiation and evaluate at any point.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['derivative calculator', 'differentiation calculator', 'symbolic derivative', 'power rule derivative', 'calculus derivative', 'differentiate polynomial', 'step by step derivative', 'calculus calculator'],
    schema: 'both',
    mathSolverExpression: 'd/dx(axⁿ) = a·n·xⁿ⁻¹',
    lastVerified: '2026-01-15',
    relatedIds: ['integral-calculator', 'limit-calculator', 'taylor-series', 'equation-solver'],
    loader: () => import('../math/derivative-calculator/index'),
  },
  {
    id: 'trigonometry-calculator',
    title: 'Trigonometry Calculator — Compute Sin, Cos, Tan & Inverse Trig',
    shortTitle: 'Trig Calculator',
    description: 'Calculate sine, cosine, tangent and their reciprocals for any angle. Also find angles from trig values with reference angles.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['trigonometry calculator', 'sin cos tan calculator', 'trig function calculator', 'inverse trig calculator', 'trigonometric functions', 'sine cosine tangent', 'trig values', 'angle calculator'],
    schema: 'both',
    mathSolverExpression: 'sin θ, cos θ, tan θ',
    lastVerified: '2026-01-15',
    relatedIds: ['unit-circle', 'inverse-trig', 'law-of-sines', 'law-of-cosines'],
    loader: () => import('../math/trigonometry-calculator/index'),
  },
  {
    id: 'unit-circle',
    title: 'Unit Circle Calculator — Coordinates, Angles & Trig Values',
    shortTitle: 'Unit Circle',
    description: 'Explore the unit circle by entering any angle. See coordinates, trigonometric values, reference angles, and the quadrant instantly.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['unit circle calculator', 'unit circle trig', 'reference angle calculator', 'trig unit circle', 'unit circle coordinates', 'sin cos unit circle', 'radians calculator', 'unit circle angles'],
    schema: 'both',
    mathSolverExpression: 'x = cos θ, y = sin θ on x² + y² = 1',
    lastVerified: '2026-05-15',
    relatedIds: ['trigonometry-calculator', 'inverse-trig', 'law-of-sines', 'law-of-cosines'],
    relatedPosts: ['pythagorean-theorem-guide'],
    loader: () => import('../math/unit-circle/index'),
  },
  {
    id: 'factoring-calculator',
    title: 'Factoring Calculator — Factor Quadratic Polynomials Step by Step',
    shortTitle: 'Factoring Calc',
    description: 'Factor quadratic polynomials (ax² + bx + c) into their factored form with step-by-step work. Find the factors and zeros of any quadratic expression.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['factoring calculator', 'factor polynomial', 'quadratic factoring', 'factor expression', 'algebra factoring', 'polynomial factor', 'factor quadratic', 'factoring step by step'],
    schema: 'both',
    mathSolverExpression: 'ax² + bx + c = a(x - r₁)(x - r₂)',
    lastVerified: '2026-01-15',
    relatedIds: ['polynomial-calculator', 'quadratic-equation-calculator', 'equation-solver', 'common-factor-calculator'],
    loader: () => import('../math/factoring-calculator/index'),
  },
  {
    id: 'polynomial-calculator',
    title: 'Polynomial Calculator — Evaluate & Analyze Polynomials',
    shortTitle: 'Polynomial Calc',
    description: 'Evaluate polynomials at any point, see the degree, and get step-by-step substitution work. Enter coefficients for polynomials of any degree.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['polynomial calculator', 'evaluate polynomial', 'polynomial degree', 'polynomial evaluation', 'polynomial function', 'horner method', 'polynomial expression', 'algebra calculator'],
    schema: 'both',
    mathSolverExpression: 'P(x) = aₙxⁿ + aₙ₋₁xⁿ⁻¹ + ... + a₁x + a₀',
    lastVerified: '2026-05-17',
    relatedIds: ['factoring-calculator', 'equation-solver', 'quadratic-equation-calculator', 'derivative-calculator'],
    relatedPosts: ['fractions-math-guide'],
    loader: () => import('../math/polynomial-calculator/index'),
  },
  {
    id: 'prime-number',
    title: 'Prime Number Calculator — Check Primality & Find Factors',
    shortTitle: 'Prime Checker',
    description: 'Check if any number is prime using trial division. Find its prime factorization, count all divisors, and see step-by-step primality verification.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['prime number calculator', 'prime checker', 'prime factor calculator', 'is prime', 'prime factorization', 'prime test', 'prime number test', 'factorization calculator'],
    schema: 'both',
    mathSolverExpression: 'n is prime if divisible only by 1 and itself',
    lastVerified: '2026-05-17',
    relatedIds: ['factorial-calculator', 'fibonacci', 'prime-factorization-calculator', 'factor-calculator', 'lcm-calculator'],
    relatedPosts: ['fractions-math-guide'],
    loader: () => import('../math/prime-number/index'),
  },
  {
    id: 'factorial-calculator',
    title: 'Factorial Calculator — Compute n! with Steps — Free Online Calculator',
    shortTitle: 'Factorial Calculator',
    description: 'Calculate the factorial of any number from 0 to 170. Shows the step-by-step multiplication, digit count, and trailing zeros.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['factorial calculator', 'n factorial', 'factorial of a number', 'math factorial', 'factorial function', 'n factorial calculator', 'factorial step by step', 'permutation calculator'],
    schema: 'both',
    mathSolverExpression: 'n! = n × (n-1) × (n-2) × ... × 1',
    lastVerified: '2026-01-15',
    relatedIds: ['permutation-combination-calculator', 'probability-calculator', 'prime-number', 'number-sequence-calculator'],
    loader: () => import('../math/factorial-calculator/index'),
  },
  {
    id: 'fibonacci',
    title: 'Fibonacci Calculator — Find nth Term & Sequence — Calculator',
    shortTitle: 'Fibonacci Calculator',
    description: 'Calculate the nth Fibonacci number, view the full sequence, and get the sum. Uses iteration and the Binet formula for verification. Free, instant, and accurate.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['fibonacci calculator', 'fibonacci sequence', 'nth fibonacci number', 'fibonacci number generator', 'fibonacci series', 'fibonacci sequence calculator', 'golden ratio', 'fibonacci formula'],
    schema: 'both',
    mathSolverExpression: 'F(n) = F(n-1) + F(n-2), F(1) = 1, F(2) = 1',
    relatedPosts: ['probability-math-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['number-sequence-calculator', 'ratio-calculator', 'factorial-calculator', 'prime-number'],
    loader: () => import('../math/fibonacci/index'),
  },
  {
    id: 'law-of-sines',
    title: 'Law of Sines Calculator — Solve Triangle Sides & Angles',
    shortTitle: 'Law of Sines',
    description: 'Apply the law of sines to solve triangles. Enter known side-angle pairs to find missing sides, angles, and the circumradius.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['law of sines calculator', 'sine law', 'triangle solver', 'sine rule', 'triangle sides calculator', 'triangle angles', 'law of sines triangle', 'a/sinA = b/sinB'],
    schema: 'both',
    mathSolverExpression: 'a/sin(A) = b/sin(B) = c/sin(C) = 2R',
    lastVerified: '2026-01-15',
    relatedIds: ['law-of-cosines', 'trigonometry-calculator', 'triangle-calculator', 'pythagorean-theorem-calculator'],
    loader: () => import('../math/law-of-sines/index'),
  },
  {
    id: 'law-of-cosines',
    title: 'Law of Cosines Calculator — Side & Angle Solver — Calculator',
    shortTitle: 'Law of Cosines',
    description: 'Solve triangles using the law of cosines. Find missing sides (SSS) or angles (SAS) with step-by-step work. Free, instant, and accurate.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['law of cosines calculator', 'cosine law', 'cosine rule', 'triangle side calculator', 'triangle angle calculator', 'SSS triangle', 'SAS triangle', 'c² = a² + b² - 2ab cos C'],
    schema: 'both',
    mathSolverExpression: 'c² = a² + b² - 2ab cos(C)',
    lastVerified: '2026-01-15',
    relatedIds: ['law-of-sines', 'trigonometry-calculator', 'triangle-calculator', 'pythagorean-theorem-calculator'],
    loader: () => import('../math/law-of-cosines/index'),
  },
  {
    id: 'inverse-trig',
    title: 'Inverse Trig Calculator — Arcsin, Arccos, Arctan Values',
    shortTitle: 'Inverse Trig',
    description: 'Compute inverse trigonometric functions: arcsin, arccos, and arctan. Get results in degrees and radians with the principal value.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['inverse trig calculator', 'arcsin calculator', 'arccos calculator', 'arctan calculator', 'inverse sine', 'inverse cosine', 'inverse tangent', 'trig inverse functions'],
    schema: 'both',
    mathSolverExpression: 'arcsin, arccos, arctan',
    relatedPosts: ['standard-deviation-statistics-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['trigonometry-calculator', 'unit-circle', 'law-of-sines', 'law-of-cosines'],
    loader: () => import('../math/inverse-trig/index'),
  },
  {
    id: 'integral-calculator',
    title: 'Integral Calculator — Compute Definite Integrals Numerically',
    shortTitle: 'Integral Calc',
    description: 'Calculate definite integrals numerically using Simpsons rule with step-by-step formula breakdown. Supports polynomial, trig, and exponential functions.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['integral calculator', 'definite integral', 'numerical integration', 'simpsons rule', 'calculus integral', 'area under curve', 'integration calculator', 'compute integral'],
    schema: 'both',
    mathSolverExpression: '∫ₐᵇ f(x)dx',
    lastVerified: '2026-01-15',
    relatedIds: ['derivative-calculator', 'limit-calculator', 'taylor-series', 'area-perimeter-calculator'],
    loader: () => import('../math/integral-calculator/index'),
  },
  {
    id: 'limit-calculator',
    title: 'Limit Calculator — Evaluate Limits with Step-by-Step',
    shortTitle: 'Limit Calc',
    description: 'Compute limits of functions as x approaches any value. Evaluate left-hand, right-hand, and two-sided limits with approach tables.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['limit calculator', 'limit of function', 'calculus limit', 'evaluate limit', 'left hand limit', 'right hand limit', 'limit solver', 'approach limit'],
    schema: 'both',
    mathSolverExpression: 'lim(x→a) f(x)',
    lastVerified: '2026-01-15',
    relatedIds: ['derivative-calculator', 'integral-calculator', 'taylor-series', 'series'],
    loader: () => import('../math/limit-calculator/index'),
  },
  {
    id: 'series',
    title: 'Series Calculator — Sum a Series from n Start to End',
    shortTitle: 'Series Sum',
    description: 'Sum mathematical series from any start to end value. Supports expressions with n, exponents, and common mathematical functions.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['series calculator', 'sum of series', 'series summation', 'arithmetic series', 'geometric series', 'sum of terms', 'series sum calculator', 'partial sum'],
    schema: 'both',
    mathSolverExpression: 'S = Σ f(n) from n=start to n=end | sum of a series',
    lastVerified: '2026-05-15',
    relatedIds: ['taylor-series', 'limit-calculator', 'number-sequence-calculator', 'integral-calculator'],
    relatedPosts: ['probability-math-guide'],
    loader: () => import('../math/series/index'),
  },
  {
    id: 'taylor-series',
    title: 'Taylor Series Calculator — Expand Functions as Power Series',
    shortTitle: 'Taylor Series',
    description: 'Compute Taylor series of common functions like e^x, sin(x), cos(x) around any center point. Adjust the expansion order for accurate polynomial approximation.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['taylor series calculator', 'taylor expansion', 'power series', 'maclaurin series', 'function expansion', 'taylor polynomial', 'taylor series expansion', 'approximate function'],
    schema: 'both',
    mathSolverExpression: 'f(x) = Σ f⁽ⁿ⁾(a)(x-a)ⁿ/n!',
    lastVerified: '2026-05-15',
    relatedIds: ['series', 'limit-calculator', 'derivative-calculator', 'integral-calculator'],
    relatedPosts: ['probability-math-guide'],
    loader: () => import('../math/taylor-series/index'),
  },
  {
    id: 'vector-calculator',
    title: 'Vector Calculator — Add, Subtract, Dot & Cross Products',
    shortTitle: 'Vector Calc',
    description: 'Compute vector operations including addition, subtraction, dot product, cross product, magnitudes, and the angle between vectors in 2D or 3D.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['vector calculator', 'vector addition', 'vector subtraction', 'dot product', 'cross product', 'vector magnitude', 'angle between vectors', '3D vector calculator'],
    schema: 'both',
    mathSolverExpression: 'a·b = |a||b|cos θ',
    relatedPosts: ['standard-deviation-statistics-guide'],
    lastVerified: '2026-01-15',
    relatedIds: ['cross-product', 'dot-product', 'matrix-calculator', 'distance-calculator'],
    loader: () => import('../math/vector-calculator/index'),
  },
  {
    id: 'cross-product',
    title: 'Cross Product Calculator — 3D Vector Cross Product',
    shortTitle: 'Cross Product',
    description: 'Compute the cross product of two 3D vectors. Shows the resulting vector, magnitude, unit vector, and area of the parallelogram.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['cross product calculator', 'vector cross product', '3D cross product', 'vector product', 'a x b calculator', 'cross product vector', 'right hand rule', 'cross product magnitude'],
    schema: 'both',
    mathSolverExpression: 'a × b = |a||b|sin θ n̂',
    lastVerified: '2026-01-15',
    relatedIds: ['dot-product', 'vector-calculator', 'matrix-calculator', 'pythagorean-theorem-calculator'],
    loader: () => import('../math/cross-product/index'),
  },
  {
    id: 'dot-product',
    title: 'Dot Product Calculator — Vector Dot Product & Angle',
    shortTitle: 'Dot Product',
    description: 'Calculate the dot product of two vectors, the angle between them, and determine if they are orthogonal. Supports 2D and 3D vectors.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Algebra',
    seoKeywords: ['dot product calculator', 'vector dot product', 'scalar product', 'dot product vectors', 'angle between vectors', 'orthogonal vectors', 'vector projection', 'inner product'],
    schema: 'both',
    mathSolverExpression: 'a·b = a₁b₁ + a₂b₂ + a₃b₃',
    lastVerified: '2026-01-15',
    relatedIds: ['cross-product', 'vector-calculator', 'matrix-calculator', 'slope-calculator'],
    loader: () => import('../math/dot-product/index'),
  },
  {
    id: 'proportion-calculator',
    title: 'Proportion Calculator — Solve a/b = c/d for Missing Value',
    shortTitle: 'Proportion Solver',
    description: 'Solve proportion equations a/b = c/d for any missing value. Enter three known values and find the fourth using cross-multiplication.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['proportion calculator', 'solve proportion', 'cross multiplication calculator', 'ratio proportion calculator', 'missing value proportion', 'a/b = c/d', 'proportion solver'],
    schema: 'both',
    mathSolverExpression: 'a/b = c/d → a×d = b×c',
    lastVerified: '2026-05-17',
    relatedIds: ['ratio-calculator', 'fraction-calculator', 'math-percentage-calculator'],
    relatedPosts: ['fractions-math-guide'],
    loader: () => import('../math/proportion-calculator/index'),
  },
  {
    id: 'common-denominator',
    title: 'Common Denominator Calculator — Find LCD for Fractions',
    shortTitle: 'Common Denominator',
    description: 'Find the least common denominator (LCD) for fractions. Convert each to equivalent form using LCM step-by-step calculations and scaling factors.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'Number Theory',
    seoKeywords: ['common denominator calculator', 'least common denominator', 'LCD calculator', 'find common denominator', 'fraction denominator', 'fraction converter'],
    schema: 'both',
    mathSolverExpression: 'LCD = LCM(denominators) | find least common denominator for fractions',
    lastVerified: '2026-05-17',
    relatedIds: ['lcm-calculator', 'gcf-calculator', 'fraction-calculator', 'ratio-calculator'],
    relatedPosts: ['fractions-math-guide'],
    loader: () => import('../math/common-denominator/index'),
  },
  {
    id: 'test-score-calculator',
    title: 'Test Score Calculator — Final Exam Grade Needed — Calculator',
    shortTitle: 'Test Score',
    description: 'Calculate what grade you need on your final exam to achieve your target overall grade. Handles weighted grading systems with impossible target detection.',
    category: 'Mathematics',
    categorySlug: 'math',
    subCategory: 'General',
    seoKeywords: ['test score calculator', 'final exam calculator', 'grade needed calculator', 'final grade calculator', 'exam score calculator', 'what do I need on my final'],
    schema: 'both',
    mathSolverExpression: 'needed = (desired - current x (1 - weight)) / weight | final exam score needed for target grade',
    lastVerified: '2026-01-15',
    relatedIds: ['grade-calculator', 'average-calculator', 'gpa-calculator'],
    loader: () => import('../math/test-score/index'),
  },
  // love-calculator lives at /everyday/love-calculator/ (its natural home); the
  // duplicate /math/ entry was removed to avoid two URLs sharing identical content.
];
