import { createElement } from 'react';
import { CalculatorConfig } from '../../../types/calculator';
import CookieConsentPanel from './CookieConsentPanel';

function generateHtmlCode(siteName: string, position: string, layout: string, colorTheme: string): string {
  const sanitized = siteName || 'My Website';
  const isDark = colorTheme === 'Dark';
  const isCustom = colorTheme === 'Custom';
  const bg = isDark ? '#1e293b' : isCustom ? '#0f172a' : '#ffffff';
  const text = isDark ? '#f1f5f9' : isCustom ? '#e2e8f0' : '#1e293b';
  const accent = isDark ? '#3b82f6' : isCustom ? '#06b6d4' : '#2563eb';
  const btnText = isDark ? '#ffffff' : isCustom ? '#0f172a' : '#ffffff';
  const border = isDark ? '#334155' : isCustom ? '#1e293b' : '#e2e8f0';

  let positionCss: string;
  switch (position) {
    case 'center-modal':
      positionCss = 'position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 9999; max-width: 440px;';
      break;
    case 'corner-widget':
      positionCss = 'position: fixed; bottom: 20px; right: 20px; z-index: 9999; max-width: 360px;';
      break;
    default: // bottom banner
      positionCss = 'position: fixed; bottom: 0; left: 0; right: 0; z-index: 9999;';
  }

  const isMinimal = layout === 'minimal';
  const isDev = layout === 'developer';

  const html = `<!-- Cookie Consent Banner - Generated by TheCalcUniverse -->
<div style="
  ${positionCss}
  background: ${bg};
  color: ${text};
  padding: ${isMinimal ? '12px 16px' : '20px 24px'};
  border-radius: ${position === 'bottom-banner' ? '0' : '12px'};
  border: 1px solid ${border};
  box-shadow: 0 10px 40px rgba(0,0,0,0.2);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  font-size: 14px;
  line-height: 1.5;
">
  ${isMinimal
    ? `<div style="display: flex; align-items: center; gap: 12px; justify-content: space-between;">
        <p style="margin: 0; color: ${text};">This site uses cookies to improve your experience.</p>
        <div style="display: flex; gap: 8px;">
          <button onclick="this.closest('[style*=\\'fixed\\']').remove()" style="background: transparent; color: ${text}; border: 1px solid ${border}; padding: 6px 12px; border-radius: 6px; cursor: pointer; font-size: 13px;">Decline</button>
          <button onclick="this.closest('[style*=\\'fixed\\']').remove()" style="background: ${accent}; color: ${btnText}; border: none; padding: 6px 16px; border-radius: 6px; cursor: pointer; font-size: 13px; font-weight: 600;">Accept</button>
        </div>
      </div>`
    : isDev
    ? `<div>
        <p style="margin: 0 0 12px 0; font-weight: 600; color: ${text};">🍪 Cookie Notice — ${sanitized}</p>
        <p style="margin: 0 0 16px 0; font-size: 13px; color: ${isDark ? '#cbd5e1' : '#64748b'};">We use cookies and similar technologies. By continuing, you agree to our <a href="#" style="color: ${accent}; text-decoration: underline;">Cookie Policy</a>.</p>
        <div style="display: flex; gap: 8px; flex-wrap: wrap;">
          <button onclick="this.closest('[style*=\\'fixed\\']').remove()" style="background: transparent; color: ${text}; border: 1px solid ${border}; padding: 8px 16px; border-radius: 6px; cursor: pointer; font-size: 13px;">Cookie Settings</button>
          <button onclick="this.closest('[style*=\\'fixed\\']').remove()" style="background: ${accent}; color: ${btnText}; border: none; padding: 8px 20px; border-radius: 6px; cursor: pointer; font-size: 13px; font-weight: 600;">Accept All</button>
          <button onclick="this.closest('[style*=\\'fixed\\']').remove()" style="background: transparent; color: ${isDark ? '#64748b' : '#94a3b8'}; border: 1px solid ${border}; padding: 8px 16px; border-radius: 6px; cursor: pointer; font-size: 13px;">Decline</button>
        </div>
      </div>`
    : `<div style="text-align: ${position === 'center-modal' ? 'center' : 'left'};">
        <div style="font-size: 24px; margin-bottom: 8px;">🍪</div>
        <p style="margin: 0 0 4px 0; font-weight: 600; font-size: 16px; color: ${text};">Cookies &amp; Privacy</p>
        <p style="margin: 0 0 16px 0; font-size: 13px; color: ${isDark ? '#cbd5e1' : '#64748b'};">${sanitized} uses cookies to enhance your browsing experience, serve personalized content, and analyze traffic. By clicking "Accept All", you consent to our use of cookies.</p>
        <div style="display: flex; gap: 10px; justify-content: ${position === 'center-modal' ? 'center' : 'flex-start'}; flex-wrap: wrap;">
          <button onclick="this.closest('[style*=\\'fixed\\']').remove()" style="background: transparent; color: ${text}; border: 1px solid ${border}; padding: 10px 18px; border-radius: 8px; cursor: pointer; font-size: 13px;">Customize</button>
          <button onclick="this.closest('[style*=\\'fixed\\']').remove()" style="background: ${accent}; color: ${btnText}; border: none; padding: 10px 24px; border-radius: 8px; cursor: pointer; font-size: 13px; font-weight: 600;">Accept All</button>
        </div>
        <div style="margin-top: 12px; font-size: 11px; color: ${isDark ? '#64748b' : '#94a3b8'};">
          <a href="#" style="color: ${accent}; text-decoration: none;">Privacy Policy</a>
          <span style="margin: 0 6px;">·</span>
          <a href="#" style="color: ${accent}; text-decoration: none;">Cookie Policy</a>
        </div>
      </div>`
  }
</div>`;

  return html;
}

function generateCssCode(position: string, colorTheme: string): string {
  return `/* Cookie Consent Banner Styles for ${position} position, ${colorTheme} theme */
.cookie-banner-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  z-index: 9998;
}
.cookie-consent-banner {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  z-index: 9999;
}
@media (max-width: 640px) {
  .cookie-consent-banner {
    left: 10px !important;
    right: 10px !important;
    max-width: none !important;
    transform: none !important;
    top: auto !important;
    bottom: 10px !important;
  }
}`;
}

function generatePreviewText(siteName: string, position: string, layout: string): string {
  const name = siteName || 'My Website';
  return `Cookie Consent Banner for "${name}"
- Position: ${position}
- Layout: ${layout}
- Description: A ${layout.toLowerCase()} cookie consent banner that appears as a ${position === 'bottom-banner' ? 'bottom banner' : position === 'center-modal' ? 'center modal' : 'corner widget'}.
- Includes Accept, Decline, and Customize buttons.
- GDPR-compliant with privacy policy links.`;
}

const cookieConsentConfig: CalculatorConfig = {
  inputs: [
    {
      id: 'siteName',
      label: 'Site Name',
      type: 'text',
      placeholder: 'My Website',
      helpText: 'Your website name — appears in the banner text',
    },
    {
      id: 'position',
      label: 'Banner Position',
      type: 'select',
      required: true,
      helpText: 'Choose where the cookie consent banner appears on the page',
      options: [
        { label: 'Bottom Banner', value: 'bottom-banner' },
        { label: 'Center Modal', value: 'center-modal' },
        { label: 'Corner Widget', value: 'corner-widget' },
      ],
    },
    {
      id: 'layout',
      label: 'Layout Style',
      type: 'select',
      required: true,
      helpText: 'Default is full, Minimal is compact, Developer includes cookie settings options',
      options: [
        { label: 'Default', value: 'default' },
        { label: 'Minimal', value: 'minimal' },
        { label: 'Developer', value: 'developer' },
      ],
    },
    {
      id: 'colorTheme',
      label: 'Color Theme',
      type: 'select',
      required: true,
      helpText: 'Choose a light, dark, or custom color scheme for the banner',
      options: [
        { label: 'Light', value: 'Light' },
        { label: 'Dark', value: 'Dark' },
        { label: 'Custom', value: 'Custom' },
      ],
    },
  ],
  calculate: (values) => {
    const siteName = values.siteName || 'My Website';
    const position = values.position || 'bottom-banner';
    const layout = values.layout || 'default';
    const colorTheme = values.colorTheme || 'Light';

    const htmlCode = generateHtmlCode(siteName, position, layout, colorTheme);
    const cssCode = generateCssCode(position, colorTheme);
    const fullCode = `<!-- Cookie Consent Banner for ${siteName} -->\n<style>\n${cssCode}\n</style>\n${htmlCode}`;
    const previewText = generatePreviewText(siteName, position, layout);

    const posLabels: Record<string, string> = {
      'bottom-banner': 'Bottom Banner',
      'center-modal': 'Center Modal',
      'corner-widget': 'Corner Widget',
    };

    const layoutLabels: Record<string, string> = {
      default: 'Default',
      minimal: 'Minimal',
      developer: 'Developer',
    };

    return [
      { id: 'htmlCode', label: 'HTML Code', value: htmlCode, highlight: true },
      { id: 'cssCode', label: 'CSS Code', value: cssCode, color: 'neutral' },
      { id: 'fullCode', label: 'Full Code (HTML + CSS)', value: fullCode, highlight: true },
      { id: 'previewText', label: 'Preview Description', value: previewText, color: 'neutral' },
      { id: 'position', label: 'Banner Position', value: posLabels[position] || position },
      { id: 'layout', label: 'Layout Style', value: layoutLabels[layout] || layout },
      { id: 'colorTheme', label: 'Color Theme', value: colorTheme },
    ];
  },
  extraPanel: (values, results) => {
    if (!results.length) return null;
    return createElement(CookieConsentPanel, { values, results });
  },
  educational: {
    formula: 'GDPR: valid consent must be freely given, specific, informed, and unambiguous | ePrivacy Directive (Cookie Law): opt-in required for non-essential cookies',
    diagram: {
      svg: '<svg viewBox="0 0 440 340" xmlns="http://www.w3.org/2000/svg" style="max-width:100%;height:auto"><rect x="40" y="60" width="360" height="240" fill="var(--svg-f8fafc)" stroke="var(--svg-e2e8f0)" stroke-width="1" rx="8"/><text x="220" y="100" text-anchor="middle" font-size="16" fill="var(--svg-333333)">This site uses cookies</text><text x="220" y="130" text-anchor="middle" font-size="12" fill="var(--svg-666666)">We use cookies to improve your experience.</text><rect x="60" y="160" width="140" height="40" fill="var(--svg-22c55e)" rx="8"/><text x="130" y="185" text-anchor="middle" font-size="13" fill="var(--svg-ffffff)">Accept All</text><rect x="220" y="160" width="140" height="40" fill="var(--svg-ef4444)" rx="8"/><text x="290" y="185" text-anchor="middle" font-size="13" fill="var(--svg-ffffff)">Decline</text><rect x="140" y="220" width="160" height="30" fill="var(--svg-3b82f6)" rx="6"/><text x="220" y="240" text-anchor="middle" font-size="12" fill="var(--svg-ffffff)">Cookie Settings</text></svg>',
      alt: 'Cookie consent banner with Accept, Decline, and Settings buttons',
      caption: 'Cookie consent banner — users must actively choose before non-essential cookies load',
    },
    formulaDescription:
      'Cookie consent banners are a legal requirement under the EU General Data Protection Regulation (GDPR) and the ePrivacy Directive (Cookie Law). Users must be informed about cookies AND give active consent before non-essential cookies are placed. The banner must include: a clear description of cookie usage, an Accept button, a Decline/Reject button, and a link to detailed privacy/cookie policies.',
    variables: [
      { symbol: 'GDPR', name: 'General Data Protection Regulation', description: 'EU regulation governing data protection and privacy. Requires valid consent for personal data processing, including cookie tracking.' },
      { symbol: 'ePrivacy', name: 'ePrivacy Directive (Cookie Law)', description: 'EU directive requiring opt-in consent for storing/accessing information on a user\'s device. This is the "cookie law".' },
      { symbol: 'Essential Cookies', name: 'Strictly Necessary Cookies', description: 'Cookies required for basic website functionality (session management, authentication). These do NOT require consent.' },
      { symbol: 'Non-Essential Cookies', name: 'Non-Essential Cookies', description: 'Cookies for analytics, advertising, tracking, and personalization. These require explicit opt-in consent.' },
    ],
    howToUse: [
      'Enter your website name.',
      'Choose the banner position (bottom, center modal, or corner widget).',
      'Select a layout style (default, minimal, or developer).',
      'Choose a color theme (light, dark, or custom).',
      'Copy the generated HTML/CSS code and paste it into your website.',
      'The live preview updates in real time as you change settings.',
    ],
    explanation:
      'Cookie consent banners are legally required for websites serving users in the European Union and European Economic Area. Under GDPR Article 7 and the ePrivacy Directive, consent must be "freely given, specific, informed, and unambiguous" — meaning pre-checked boxes and implied consent are no longer valid. The banner must allow users to both accept AND reject non-essential cookies with equal ease (no "dark patterns" like making Decline harder to find than Accept). Essential cookies (session management, authentication, load balancing) are exempt. Analytics, advertising, tracking, and personalization cookies all require explicit opt-in. Fines for non-compliance can reach 4% of annual global revenue or EUR 20 million, whichever is greater.',
    commonUses: [
      'Adding GDPR-compliant cookie consent banners to European-facing websites to meet legal privacy requirements',
      'Generating ready-to-use HTML and CSS code for cookie consent banners with different layouts, positions, and color themes',
      'Understanding cookie consent legal requirements under GDPR and the ePrivacy Directive to avoid regulatory fines',
    ],
    faqs: [
      {
        question: 'Is a cookie consent banner really required?',
        answer: 'Yes, if your website serves users in the EU/EEA and uses any non-essential cookies (analytics, tracking, advertising, personalization). Essential cookies (session management, authentication) are exempt. Many countries outside the EU have similar laws (UK, Brazil LGPD, California CCPA/CPRA).',
      },
      {
        question: 'What is the difference between GDPR and ePrivacy?',
        answer: 'GDPR covers all personal data processing, including cookies. The ePrivacy Directive (Cookie Law) specifically covers cookies and similar tracking technologies. Both apply to cookie consent. GDPR requires a legal basis (consent is one option), while ePrivacy specifically requires opt-in consent for non-essential cookies.',
      },
      {
        question: 'What are "dark patterns" in cookie banners?',
        answer: 'Dark patterns are UI designs that make it easier to accept cookies than to reject them. Examples: making the Decline button grayed out or harder to find, requiring multiple clicks to reject vs. one click to accept, or using confusing language. These violate GDPR requirements for "freely given" consent and can result in fines.',
      },
    ],
    citations: [
      { source: 'Wikipedia', title: 'Cookie Consent', url: 'https://en.wikipedia.org/wiki/Cookie_consent' },
      { source: 'GDPR.eu', title: 'Cookie Consent Under GDPR', url: 'https://gdpr.eu/cookies/' },
    ],
  },
};

export default cookieConsentConfig;
